Implement update_publish_items endpoint [RHELDST-2160]
release-engineering/exodus-gw pull request #102
Opened 2020-12-10 18:04 UTC by nathanegillett

Includes introduction of the Item schema and model and the Publish
model's items attribute.

Co-authored-by: lioramilbaum <lmilbaum@redhat.com>

2020-12-10 18:13 UTC, nathanegillett commented
Replaces #94

2021-01-07 15:55 UTC, crungehottman commented on exodus_gw/routers/gateway.py
> +    return {}
The example in the AC suggests that the response would return `{"200": "OK"}` instead of an empty dict -- I see the status code is included on line 47, but I wonder if there is some benefit to returning a non-empty dict?

2021-01-07 16:02 UTC, nathanegillett commented on exodus_gw/routers/gateway.py
> +    return {}
It looked strange to me too but @rohanpm explained its purpose on #94: https://github.com/release-engineering/exodus-gw/pull/94#discussion_r538893708
Basically, it still serves as an empty response but allows us to add fields down the road.

2021-01-07 16:14 UTC, crungehottman approved these changes

2021-01-12 00:53 UTC, rohanpm requested changes
I think there are some issues with type declarations.

About the typing info, I think it's only needed for the FastAPI endpoints because FastAPI will use it to automate some things.  I'm in favor of adding it in other places as well as a kind of documentation, but it's a little surprising that none of the existing test tools are finding mistakes here (does pylint really not detect a wrong return type?)

If you also want to keep adding the typing info in other places, you might want to look into whether your editor can be configured to parse it and find issues.

2021-01-12 00:53 UTC, rohanpm commented on exodus_gw/crud.py
> +def create_publish(db: Session) -> List[models.Publish]:
Is the return type here correct?  It doesn't seem to return a list.

2021-01-12 00:53 UTC, rohanpm commented on exodus_gw/crud.py
> +    items: schemas.ItemBase or List[schemas.ItemBase],
Hmm, I'm not sure this typing declaration is correct.  If there is not some magic going on deep in the python interpreter, then this 'or' should be just the standard python boolean operator which means that it's just going to return the first truthy value out of the two.  So this is probably equal to just 'schemas.ItemBase' exactly.

A quick test at the console seems to bear this out:

```
>>> import typing
>>> import inspect

# Try to declare a function which accepts a str, or list of str
>>> def myfn(list_or_str: typing.List[str] or str): pass
... 

# What signature do we actually end up with?
>>> inspect.signature(myfn)
<Signature (list_or_str: List[str])>

# => since "truthy1 or truthy2" is always going to return truthy1, the second part is simply lost
```

I believe the correct way is to use Union:

```
typing.Union[schemas.ItemBase, List[schemas.ItemBase]]
```

2021-01-12 00:53 UTC, rohanpm commented on exodus_gw/routers/gateway.py
> +    items: schemas.ItemBase or List[schemas.ItemBase],
Same here about `or` not working the way you want for types.

2021-01-12 15:37 UTC, nathanegillett commented on exodus_gw/crud.py
> +def create_publish(db: Session) -> List[models.Publish]:
You're right. This was carried over from #94. Not sure what was originally intended but it's now corrected.

2021-01-12 15:42 UTC, nathanegillett commented
> About the typing info [...] I'm in favor of adding it in other places as well as a kind of documentation [...].
As am I.
> If you also want to keep adding the typing info in other places, you might want to look into whether your editor can be configured to parse it and find issues.
I'm using VS Code, which I believe you use as well. If so, any suggestions for this?

2021-01-14 02:44 UTC, rohanpm commented
> > If you also want to keep adding the typing info in other places, you might want to look into whether your editor can be configured to parse it and find issues.
> 
> I'm using VS Code, which I believe you use as well. If so, any suggestions for this?

No.  I'm using VS Code but haven't looked into this topic.  I've noticed that the typing info influences autocomplete, so sometimes mistakes can be detected indirectly that way.

2021-01-14 02:45 UTC, rohanpm approved these changes

2021-01-14 16:27 UTC, nathanegillett commented
> > > If you also want to keep adding the typing info in other places, you might want to look into whether your editor can be configured to parse it and find issues.
> > 
> > 
> > I'm using VS Code, which I believe you use as well. If so, any suggestions for this?
> 
> No. I'm using VS Code but haven't looked into this topic. I've noticed that the typing info influences autocomplete, so sometimes mistakes can be detected indirectly that way.

Ah, okay. I did a few searches for extensions but didn't come up with anything.

2021-01-14 16:27 UTC, merged