API for creating publish objects - initial commit
release-engineering/exodus-gw pull request #13
Opened 2020-08-27 06:15 UTC by lioramilbaum

/{env}/publish end point.

https://projects.engineering.redhat.com/browse/RHELDST-2159

2020-08-27 19:21 UTC, nathanegillett commented
What's the intended scope of this PR?
What you have looks okay but I'm not seeing where the API would connect to or create publish objects in the database. Is that coming later?

2020-08-31 10:12 UTC, lioramilbaum commented
The scope of this PR is to act as the MVP of the feature.  I am breaking the overall story implementation to baby steps/PRs, such that each PR is effectively re-viewable by the whole team.

2020-08-31 23:16 UTC, rohanpm commented on exodus_gw/gateway.py
> +    artifacts: list
We will need to define the model for the artifacts.

2020-08-31 23:18 UTC, rohanpm commented on exodus_gw/gateway.py
> +    if env not in ["dev", "qa", "stage", "prod"]:
I think these shouldn't be hardcoded - we'll need settings to define the details of each environment anyway, so those settings would also define the list of supported environments.  Maybe that should be done first?

2020-08-31 23:19 UTC, rohanpm commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
I don't think this endpoint is right, you need to add artifacts onto *a specific publish object* and not just send them to the service in general.

I would expect something more like:

```
@app.put("/{env}/publish/{publish_id}")
```

...meaning "add artifacts to the publish of the given ID".

It's also possible that env shouldn't be here because the service could already keep track of the environment on each publish object - not sure currently whether this is a good idea.  It might still make sense to keep env there anyway for a more consistent API.

2020-08-31 23:23 UTC, rohanpm commented on exodus_gw/publish.py
> +        "detail": "Publishing artifacts {0} in environment {1}".format(
I think we should keep these detail messages very terse, like just "publishing" in all successful cases and not have additional details on what was done.  Probably more detailed messages should be used only for errors.

The reasoning is that the messages are meant to be human-oriented, but if you put more detail in them there is a risk that someone starts parsing the messages to extract some details instead of using the API properly, essentially locking the format.

2020-08-31 23:24 UTC, rohanpm commented on exodus_gw/gateway.py
> +def publish(env: str, publishobject: PublishObject):
We'll need to define the response model.

2020-08-31 23:39 UTC, rohanpm commented on exodus_gw/gateway.py
> +    """Publish artifacts"""
API docs should be fleshed out at some point.

2020-09-01 13:47 UTC, nathanegillett commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
I think leaving the env for consistency is a good idea.

2020-09-01 14:49 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +    artifacts: list
Filed a sub-task to handle the model definition

2020-09-01 14:50 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
Where is the publish_id coming from? Do we have an end-point which produces publish_ids?

2020-09-01 14:52 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +def publish(env: str, publishobject: PublishObject):
Filed a sub-task to handle response model

2020-09-01 14:53 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +    """Publish artifacts"""
Filed a JIra issued to handle it

2020-09-01 15:01 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +    if env not in ["dev", "qa", "stage", "prod"]:
Filed an issue to handle this. Those can be worked in parallel.

2020-09-01 15:02 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +        return {"error": "environment {0} not found".format(env)}
This question will be addressed as soon as we define the response model.

2020-09-01 15:07 UTC, lioramilbaum commented on exodus_gw/publish.py
> +        "detail": "Publishing artifacts {0} in environment {1}".format(
+1 It should be addressed when dealing with the Response model

2020-09-01 16:32 UTC, lioramilbaum commented
The PR should not be merged till #15 is. Some of the code changes in this PR will be removed as soon as #15 is merged and this PR is rebased.

2020-09-01 16:36 UTC, nathanegillett commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
Generating the ID is one of the responsibilities of the publish method.
https://projects.engineering.redhat.com/browse/RHELDST-2159:
> The endpoint returns a unique "publish ID" for the created publish object (uuid.uuid4 recommended)

Also, issue 2158 doesn't include adding items/artifacts to the publish object in it's scope. That belongs to https://projects.engineering.redhat.com/browse/RHELDST-2160.

2020-09-01 16:45 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
@nathanegillett Than publish_id is unknown when calling the end-point. @rohanpm suggested with use the publish_id at calling time.

2020-09-01 16:47 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
> Also, issue 2158 doesn't include adding items/artifacts to the publish object in it's scope. That belongs to https://projects.engineering.redhat.com/browse/RHELDST-2160.

Does that mean that we should only create a publish_id with this end-point? I am a bit confused.

2020-09-01 16:51 UTC, lioramilbaum commented
> The corresponding issue for this PR is about creating the publish objects in the database. The publish endpoint should only be responsible for creating the publish database object and that object's ID. So, I don't think it's in scope to `publish_artifacts`; that's encroaching on https://projects.engineering.redhat.com/browse/RHELDST-2160, I believe.

I have read again the issue and figured out my confusion.  @nathanegillett thanks for that :-)

2020-09-01 16:54 UTC, nathanegillett commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
Yeah, @rohanpm is right, when adding items to a publish object, we'll need to provide the ID of that publish object so that the items go to the correct publish. Though, that shouldn't be in scope of 2159. 2159 is just about creating the publish object and returning that object's ID.

2020-09-01 16:55 UTC, nathanegillett commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
So, when the publish endpoint is called (/env/publish), a publish object should be created within the database and we should have the ID of the object to use later.

2020-09-02 13:23 UTC, nathanegillett commented on exodus_gw/publish.py
> +    }
I don't think this needs to be handled by a separate Jira issue or anything. It should be as simple as using uuid4 to generate a random ID. That ID will then be assigned to the publish when it's created in the database.

2020-09-02 16:25 UTC, lioramilbaum commented on exodus_gw/publish.py
> +    }
I am not sure this is the right path. Don't we want to create a new row in a publish ids table and than use this id as a foreign key in the artifacts table?

2020-09-02 19:12 UTC, nathanegillett commented on exodus_gw/publish.py
> +    }
Something along those lines, yes. But we need to create the ID before we can use it, right? Or do you expect the DB to generate the ID itself?

2020-09-02 23:25 UTC, rohanpm requested changes

2020-09-02 23:25 UTC, rohanpm commented on exodus_gw/publish.py
> +    pusblish_id = uuid.uuid4()
```suggestion
    publish_id = uuid.uuid4()
```

2020-09-02 23:25 UTC, rohanpm commented on exodus_gw/publish.py
> +            pusblish_id, env
```suggestion
            publish_id, env
```

2020-09-02 23:25 UTC, rohanpm commented on exodus_gw/publish.py
> +    return {
This doesn't make sense to me at all, why are we generating a publish ID and then only returning it embedded in a human-oriented message?  The point of generating an ID is to give it back to the caller, so that they can use it for further operations on the publish object.

2020-09-02 23:25 UTC, rohanpm commented on exodus_gw/gateway.py
> +    """Returns a new, empty publish id"""
In the current implementation it doesn't actually do this... the caller has no way of seeing the generated ID, which is really odd.

2020-09-03 08:17 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +@app.put("/{env}/publish")
As I wrote in a previous comment, I had a misunderstanding to what the scope of the issue. With that, the implementation was incorrect. @rohanpm and @nathanegillett your reviews helped me realize the confusion early. With that, there was a great value for this PR review.

2020-09-03 08:23 UTC, lioramilbaum commented on exodus_gw/publish.py
> +    return {
The response object will be defined and implemented in a separate sub-task. The purpose of this message is to establish a return value and the corresponding tests.

2020-09-03 13:29 UTC, nathanegillett commented on exodus_gw/gateway.py
> +    """Returns a new, empty publish id"""
I think his point is that the docstring should reflect the actual behavior of the function, regardless of our intentions for it.

2020-09-03 13:55 UTC, nathanegillett commented on test-requirements.txt
> +    # via -r test-requirements.in, pytest-asyncio, pytest-mock
I don't really understand what this comment is support to communicate. Wasn't it just to say that the pytest hash was generated from test-requirements.in? If that's the case, why are pytest-asyncio and pytest-mocked noted here?
@rohampm @lioramilbaum not sure who this question should go to.

2020-09-03 13:58 UTC, lioramilbaum commented on test-requirements.txt
> +    # via -r test-requirements.in, pytest-asyncio, pytest-mock
I can only guess that pytest is a dependency of both pytest-asyncio and pytest-mock. Maybe this is the reason why it is listed here.

2020-09-03 13:59 UTC, nathanegillett commented on exodus_gw/publish.py
> +    return {
I guess it doesn't matter too much at this stage but, if we're only concerned with returning something for the tests right now, wouldn't it be simpler to just return the bare publish_id as @rohanpm suggests?

2020-09-03 14:06 UTC, nathanegillett commented on exodus_gw/publish.py
> +    return {
Actually, I think in the end that's all this function should do, right? It only needs to return the publish_id to the caller, not some complex object. Or am I missing something?

2020-09-03 14:33 UTC, nathanegillett requested changes

2020-09-03 14:33 UTC, nathanegillett commented on exodus_gw/publish.py
> +    }
I think create_publish_id should just return the bare publish_id. I don't see a reason to place it in some other object, as the goal is to just get the ID back to the caller. If there is a reason to return a more complex structure here, could you explain that a bit?

Testing this should be easier also without a dict and strings to dig through.

2020-09-08 13:33 UTC, nathanegillett requested changes

2020-09-08 13:33 UTC, nathanegillett commented on exodus_gw/gateway.py
> +    """WIP: Returns a new, empty publish id"""
```suggestion
    """WIP: Returns a new publish id"""
```

2020-09-08 13:33 UTC, nathanegillett commented on exodus_gw/publish.py
> +    return {"detail": publish_id}
Sorry, I still don't understand the reason to return a dictionary.
This is just a backend function, right? So, it can just return `publish_id` to the caller, which, right now, is the publish endpoint.
```suggestion
    return publish_id
```
The caller can then expose to the user whatever details it needs to in the forthcoming response object.

2020-09-08 13:34 UTC, crungehottman commented on exodus_gw/publish.py
> +    return {"detail": publish_id}
+1

2020-09-08 15:41 UTC, lioramilbaum commented on exodus_gw/publish.py
> +    return {
The requirements from the response model were not collected yet. Not sure we need to block this PR over this.

2020-09-08 15:42 UTC, lioramilbaum commented on exodus_gw/publish.py
> +    return {"detail": publish_id}
See my previous comment

2020-09-08 20:25 UTC, nathanegillett commented on exodus_gw/publish.py
> +    return {
This function shouldn't need to return a response object, was my point. Simply `return publish_id` is all that will ever be needed.

2020-09-09 13:11 UTC, lioramilbaum commented on exodus_gw/publish.py
> +    return {
I am not sure of it and I would prefer not to over-engineer this. We will gain more understanding of what is needed as we drive this effort forward.

2020-09-09 14:40 UTC, crungehottman commented on exodus_gw/publish.py
> +    return {
> I am not sure of it and I would prefer not to over-engineer this. We will gain more understanding of what is needed as we drive this effort forward.

I think that is an argument in favor of `return publish_id`. I hope we're not bikeshedding here :smile:, but @nathanegillett raises an important point. Wrapping the publish_id in a response object overcomplicates the function. When creating a foundation to build upon, we should opt for the simplest solution; if we don't have a specific use case or clear path forward for the more complicated option, why use it when a simpler option will suffice at this stage? If, in the future, we find that that the publish_id must be wrapped in a response object, we can make that change later.

2020-09-09 14:48 UTC, lioramilbaum commented on exodus_gw/publish.py
> +    return {
We are defiantly bikeshedding and over-engineering here. I will do the change only because it potentially unblocks the approval process.

2020-09-09 17:03 UTC, nathanegillett approved these changes

2020-09-09 21:03 UTC, crungehottman approved these changes

2020-09-10 01:23 UTC, rohanpm commented on exodus_gw/publish.py
> +    return {
I think the PR is structured in a way which encouraged bikeshedding because there is a bunch of code which produces values, returns them to nowhere and is not actually usable in any way.  It was and still is kind of unclear what the point is here as we have a function which has no useful side effect and whose return value is not used in any way.

Why even add the function now?  It obviously doesn't "work", so you must expect it to be evaluated by some criteria other than "does it work", but I don't think it is obvious to reviewers what that criteria should have been (certainly wasn't clear to me anyway).

I also just want this PR to be done with, but for later PRs, would it be possible to have some clearly defined scope (like "this fully implements X, while Y and Z are just placeholders", or just defining endpoint URLs and parameters while leaving implementation completely blank).  Or else could you next time provide some guidance on how reviewers should do their review?

2020-09-10 01:24 UTC, rohanpm approved these changes

2020-09-10 01:24 UTC, merged