Allow upload of empty files [RHELDST-4728]
release-engineering/exodus-gw pull request #153
Opened 2021-01-26 20:07 UTC by nathanegillett

No Content-MD5 header is added to upload requests for files which have
no content. This caused a key error in our code, so a static value was
added for empty files, matching that which would be generated.

2021-01-26 20:12 UTC, crungehottman approved these changes

2021-01-26 21:54 UTC, rohanpm commented on exodus_gw/routers/s3.py
> +            ContentMD5=request.headers.get("Content-MD5", empty_content_md5),
Could we please use the default value only when there's no data?  (e.g. Content-Length == 0 ?)

Setting a static default checksum whenever the client doesn't provide any seems odd, I'd expect it to be a source of confusing error messages at least, e.g. the client getting an error back suggesting that there's a checksum mismatch when it never sent any checksum.

2021-01-27 01:32 UTC, rohanpm requested changes

2021-01-27 01:32 UTC, rohanpm commented on exodus_gw/aws/util.py
> +        assert "Content-MD5" not in request.headers
I don't think we should assert this.  Can we just delete this line?

It may be the case that boto always omits Content-MD5 if Content-Length is zero, but that seems to be an implementation detail which isn't required by the S3 or exodus-gw APIs and we shouldn't make the API crash unnecessarily if a client behaves differently.  It'd be completely legal for a client to send both Content-Length: 0 and the valid Content-MD5 header themselves and if they do that I don't see any reason we should crash.

Note this API isn't expected to be used exclusively via boto, e.g. exodus-rsync would probably use the "AWS SDK for Go" which is a different codebase and might have different behavior for when it does or doesn't send the header.

2021-01-27 03:18 UTC, dichen16 approved these changes

2021-01-27 03:44 UTC, rohanpm approved these changes

2021-01-27 14:02 UTC, crungehottman approved these changes

2021-01-27 14:29 UTC, merged