Support S3 head_object operation [RHELDST-4705]
release-engineering/exodus-gw pull request #156
Opened 2021-01-27 17:43 UTC by nathanegillett

Introduces a new upload endpoint using the HEAD operation which
retrieves metadata from an S3 object.

2021-01-27 17:44 UTC, nathanegillett commented on exodus_gw/routers/s3.py
> +    tags=["head"],
Wasn't quite sure whether this should be "upload" or "head".

2021-01-27 17:47 UTC, nathanegillett commented on exodus_gw/routers/s3.py
> +    )
Wondering if we should only preserve certain headers or all of them. If the latter, we should adopt this method in other endpoints.

2021-01-27 22:57 UTC, rohanpm requested changes

2021-01-27 22:57 UTC, rohanpm commented on exodus_gw/routers/s3.py
> +    """Retreive metadata from an S3 object."""
```suggestion
    """Retrieve metadata from an S3 object."""
```

2021-01-27 22:57 UTC, rohanpm commented on exodus_gw/routers/s3.py
> +    tags=["head"],
URL looks right to me.  We've set things up so that "<exodus_gw_root>/upload" can be used as the S3 endpoint, this should work correctly with the URL here.

I think the tag should be "upload" though - I would still consider this endpoint a part of the "upload API" even if it's not actually doing any uploading, as you would generally be using it in combination with other upload APIs.  e.g. for comparison, an endpoint in the publish API which just gets you the state of a publish object would still be a "publish API" even if it doesn't actually do any publishing during the request.

2021-01-27 22:57 UTC, rohanpm commented on exodus_gw/routers/s3.py
> +    )
Yeah, I think we should only return a subset.  The other endpoints currently aren't returning all the headers.

It's good to be defensive here.  I guess we don't have a good understanding of what all the headers are, what info they expose and why somebody might want to use them.  If we return them all, there are risks such as: a client of exodus-gw starts building logic on top of some of the headers without our knowledge, thus getting locked in to some behavior specific to the current storage backend of S3.  In theory it's meant to be an implementation detail which we could replace if we have to.

Personally I think a good balance would be to filter out all the `x-amz-*` headers since these are the ones which are clearly invented for AWS and don't map to any standard HTTP concept.  What do you think?

2021-01-28 05:24 UTC, rohanpm commented on exodus_gw/routers/s3.py
> +    )
Forgot to mention that our docs already say we're omitting `x-amz-*`.  I believe I wrote that anticipating that's what we'd end up doing.

2021-01-28 06:26 UTC, rohanpm commented
It's not in the acceptance criteria of this issue, but you might want to consider updating examples/exodus-sync as well to check that this really works.

The idea is that the call to `object.load()` in that example should now be able to work so that we can skip uploading anything which is already present.

2021-01-28 13:36 UTC, nathanegillett commented on exodus_gw/routers/s3.py
> +    tags=["head"],
Thanks. Yeah, it was the tag that I was questioning.

2021-01-28 13:37 UTC, nathanegillett commented on exodus_gw/routers/s3.py
> +    """Retreive metadata from an S3 object."""
Thanks

2021-01-28 13:37 UTC, nathanegillett commented on exodus_gw/routers/s3.py
> +    )
Sounds good to me.

2021-01-28 16:16 UTC, nathanegillett commented
@rohanpm 
> The idea is that the call to `object.load()` in that example should now be able to work so that we can skip uploading anything which is already present.

The call to `object.load()` works but because we're reaching through boto, it raises ClientError based on our endpoint response's status code. So, I've had to wrap the call in another try/except. If the script were calling our code directly or using curl (like `publish_items` does), this wouldn't be an issue.

2021-01-28 21:48 UTC, rohanpm commented on examples/exodus-sync
> +        # Since the outermost layer used here is boto and our head
The commentary here is a bit confusing to me:

All endpoints return status codes.  Is it suggesting there's some difference in handling of status codes between the implementation of our endpoint and the equivalent in S3 which changes the behavior of `object.load()` on a nonexistent object?  If so we should fix it.

2021-01-28 23:05 UTC, nathanegillett commented on examples/exodus-sync
> +        # Since the outermost layer used here is boto and our head
The non-2xx status code returned by our head endpoint seems to be raised by object.load().
So, when a `ClientError(404)` is caught in `head()` it returns `Response(status_code=404)`, then, it seems, `object.load()` receives that `Response` object and raises `ClientError(404)` again due to the `status_code` it contains.

Does that make sense?

2021-01-28 23:10 UTC, nathanegillett commented on examples/exodus-sync
> +        # Since the outermost layer used here is boto and our head
I've updated the comment. Hopefully it's at least a little clearer.

2021-01-28 23:51 UTC, rohanpm approved these changes

2021-01-28 23:51 UTC, rohanpm commented on examples/exodus-sync
> +        # The object.load() call reraises status code ClientErrors
I don't want to hold up a PR on this, but I still think this comment is potentially misleading.

It's accurate to say that "If the object doesn't exist, object.load() will raise a ClientError".

Going further and referring to this as "re-raising" a ClientError which was caught by the server seems confusing to me.  One, it's not re-raising in the Python sense - it's creating an entirely new exception.  Two, the fact that the server itself might have caught a ClientError within its own code is entirely incidental.  Yes,in this example both the client and server happen to use boto library and so they both will see an exception of the same type when dealing with a nonexistent object.  But the fact that the server also happens to use boto should be irrelevant to the client.

Another way to think of it - imagine that the server wasn't using boto library to access S3, but a separate FooLibrary which raised a different kind of exception, maybe an ObjectNotFound exception.  The behavior from the server's endpoint would still be the same (returns a 404 response if object doesn't exist).

Then in the boto-using example, would you say "we need to catch a ClientError here because our head endpoint catches FooLibrary ObjectNotFound exceptions and returns an error" ?  It'd be pretty strange for a client to worry about this implementation detail of the server, wouldn't it?  It should only care about the HTTP response and not about whatever exceptions the server was handling internally while preparing that response.

So now if that seems strange, if FooLibrary is replaced with boto and ObjectNotFound is replaced with ClientError, does that make it not strange for some reason?  I don't think so - it's still just an implementation detail that the client shouldn't care about.  To me the comment here seems to falsely suggest that the boto used by the client and by the server are "connected" somehow, which they aren't.

2021-01-29 01:40 UTC, nathanegillett commented on examples/exodus-sync
> +        # The object.load() call reraises status code ClientErrors
> the fact that the server itself might have caught a ClientError within its own code is entirely incidental

Thanks for helping clarify. This behavior defied my initial expectations and the troubleshooting process skewed my perception a bit, I think.

> this comment is potentially misleading

I agree

2021-01-29 02:57 UTC, rohanpm approved these changes

2021-01-31 22:30 UTC, merged