Add links to publishes [RHELDST-4706]
release-engineering/exodus-gw pull request #161
Opened 2021-01-29 16:58 UTC by nathanegillett

This commit introduces a links attribute on Publish objects which is
updated upon creation with create_publish. Links are URLs related to
the object, e.g., commit: /{env}/publish/{publish_id}/commit, which
reduces what clients need to know in order to use Publish objects.

2021-01-31 22:29 UTC, rohanpm requested changes

2021-01-31 22:29 UTC, rohanpm commented on exodus_gw/crud.py
> +    db_publish = models.Publish(id=uuid4())
If there are other APIs which can return a publish object, they'll have to include similar logic.  I wonder if there's a way to make it happen automatically.

2021-02-01 20:15 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db_publish = models.Publish(id=uuid4())
After a few days looking into it, I can't come up with any way to do that, unfortunately. The problem is that the Publish's attributes can't be used within the class because they aren't defined until construction.
LMK if you have any ideas. I feel I've exhausted every possibility within sqlalchemy.

I've also realized that the code here still won't make the links visible in the publish response -- it's just a property of the Python object currently. Submitted a change to the PR for that.

2021-02-01 21:28 UTC, rohanpm requested changes

2021-02-01 21:28 UTC, rohanpm commented on examples/exodus-sync
> +    links = json.loads(publish["links"])
This looks broken, as 'publish' is already a dict parsed from JSON - so this only makes sense if we define links as "JSON within JSON".  We shouldn't do that.

2021-02-01 21:28 UTC, rohanpm commented on exodus_gw/models.py
> +    links = Column(JSON, nullable=False)
Two points here:

1. I don't think we should store links in the DB since it should be easy to calculate them.
2. However you do need to know the 'env' in order to calculate links.  So this probably points that we should be storing env on publish objects.

In fact it seems like we really ought to be storing env on publish objects regardless, right?  Because otherwise you can create a publish object for one env, and then ask to commit it for another, and the system can't tell that this has happened?

2021-02-01 22:36 UTC, nathanegillett commented on exodus_gw/models.py
> +    links = Column(JSON, nullable=False)
1) If links aren't stored in DB they won't be included in the response, which was the acceptance criteria here.

2) Latest change enforces env.

2021-02-01 22:37 UTC, nathanegillett commented on examples/exodus-sync
> +    links = json.loads(publish["links"])
The links column requires a JSON string, it can't take a dict, afaIk. So the links JSON string needs to be loaded here.

2021-02-01 22:38 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db_publish = models.Publish(id=uuid4())
I managed to get this handled automatically within Publish, only requiring env be stored (which I see is recommended anyway).

2021-02-01 22:52 UTC, nathanegillett commented on examples/exodus-sync
> +    links = json.loads(publish["links"])
E.g.;
`Created publish {'id': '2b733145-d28f-4dcf-85f5-af02ecdf2e89', 'env': 'test', 'links': '{"self": "/test/publish/2b733145-d28f-4dcf-85f5-af02ecdf2e89", "commit": "/test/publish/2b733145-d28f-4dcf-85f5-af02ecdf2e89/commit"}', 'items': []}`
^ That's the parsed `Response`, which contains the links JSON string.

2021-02-01 23:04 UTC, rohanpm commented on exodus_gw/models.py
> +    links = Column(JSON, nullable=False)
About not including links in the response if not added here:

These classes define our DB models.  It can't be the case that something *must* be included in the DB in order to be returned by the API.  If it is then we have a problem that we have to solve.

2021-02-01 23:13 UTC, rohanpm requested changes

2021-02-01 23:13 UTC, rohanpm commented on examples/exodus-sync
> +    links = json.loads(publish["links"])
Yeah, I'm saying this response format doesn't make sense from the client's point of view and we shouldn't implement it this way.

The reasoning "it's stored in DB as JSON so it must be returned here as JSON" isn't valid - APIs aren't supposed to be just a raw dump of whatever's in the DB.  We need to find a way to return this as a proper dict.

I don't know exactly what that would look like, but I'm pretty sure 'links' should not exist on the models object at all, only on the schema object.  FastAPI is converting models objects to schema objects 'somehow', we'll have to learn a bit more about how that works.

2021-02-02 01:00 UTC, nathanegillett commented on examples/exodus-sync
> +    links = json.loads(publish["links"])
> I'm pretty sure 'links' should not exist on the models object at all, only on the schema object.

Ah, yeah, that makes a lot of sense. I hadn't considered working this out on the schema side. I'll give that a shot.

2021-02-02 17:43 UTC, nathanegillett commented
Logic responsible for generating links now exists on the schema object. Commit message updated.

2021-02-02 21:53 UTC, rohanpm approved these changes

2021-02-02 21:53 UTC, rohanpm commented on exodus_gw/schemas.py
> +    def make_links(cls, values):
Cool.  Just wondering did you find any pydantic docs or similar pointing at this solution? (use a validator to generate additional values on model creation).

Seems like a pretty good approach to me, but I couldn't find anything about this when looking at the docs the other day.

2021-02-02 22:16 UTC, nathanegillett commented on exodus_gw/schemas.py
> +    def make_links(cls, values):
I came across this SO thread: https://stackoverflow.com/a/65128634
The pydantic doc regarding this is here: https://pydantic-docs.helpmanual.io/usage/validators/
However, the SO thread illustrates the idea much better, imo.

2021-02-04 00:22 UTC, rohanpm commented
Hope you don't mind if I go ahead and merge this - I think it would be better to get this landed prior to some refactors & migration stuff I'm working on.

2021-02-04 00:22 UTC, merged

2021-02-04 00:35 UTC, nathanegillett commented
> Hope you don't mind if I go ahead and merge this - I think it would be better to get this landed prior to some refactors & migration stuff I'm working on.

Fine by me. Was just waiting for a 2nd ack.