Add endpoint to poll for task completion [RHELDST-2162]
release-engineering/exodus-gw pull request #184
Opened 2021-02-08 21:50 UTC by nathanegillett

2021-02-08 21:53 UTC, nathanegillett commented
Almost there. Just having some issue with the new task object. The db can't seem to find the "tasks" table when it tries to insert the new task. I can't find anything wrong in the code, however.

2021-02-08 21:58 UTC, rohanpm commented
> The db can't seem to find the "tasks" table when it tries to insert the new task.

You're going to have to make a migration for this, which is a change compared to previously.  Could you try the workflow at https://release-engineering.github.io/exodus-gw/development.html#disabling-migrations-during-development ?

2021-02-09 00:14 UTC, nathanegillett commented
Thanks, @rohanpm, that helped.

```
[...]
Started commit of publish: {'id': '986ae4ef-3fbc-4050-aff7-d1b3ead5159a', 'state': 'NOT_STARTED', 'publish_id': '0bf4fee4-9b88-49eb-879f-9964006d9a8c', 'links': {'poll': '/task/986ae4ef-3fbc-4050-aff7-d1b3ead5159a'}}
Polling for commit completion. . .
Task 986ae4ef-3fbc-4050-aff7-d1b3ead5159a: COMPLETE
```
```
Feb 08 19:10:23 fedora sh[434451]: [2021-02-08 19:10:23,097] [PID 434460] [Thread-2] [dramatiq_pg.broker] [INFO] Consumed 986ae4ef-3fbc-4050-aff7-d1b3ead5159a@default.
Feb 08 19:10:23 fedora sh[434463]: INFO:     127.0.0.1:42194 - "POST /test/publish/0bf4fee4-9b88-49eb-879f-9964006d9a8c/commit HTTP/1.1" 200 OK
Feb 08 19:10:23 fedora sh[434463]: [2021-02-08 19:10:23 -0500] [434463] [INFO] Backing off poll_task_completion(...) for 0.7s ({'detail': 'Task 986ae4ef-3fbc-4050-aff7-d1b3ead5159a: NOT_STARTED'})
Feb 08 19:10:23 fedora sh[434451]: [2021-02-08 19:10:23,435] [PID 434460] [Thread-3] [botocore.credentials] [INFO] Found credentials in shared credentials file: ~/.aws/credentials
Feb 08 19:10:23 fedora sh[434463]: [2021-02-08 19:10:23 -0500] [434463] [INFO] Backing off poll_task_completion(...) for 0.4s ({'detail': 'Task 986ae4ef-3fbc-4050-aff7-d1b3ead5159a: IN_PROGRESS'})
Feb 08 19:10:24 fedora sh[434463]: [2021-02-08 19:10:24 -0500] [434463] [INFO] Backing off poll_task_completion(...) for 3.1s ({'detail': 'Task 986ae4ef-3fbc-4050-aff7-d1b3ead5159a: IN_PROGRESS'})
Feb 08 19:10:24 fedora sh[434451]: [2021-02-08 19:10:24,575] [PID 434460] [Thread-3] [botocore.credentials] [INFO] Found credentials in shared credentials file: ~/.aws/credentials
Feb 08 19:10:25 fedora sh[434451]: [2021-02-08 19:10:25,592] [PID 434460] [Thread-3] [botocore.credentials] [INFO] Found credentials in shared credentials file: ~/.aws/credentials
Feb 08 19:10:26 fedora sh[434451]: [2021-02-08 19:10:26,714] [PID 434460] [Thread-3] [botocore.credentials] [INFO] Found credentials in shared credentials file: ~/.aws/credentials
Feb 08 19:10:27 fedora sh[434451]: [2021-02-08 19:10:27,038] [PID 434460] [Thread-3] [exodus-gw] [INFO] Items successfully written
Feb 08 19:10:27 fedora sh[434463]: INFO:     127.0.0.1:42194 - "GET /task/986ae4ef-3fbc-4050-aff7-d1b3ead5159a HTTP/1.1" 200 OK
```
Added the migrations per the guide but do we need all three?.

2021-02-09 01:18 UTC, rohanpm commented on exodus_gw/schemas.py
> +    state: str = Field(..., description="Current state of this task.")
Is there a way to declare this field as some kind of an enum so that all the possible values appear in the docs?  Though it's a string, only certain values would be valid.

2021-02-09 01:18 UTC, rohanpm commented on exodus_gw/schemas.py
> +        values["links"] = {"poll": join("/task", str(values["id"]))}
Per the comments earlier about the concept of the endpoint, I think this should just be "self" and not "poll".

2021-02-09 01:18 UTC, rohanpm commented on exodus_gw/worker/publish.py
> +    update_task_state(
I think we need a check on the task's state here before proceeding.  Keeping in mind that workers are only loosely coupled with the web component via the DB and also that messages can be delayed or interrupted at any point and retried, there's some edge cases which could happen here or could be introduced later:

- task object might not exist at all by the time the message is received
- task might have previously been COMPLETED (and then the worker interrupted before it could mark the current message as done)

The desired behavior in those cases would be to avoid dramatiq repeatedly retrying the message which is doomed to failure.  So there should probably be a check of the form here: if task object doesn't exist or is in an unexpected state, log a warning and return.

2021-02-09 01:18 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +    return create_task(db, msg)
There's a problem here with concurrency and retries - if someone calls this API N times then it'll create N tasks for committing the publish, and they'll even be allowed to run at the same time.

We wouldn't want that. Could this please return the existing task object instead in such cases?

2021-02-09 05:06 UTC, rohanpm commented
I'm gonna mention a couple of other things I think will need to be done in this area.  I'm not saying they have to be done in this PR though.  Pointing them out so you have the option of including them now if you want, and they won't be a surprise later:

- both tasks and publish objects should have a created and/or updated timestamp so that our scheduled cleanup job will be able to identify data for cleanup.
- publish objects probably need a 'state' too, similar to task, so that the update_publish_items and commit endpoints know when a publish has been or will be committed.  For example update_publish_items should refuse adding more items if commit has been requested.

2021-02-09 14:20 UTC, nathanegillett commented on exodus_gw/models.py
> +        self.msg = msg.asdict()
Just thought it might be useful to have the info on the model for debugging or something. We don't currently have a need for it, though, so I'll remove it.

2021-02-09 16:23 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
I've moved this code out to the `commit_publish` endpoint where `create_task` was called but the commit call is necessary to execute the addition of the task object to the DB. It's my understanding that any time you add/edit an object, you have to commit it to the db or it's lost at close of scope.

I'm not sure what you mean by `the app is already designed to commit or roll back around each request`. Where is that functionality supposed to be? Anyway, removing `db.commit()` here breaks the endpoint (schema validation fails because there's no task response because the task object doesn't exist in the DB).

2021-02-09 16:32 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
These commits are necessary as well. Without them, the task's state is never actually updated.

I've kept this function too. We _can_ move the code out to the caller but then we're violating D.R.Y., which may worsen if additional updates need to be made in the future, e.g., aborting a task.
```
task = get_task_by_id(db, current_message.message_id)
task.state = "IN_PROGRESS"
db.commit()

[...]

task = get_task_by_id(db, current_message.message_id)
task.state = "COMPLETE"
db.commit()
```

2021-02-09 16:34 UTC, nathanegillett commented on exodus_gw/routers/service.py
> +def poll_task_completion(
We should update the Jira issue, in that case;
```An API which polls for the completion of the commit task exists.```

2021-02-09 16:47 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
You mentioned in another comment that we should add some checks around updating states, adding more reason to keep this function.

2021-02-09 17:56 UTC, nathanegillett commented on exodus_gw/migrations/versions/582852017462_.py
> +def upgrade():
I found that the empty migration versions are from running alembic-autogen without any schema changes.

2021-02-09 18:05 UTC, nathanegillett commented
@rohanpm 
> * both tasks and publish objects should have a created and/or updated timestamp so that our scheduled cleanup job will be able to identify data for cleanup.
> * publish objects probably need a 'state' too, similar to task, so that the update_publish_items and commit endpoints know when a publish has been or will be committed.  For example update_publish_items should refuse adding more items if commit has been requested.

These sound good but I think they deserve their own jira issues.

2021-02-09 20:37 UTC, nathanegillett commented on exodus_gw/crud.py
> +def get_task_by_id(db: Session, task_id: UUID) -> Query:  # pragma: no cover
So, something like the following should work:
```
    msg = mock.MagicMock(message_id=uuid4(), kwargs={"publish_id": uuid4()})
    task = models.Task(msg)

    with TestClient(app) as client:
        db.add(task)
        db.commit()

        r = client.get("/task/%s" % task.id)
```
However, SQLite is complaining that the object was created in a different thread.

2021-02-09 22:07 UTC, rohanpm commented on exodus_gw/crud.py
> +    db.commit()
> I'm not sure what you mean by "the app is already designed to commit or roll back around each request".
Where is that functionality supposed to be?

That's from commit ae34d30b32619d93d1db, if you check the code added there you'll see it will do a 'commit' whenever we're about to deliver a successful response.

> schema validation fails because there's no task response because the task object doesn't exist in the DB

Do you have more details about how it fails?  This doesn't sound right, I don't see why the model => schema conversion which happens when responding would care at all about whether the object has been saved to DB.

2021-02-09 22:27 UTC, rohanpm commented on exodus_gw/crud.py
> +    db.commit()
It's necessary for a commit to happen at some point, but it shouldn't be here.  It should be covered already by the db_session middleware.  If you remove the commit here, what is it that doesn't work?

Commits really don't belong inside these "update one field of an object" kind of functions because it makes it impossible to compose them safely.  A realistic example which will probably come up is something like this:

When we are asked to commit a publish, we'll want to do something like:
- add a Task object to DB.
- update state field on the Publish object so it's no longer possible to add more items.
- send message to dramatiq actor.

We want "all or nothing" semantics here, e.g. if the service is killed while in the middle of the request, it shouldn't be possible that it created the Task object but failed to update the Publish object.

This can be achieved by adding them all to the same transaction - which is what the middleware implements.  If we instead had e.g. create_task does a commit, and update_publish_state does a commit, then you can't set up the code in a way which ensures they either both succeed or both fail.

That's what I mean when I say it's not the job of these functions. Something like update_task_state has no idea if the caller needs to do some other data updates within the same transaction, so it has no idea whether committing now is appropriate.

There's some discussion in sqlalchemy docs around this too, e.g. https://docs.sqlalchemy.org/en/13/orm/session_basics.html.  If you start reading from where it says "don’t do this", the first (bad) example there shows doing a commit() immediately after doing an update() in the same function.  The next two (good) examples show the preferred way, to avoid committing within the functions doing updates and instead allow that to be the responsibility of the caller.

2021-02-09 22:31 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
> Do you have more details about how it fails? This doesn't sound right, I don't see why the model => schema conversion which happens when responding would care at all about whether the object has been saved to DB.

The traceback is not all that helpful but removing the `commit` call from `commit_publish` leads to the following error:
```
Feb 09 17:27:25 fedora sh[539497]: [2021-02-09 17:27:25 -0500] [539497] [ERROR] Exception in ASGI application
Feb 09 17:27:25 fedora sh[539497]: Traceback (most recent call last):
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
Feb 09 17:27:25 fedora sh[539497]:     result = await app(self.scope, self.receive, self.send)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
Feb 09 17:27:25 fedora sh[539497]:     return await self.app(scope, receive, send)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
Feb 09 17:27:25 fedora sh[539497]:     await super().__call__(scope, receive, send)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
Feb 09 17:27:25 fedora sh[539497]:     await self.middleware_stack(scope, receive, send)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
Feb 09 17:27:25 fedora sh[539497]:     raise exc from None
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
Feb 09 17:27:25 fedora sh[539497]:     await self.app(scope, receive, _send)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
Feb 09 17:27:25 fedora sh[539497]:     response = await self.dispatch_func(request, self.call_next)
Feb 09 17:27:25 fedora sh[539497]:   File "./exodus_gw/main.py", line 161, in db_session
Feb 09 17:27:25 fedora sh[539497]:     response = await call_next(request)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
Feb 09 17:27:25 fedora sh[539497]:     task.result()
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
Feb 09 17:27:25 fedora sh[539497]:     await self.app(scope, receive, send)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Feb 09 17:27:25 fedora sh[539497]:     raise exc from None
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
Feb 09 17:27:25 fedora sh[539497]:     await self.app(scope, receive, sender)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
Feb 09 17:27:25 fedora sh[539497]:     await route.handle(scope, receive, send)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
Feb 09 17:27:25 fedora sh[539497]:     await self.app(scope, receive, send)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
Feb 09 17:27:25 fedora sh[539497]:     response = await func(request)
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/fastapi/routing.py", line 209, in app
Feb 09 17:27:25 fedora sh[539497]:     response_data = await serialize_response(
Feb 09 17:27:25 fedora sh[539497]:   File "/home/ngillett/src/exodus-gw/.tox/dev-server/lib/python3.9/site-packages/fastapi/routing.py", line 126, in serialize_response
Feb 09 17:27:25 fedora sh[539497]:     raise ValidationError(errors, field.type_)
Feb 09 17:27:25 fedora sh[539497]: pydantic.error_wrappers.ValidationError: 1 validation error for Task
Feb 09 17:27:25 fedora sh[539497]: response -> state
Feb 09 17:27:25 fedora sh[539497]:   none is not an allowed value (type=type_error.none.not_allowed)
```

2021-02-09 22:40 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
I suppose you're right, though, that translating the task model that's returned by `commit_publish` _shouldn't_ depend on the task database object.

2021-02-09 22:43 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
@rohanpm, I found that this was actually due to there being no default state value in the task model.

2021-02-09 22:48 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
@rohanpm, I believe this is due to the fact that Column model attributes aren't initialized until the object is saved to the database.

2021-02-09 22:53 UTC, rohanpm commented on exodus_gw/crud.py
> +    db.commit()
Yeah, I figured it might be something like that.  In general I think we need to have values being set when the object is created and before it's committed and not rely on the DB generating default values.

I'm not sure if this means e.g. we must explicitly set 'state' when creating the Task object, or if there's some way in sqlalchemy to set it by default when the object is created (and before committed).

2021-02-09 23:00 UTC, rohanpm commented on exodus_gw/crud.py
> +def get_task_by_id(db: Session, task_id: UUID) -> Query:  # pragma: no cover
Could you share that error please?

The above looks like it should work.  The db.add, db.commit don't need to be within the 'with' block but I don't *think* it should be harmful either.

2021-02-09 23:05 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
That makes sense to me. The mechanism we have in place doesn't seem to be working, though. As I mentioned above, If the commit calls are removed, the state is never updated in the database: `get_task` will always show a "NOT_STARTED" state, despite the state being set in the actor and the following `db.add(task)` call.

Worker:
```
[...]
Feb 09 18:01:31 fedora sh[546000]: INFO:     127.0.0.1:37832 - "PUT /test/publish/d051daad-e68e-4c65-8d99-03a5fa82e7db HTTP/1.1" 200 OK
Feb 09 18:01:31 fedora sh[546000]: [2021-02-09 18:01:31 -0500] [546000] [INFO] Enqueued commit for 'd051daad-e68e-4c65-8d99-03a5fa82e7db'
Feb 09 18:01:31 fedora sh[542191]: [2021-02-09 18:01:31,849] [PID 546014] [Thread-2] [dramatiq_pg.broker] [INFO] Consumed 34a3708d-5e75-4297-8b36-f95ff8bc2ee8@default.
Feb 09 18:01:31 fedora sh[546000]: INFO:     127.0.0.1:37832 - "POST /test/publish/d051daad-e68e-4c65-8d99-03a5fa82e7db/commit HTTP/1.1" 200 OK
Feb 09 18:01:31 fedora sh[546000]: INFO:     127.0.0.1:37850 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
Feb 09 18:01:32 fedora sh[542191]: [2021-02-09 18:01:32,161] [PID 546014] [Thread-4] [botocore.credentials] [INFO] Found credentials in shared credentials file: ~/.aws/credentials
Feb 09 18:01:32 fedora sh[546000]: INFO:     127.0.0.1:37868 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
Feb 09 18:01:33 fedora sh[542191]: [2021-02-09 18:01:33,474] [PID 546014] [Thread-4] [botocore.credentials] [INFO] Found credentials in shared credentials file: ~/.aws/credentials
Feb 09 18:01:34 fedora sh[546000]: INFO:     127.0.0.1:38606 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
Feb 09 18:01:34 fedora sh[542191]: [2021-02-09 18:01:34,515] [PID 546014] [Thread-4] [botocore.credentials] [INFO] Found credentials in shared credentials file: ~/.aws/credentials
Feb 09 18:01:35 fedora sh[542191]: [2021-02-09 18:01:35,580] [PID 546014] [Thread-4] [botocore.credentials] [INFO] Found credentials in shared credentials file: ~/.aws/credentials
Feb 09 18:01:35 fedora sh[542191]: [2021-02-09 18:01:35,993] [PID 546014] [Thread-4] [exodus-gw] [INFO] Items successfully written
Feb 09 18:01:36 fedora sh[546000]: INFO:     127.0.0.1:39444 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
Feb 09 18:01:38 fedora sh[546000]: INFO:     127.0.0.1:39448 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
Feb 09 18:01:39 fedora sh[546000]: INFO:     127.0.0.1:39456 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
Feb 09 18:01:59 fedora sh[546000]: INFO:     127.0.0.1:39460 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
Feb 09 18:02:45 fedora sh[546000]: INFO:     127.0.0.1:39466 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
Feb 09 18:03:31 fedora sh[546000]: INFO:     127.0.0.1:39472 - "GET /task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8 HTTP/1.1" 200 OK
```
Client:
```
[...]
Started commit of publish: {'id': '34a3708d-5e75-4297-8b36-f95ff8bc2ee8', 'state': 'NOT_STARTED', 'publish_id': 'd051daad-e68e-4c65-8d99-03a5fa82e7db', 'links': {'self': '/task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8'}}
Polling for commit completion. . .
Task state: NOT_STARTED
Task state: NOT_STARTED
Task state: NOT_STARTED
Task state: NOT_STARTED
Task state: NOT_STARTED
Task state: NOT_STARTED
Task state: NOT_STARTED
Task state: NOT_STARTED
Task state: NOT_STARTED
Publish complete: {'id': '34a3708d-5e75-4297-8b36-f95ff8bc2ee8', 'state': 'NOT_STARTED', 'publish_id': 'd051daad-e68e-4c65-8d99-03a5fa82e7db', 'links': {'self': '/task/34a3708d-5e75-4297-8b36-f95ff8bc2ee8'}}
```

2021-02-09 23:10 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
I'm not sure about the sqlalchemy approach but setting non-nullable values ourselves should be easy enough.

2021-02-09 23:15 UTC, nathanegillett commented on exodus_gw/crud.py
> +def get_task_by_id(db: Session, task_id: UUID) -> Query:  # pragma: no cover
With `db.*` calls inside of the `with`:
```
-------------------------------------- Captured log call --------------------------------------
INFO     exodus-gw:migrate.py:43 Upgrading DB to head
INFO     alembic.runtime.migration:migration.py:163 Context impl SQLiteImpl.
INFO     alembic.runtime.migration:migration.py:166 Will assume non-transactional DDL.
INFO     alembic.runtime.migration:migration.py:555 Running upgrade  -> 0c60e1b25e03, Initial migration
INFO     alembic.runtime.migration:migration.py:555 Running upgrade 0c60e1b25e03 -> cd561983acb2, Add tasks table
ERROR    sqlalchemy.pool.impl.NullPool:base.py:705 Exception during reset or similar
Traceback (most recent call last):
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140170701055552 and this is thread id 140171024049984.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ngillett/src/exodus-gw/exodus_gw/main.py", line 163, in db_session
    request.state.db.commit()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 508, in commit
    t[1].commit()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1762, in commit
    self._do_commit()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140170701055552 and this is thread id 140171024049984.
(Background on this error at: http://sqlalche.me/e/13/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140170701055552 and this is thread id 140171024049984.
ERROR    sqlalchemy.pool.impl.NullPool:base.py:272 Exception closing connection <sqlite3.Connection object at 0x7f7c0857a030>
Traceback (most recent call last):
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140170701055552 and this is thread id 140171024049984.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ngillett/src/exodus-gw/exodus_gw/main.py", line 163, in db_session
    request.state.db.commit()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 508, in commit
    t[1].commit()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1762, in commit
    self._do_commit()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1793, in _do_commit
    self.connection._commit_impl()
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 773, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 771, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 561, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140170701055552 and this is thread id 140171024049984.
(Background on this error at: http://sqlalche.me/e/13/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140170701055552 and this is thread id 140171024049984.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/home/ngillett/src/exodus-gw/.tox/cov/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 564, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140170701055552 and this is thread id 140171024049984.
```
With `db.*` calls outside of the `with`:
```
_______________________________________ [...]

2021-02-09 23:19 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
That worked, @rohanpm. Setting state at Task() construction allows the removal of the `db.commit` call.

2021-02-09 23:28 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
If we move the `update_task_status` code out into the actor, we could get the task just once and set the state as the publish progresses. However, this would mean there are effectively only two states, "NOT_STARTED" and "COMPLETE", since the states wouldn't be committed to the DB until the actor finishes.

2021-02-10 00:12 UTC, rohanpm commented on exodus_gw/crud.py
> +    db.commit()
It'll have to work a bit differently in the actor vs the web endpoints.  The autocommit/rollback stuff in the fastapi middleware won't apply from within the actors.

There's the possibility of implementing something similar in dramatiq to have autocommit/rollback at the end of message processing as well, but I thought about that and figured it doesn't make sense since we expect to have long-running actors, taking several minutes, which probably should expose progress info while they are running. (You're really only supposed to keep transactions open for a few seconds).

I would expect the code to end up something like this:

- most fastapi endpoints don't contain any DB commit or rollback, it happens within the middleware
   - (there's still the option of doing an explicit commit when needed, but it should be very rare that this is needed)
- within any long-running actor, we need some explicit commits added in strategic places.  There are no rules to say exactly when this should happen, but it'd be roughly whenever the actor makes some change to the data which should immediately become visible through the API.  The calls to commit ideally happen within the top-level actor function and not within any utility functions shared with the web component.
   - so for example, if an actor works like: "set task in progress; write items (taking several minutes); set task complete", then indeed it makes sense to have some explicit db.commit just after setting task in progress and then again after setting task to complete.
   - (Actually I've expected that we should save and commit some info about the items we've written as well, e.g. mark items in the DB as committed after each batch, which would allow to resume where we've stopped if we get interrupted - but this is another thing to be saved for a different issue).

2021-02-10 00:19 UTC, rohanpm commented on exodus_gw/crud.py
> +def get_task_by_id(db: Session, task_id: UUID) -> Query:  # pragma: no cover
OK, I understand why moving them outside the 'with' doesn't work at least, it's because the test relies on the app's built-in 'deploy schema on boot' to create all the tables... so the tables just don't exist until the app is created.  I guess that's fine and it makes sense to keep those inside the 'with' statement, or maybe another solution can be found later.

For the thread issue, it sounds like we might be wrongly sharing some db connection object between threads.  I don't think there's anything wrong with how you've written this test, it's probably an existing issue in how the fixture setup works and you're exposing it since you're trying to write the first test which modifies data before invoking the endpoint.

I'm gonna try it locally to learn more about the issue.

2021-02-10 00:49 UTC, rohanpm commented on exodus_gw/crud.py
> +def get_task_by_id(db: Session, task_id: UUID) -> Query:  # pragma: no cover
I tried implementing a test in the similar style for one of the publish APIs, and it works OK, not hitting the thread issue: https://github.com/release-engineering/exodus-gw/pull/187

Can you see any differences between that test and the one you tried to implement which may explain it?

2021-02-10 14:18 UTC, nathanegillett commented on exodus_gw/crud.py
> +def get_task_by_id(db: Session, task_id: UUID) -> Query:  # pragma: no cover
My tests is at https://github.com/release-engineering/exodus-gw/pull/184/files#diff-f40b83876519cbf8de8ef9e6589f228e987632803b77974c283d53b565b91b3fR31.

There don't appear to be any differences. I think the issue might be that my test is asking `get_task` to perform the db query from the app but, as the error states, db operations have to take place within the scope of the TestClient. So, to test this we need to call it directly inside the `with` block, e.g., `service.get_task`.

2021-02-10 14:21 UTC, nathanegillett commented on exodus_gw/crud.py
> +    db.commit()
Okay, so we'll allow explicit commits within actors but keep them away from the web component. I'll rework the actor a bit to accommodate this.

2021-02-10 14:29 UTC, nathanegillett commented on exodus_gw/crud.py
> +def get_task_by_id(db: Session, task_id: UUID) -> Query:  # pragma: no cover
Looks like that link to the test points to the new test now, btw. The previous one looked nearly identical to yours, though.

2021-02-10 22:15 UTC, rohanpm requested changes

2021-02-10 22:15 UTC, rohanpm commented on exodus_gw/routers/service.py
> +    task = db.query(models.Task).filter(models.Task.id == task_id).first()
If there's no match, what happens - does it perhaps give an internal server error (500)?

If so could we please ensure it gives a 404 response instead?  Clients shouldn't be able to trigger internal server errors by passing wrong data.

2021-02-10 22:15 UTC, rohanpm commented on tests/routers/test_service.py
> +        db.commit
This looks wrong as `()` have been omitted, so this isn't actually calling the commit function.  This line doesn't seem to be doing anything.

The reason the test is still able to pass is that you're passing the db session directly into get_task, so it can see all changes whether committed or not.

Currently this test is somewhere in between the two established styles of testing (1. invoke endpoint functions directly with mocks/fakes, or 2. use TestClient to pass a real request through the app, pointing at a real DB, and check the outcome).

Is it possible to push it the rest of the way to style (2) and use the TestClient here to make the request, then check the response?  If that issue with the sqlite thread exception still occurs, let me know and I will pull this and try to debug it.

We haven't talked much about when to use each style of test.  I think the aim should be that each endpoint has at least one test of style (2), because only that style of test covers whether the features integrated with the fastapi router work properly (e.g. Depends, and validations on inputs/outputs).  Then fall back to style (1) only if there are edge cases which are difficult to reach otherwise.  I regret that the first implemented tests used style (1) which caused it to become dominant, as the other style is more effective.

2021-02-11 14:33 UTC, nathanegillett commented on tests/routers/test_service.py
> +        db.commit
I mean, I can go back to "style 2" and let you try to debug it, but the reason I chose this approach is because "style 2" wasn't working due to the aforementioned issue.

2021-02-11 14:42 UTC, nathanegillett commented on exodus_gw/routers/service.py
> +    task = db.query(models.Task).filter(models.Task.id == task_id).first()
Looks like it just returns "null", so I've added an HTTPException here.

2021-02-11 15:06 UTC, nathanegillett commented on tests/routers/test_service.py
> +        db.commit
> E       sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140675778545216 and this is thread id 140676101015360.
E       (Background on this error at: http://sqlalche.me/e/13/f405)

2021-02-11 15:06 UTC, nathanegillett commented on tests/routers/test_service.py
> +        db.commit
https://travis-ci.com/github/release-engineering/exodus-gw/jobs/482233623

2021-02-11 22:09 UTC, rohanpm commented on tests/routers/test_service.py
> +        db.commit
> I think the issue might be that my test is asking `get_task` to perform the db query from the app but, as the error states, db operations have to take place within the scope of the TestClient. So, to test this we need to call it directly inside the `with` block, i.e., `service.get_task`.

This shouldn't be the issue, the scope of the `with` block covers all code indirectly executed as well, not only what's directly executed.

It seems what's happening is just that the sqlite driver has an unnecessary check on the current thread (which e.g. postgres driver doesn't have).  It's meant to protect against coding errors, but it's not designed for a situation like fastapi where you may be mixing async and sync functions safely.  I think the right solution here is to do https://github.com/release-engineering/exodus-gw/pull/190 , do you want to try rebasing/merging with that?

2021-02-11 22:48 UTC, nathanegillett commented on tests/routers/test_service.py
> +        db.commit
I'm in the middle of a dev env publish on another branch atm for the actor time limit investigation.
> Publish item count: 78317

So, can we merge #190 and then I can rebase onto that from here?

2021-02-11 23:04 UTC, nathanegillett commented on tests/routers/test_service.py
> +        db.commit
Maybe I can't rebase here without also merging. I'll just wait for my publish to finish and test the change from #190. If it works, should I just absorb it into this commit?

2021-02-11 23:38 UTC, rohanpm commented on tests/routers/test_service.py
> +        db.commit
#190 is landed, so this could be rebased on top of it now, that would be the cleanest way.

2021-02-11 23:42 UTC, rohanpm approved these changes
I'm marking this approved since the only significant issue remaining was the CI failure, which should disappear now with #190 merged.

It would be preferable to rebase this on latest master now just to be certain that CI really passes on the latest version, but we don't need to bother with another review round for that.

2021-02-11 23:42 UTC, rohanpm commented on exodus_gw/routers/service.py
> +    responses={200: {"description": "Task is complete"}},
Just realized this doc string is wrong as the 200 status doesn't indicate the task is complete.

2021-02-11 23:50 UTC, nathanegillett commented on exodus_gw/routers/service.py
> +    responses={200: {"description": "Task is complete"}},
Good catch. Yeah, that should say something like "task retrieved".

2021-02-12 16:19 UTC, nathanegillett commented
@crungehottman, @lipoja, @dichen16, if there are no objections, I'd like to merge this soon, as it'll help with investigation for 4973.

2021-02-12 16:36 UTC, crungehottman approved these changes

2021-02-12 17:58 UTC, nathanegillett commented on tests/routers/test_service.py
> +    # First request should have succeeded and returned the correct object.
Going to fix this comment prior to merging. The second request is the valid one we're asserting about below.

2021-02-12 23:52 UTC, merged