Publish state
release-engineering/exodus-gw pull request #202
Opened 2021-02-17 18:32 UTC by nathanegillett

this is built on #197, will rebase once it's merged

2021-02-17 18:47 UTC, nathanegillett commented on exodus_gw/models/service.py
> +    state = Column(String, nullable=False)
I've added `nullable=False` back here because migrations knew nothing of its removal, resulting in some testing issues. I think it should be required, anyway. A Task (or Publish) without a state is DOA now that we're checking for them when committing (and/or updating).

2021-02-17 18:55 UTC, nathanegillett commented
@rohanpm, I have no clue as to why the testing db is broken here. Locally, I have one test failing due to a similar issue which I had planned to ask about here but it's now obscured by all of this.
https://travis-ci.com/github/release-engineering/exodus-gw/jobs/483997603

2021-02-17 19:04 UTC, nathanegillett reviewed
@rohanpm, I have no clue as to why the testing db is broken here. Locally, I have one test failing due to a similar issue which I had planned to ask about here but it's now obscured by all of this.
https://travis-ci.com/github/release-engineering/exodus-gw/jobs/483997603

It's complaining about a null value for Publish.state but I don't see where it could be missing.

2021-02-17 22:10 UTC, rohanpm commented
> @rohanpm, I have no clue as to why the testing db is broken here. Locally, I have one test failing due to a similar issue which I had planned to ask about here but it's now obscured by all of this.
> https://travis-ci.com/github/release-engineering/exodus-gw/jobs/483997603
> 
> It's complaining about a null value for Publish.state but I don't see where it could be missing.

For "sqlite3.OperationalError: Cannot add a NOT NULL column with default value NULL", I discovered the same thing on another PR of mine.  If you have a look at exodus_gw/migrations/versions/a60131dd10c4_.py in latest master, the solution is there: you have to adjust your migration to use a 'batch op' and to set recreate='always'.

The background is that sqlite versions older than 3.32.0 have a weird limitation whereby you aren't allowed to add a NOT NULL column with no default value using the ALTER COLUMN statement.  This is despite the fact that there shouldn't be any problem with this if the table is empty, and that there's no problem defining a column in this way when the table is initially created.

batch op and recreate fixes it because this tells sqlalchemy to add the column in a different way, essentially creating an entirely new table and then renaming it over the old one.

The sqlite limitation was removed in 3.32.0, and an up-to-date Fedora env will have a version newer than that so it can't be reproduced locally, but I guess the Travis environment has something older.

2021-02-17 22:54 UTC, nathanegillett commented
> [...] batch op and recreate fixes it [...]

Thanks, @rohanpm.

2021-02-17 23:05 UTC, rohanpm requested changes

2021-02-17 23:05 UTC, rohanpm commented on exodus_gw/worker/publish.py
> +    publish.state = schemas.PublishStates.committing
I think this needs to happen in the web endpoint, commit_publish, not here.  Also with some locking.

If done here there are many scenarios where concurrent requests can mess it up, e.g.:

- commit_publish is invoked N times before this actor manages to set the state to COMMITTING.  With current code that would result in N tasks & calls to the actor being queued.  We want a maximum of 1.
- commit_publish is invoked, then update_publish_items is invoked after this task is enqueued but before it got up to here.  We'd want the update_publish_items to be rejected at that point.

I think the way it ought to work is something like this:

- in commit_publish, when you query for the publish object, that should be a "SELECT ... FOR UPDATE" query.  That can be achieved by adding a 'with_for_update' to the query call.  The point of this is that it both reads the object and obtains a lock on it for the current transaction - so you know nobody else is in the middle of code to update the state.
- set the publish to COMMITTING within the same transaction as sending the commit message to the actor.
- update_publish_items needs to use "SELECT ... FOR UPDATE" as well.  This is how we can guarantee that, for example, we don't have one request starting to commit the publish at exactly the same time as another request is adding more publish items onto it.

2021-02-18 21:55 UTC, rohanpm approved these changes

2021-02-19 23:43 UTC, merged