Add UTC timestamp to publish and task objects [RHELDST-5084]
release-engineering/exodus-gw pull request #208
Opened 2021-02-22 14:13 UTC by nathanegillett

2021-02-22 16:04 UTC, nathanegillett commented
@rohanpm, migration has broken somehow.

> sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop constraint publishes_pkey on table publishes because other objects depend on it
DETAIL:  constraint items_publish_id_fkey on table items depends on index publishes_pkey
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
>
> [SQL: ALTER TABLE publishes DROP CONSTRAINT publishes_pkey]
(Background on this error at: http://sqlalche.me/e/13/2j85)
ERROR: InvocationError for command /home/ngillett/src/exodus-gw/.tox/alembic-autogen/bin/python scripts/alembic-autogen (exited with code 1)

Looks like `meta.drop_all` in `db_reset` from migrate.py is trying to drop the publishes table before the items table without using `CASCADE`.

This problem is present on the master branch as well.
I've tried a few different things, altering `db_reset`, adding cascade options in various places, etc., with no luck.

2021-02-22 22:58 UTC, rohanpm requested changes

2021-02-22 22:58 UTC, rohanpm commented on exodus_gw/models/publish.py
> +from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
Hmm, rather than using this type from postgresql dialect, can we just use the generic DateTime type which can be imported from sqlalchemy module?

From a quick reading of the doc string, the differences are probably something like:

- TIMESTAMP might support fractional seconds
- TIMESTAMP might support storing timezones

I don't think we need either of these, so it'd be preferable to stick with the generic type.  Note: I said something before about handling datetimes as UTC, but this doesn't mean we have to store timezone info in the DB (we would only have to do that if we wanted to store values using multiple different timezones).

2021-02-22 22:58 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +        updated=datetime.now(timezone.utc),
I think it'd be preferable to use exactly the same timestamp here as on the publish object as well, rather than possibly allowing them to be different.

Similar to the comment I made on the other PR about advantages of having "from_date" the same across an entire publish.  Even though either way works, it just makes it a bit easier to identify related data if they've got the same timestamp.

2021-02-22 22:58 UTC, rohanpm commented on exodus_gw/worker/publish.py
> +def update_state(
I guess the intent of this is to help ensure that you won't forget to update timestamps when changing states.

There's another more direct way you might consider looking into.  sqlalchemy has an events system which allows to run bits of code when certain things happen.  If we want to implement e.g. "Whenever a Task is modified, its timestamp is updated" then I believe dropping something like this underneath the 'class Task' may do the trick:

```python
@event.listens_for(Task, 'before_update')
def task_before_update(_mapper, _connection, task):
    task.updated = datetime.utcnow()
```

So you might want to consider it in case it helps remove the need for a helper like this.

2021-02-22 22:58 UTC, rohanpm commented on exodus_gw/worker/publish.py
> +        LOG.error("Unknown action, '%s'", action)
This would be just a bug in our code, it shouldn't be tolerated by returning since it means we can write code passing the wrong value to update_state and it will seem to work.  In a case like this I'd suggest raising an AssertionError, as there is just no legitimate way to get here, if we do then it's most likely a bug in the code the dev is currently working on and it should be detected ASAP rather than ignored.

2021-02-22 22:58 UTC, rohanpm commented on tests/conftest.py
> +def mock_datetime(autouse=True):
To me this is a little too severe to enable as an autouse fixture, as it means every piece of code will always get the same value for the current datetime which is very unrealistic.

The way it is mocked, by patching datetime.datetime, is also very severe as it means even if you explicitly try to create a datetime.datetime of a particular year, month, day etc, you won't get it - instead you'll just get this hardcoded value.  This would apply across every library in use.

What's the goal here, and is there another way we can do it which won't make datetime.datetime behave so oddly across all tests?

2021-02-23 11:36 UTC, nathanegillett commented on exodus_gw/models/publish.py
> +from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
Sure. I just thought it would help anyone looking at these figure them out but I suppose it's not meant for human consumption anyway.

2021-02-23 11:43 UTC, nathanegillett commented on tests/conftest.py
> +def mock_datetime(autouse=True):
Thought it would be convenient to have datetimes in tested code return a static value, so we can assert about it, but we can just mock it as needed instead.

2021-02-23 12:42 UTC, nathanegillett commented on exodus_gw/worker/publish.py
> +def update_state(
This is exactly what I was looking for. Thanks!

2021-02-23 19:26 UTC, crungehottman approved these changes

2021-02-23 22:03 UTC, rohanpm requested changes

2021-02-23 22:03 UTC, rohanpm commented on exodus_gw/migrations/versions/54f2120b9ab6_.py
> +    # clean all publishes and tasks first to avoid crashing on null state
This all looks wrong as the columns have been defined with nullable=True.

Which is it - are they intended to be nullable or not?  If nullable then why would it be needed to delete the current content of the tables and how can the comment about sqlite "NOT NULL column" be correct?

2021-02-23 22:03 UTC, rohanpm commented on tests/test_models.py
> +        t_updated = publish.updated
```suggestion
        t_updated = task.updated
```

2021-02-23 22:27 UTC, nathanegillett commented on exodus_gw/migrations/versions/54f2120b9ab6_.py
> +    # clean all publishes and tasks first to avoid crashing on null state
Seems like emptying the tables wasn't necessary.

2021-02-23 22:50 UTC, rohanpm requested changes

2021-02-23 22:50 UTC, rohanpm commented on exodus_gw/migrations/versions/54f2120b9ab6_.py
> +    # recreate='always' to avoid "Cannot add a NOT NULL column with default value NULL"
This should still be wrong though, it's specifically about "NOT NULL" columns, and the columns being touched here aren't NOT NULL.  Can this be dropped too please and just don't pass a 'recreate' value if we don't have to?

(It might not even be required to use a batch op at all here, but I think it's reasonable to just use them by default anyway to keep all changes to a table grouped.)

2021-02-23 22:56 UTC, nathanegillett commented on exodus_gw/migrations/versions/54f2120b9ab6_.py
> +    # recreate='always' to avoid "Cannot add a NOT NULL column with default value NULL"
Yeah, I just had another, closer look at the error raised by the autogen migration version. The stock upgrade function should be fine but the downgrade function is what needed some attention.

2021-02-23 23:43 UTC, rohanpm approved these changes

2021-02-24 02:08 UTC, merged