Remove from_date Item attribute [RHELDST-4868]
release-engineering/exodus-gw pull request #211
Opened 2021-02-22 21:39 UTC by nathanegillett

This commit removes the from_date attribute from the Item model and
schema so users are unable to set this field themselves, as there is
currently no use-case for them to do so. The from_date attribute is
still required by the DynamoDB table, however, so it is
programmatically set to the datetime at which the item is written.

2021-02-22 22:34 UTC, rohanpm requested changes

2021-02-22 22:34 UTC, rohanpm commented on exodus_gw/aws/dynamodb.py
> +                        "from_date": {"S": datetime.now(timezone.utc)},
I don't think this is the most appropriate place to initialize the value, mainly because it means every item or batch of items within the same publish can have a different from_date.

I think it's quite advantageous to have one from_date used for the entire publish.  Think of the scenario for instance of getting a ticket "hey, this one publish messed up a bunch of stuff, can you manually undo it somehow?"  The request is basically impossible if exodus-gw used a range of from_date values during the publish, but if it used the same value for all items, and that value was logged somewhere, then we have the ability to look up or delete all the items it wrote.

I suggest passing from_date as an argument into the dramatiq actor.  This also has another effect which I think is positive: in the event of a conflict, whichever commit is requested later "wins", even if some writes are delayed due to retries etc.  I think this is easier to reason about than having whichever write succeeds last "wins".

Also, unless I'm missing something, this is going to completely break deletes, since datetime.now at time of delete is not necessarily going to be the same as it was at the time of put.

2021-02-23 17:39 UTC, nathanegillett commented
Based on #208 to avoid migration conflicts. Holding as draft until parent commit is merged.

2021-02-24 03:11 UTC, rohanpm approved these changes

2021-02-24 03:12 UTC, rohanpm commented
Looked right, but it failed CI.  One of the revisions within the alembic migration might be wrong.

2021-02-24 12:56 UTC, nathanegillett commented
> Looked right, but it failed CI. One of the revisions within the alembic migration might be wrong.

Yep. I remade the revision for #208 so the revision from this commit was looking for a non-existent down_revision.
Fixed.

2021-02-24 22:04 UTC, rohanpm approved these changes

2021-02-25 00:33 UTC, rohanpm commented
I want to submit this because otherwise I still need to write "from_date" in some new autotests only to remove it later.

2021-02-25 00:33 UTC, merged