auth: add an endpoint for basic auth diagnosis
release-engineering/exodus-gw pull request #28
Opened 2020-09-10 01:05 UTC by rohanpm

Let's add a trivial endpoint which can be used to determine whether
the current user is authenticated, along with their roles. Without
this, there is no way to verify directly that the authentication
reverse-proxy is working correctly, or for a user to verify that
they were given the roles they requested, etc.

This also gives the healthcheck and whoami endpoints the same
openapi tag, so that they appear in the API docs together (as both
of them are kind of "meta APIs" relating to the service itself
rather than the exodus CDN.)

2020-09-10 04:09 UTC, rohanpm commented
Travis is acting a bit odd today.

2020-09-10 07:33 UTC, lioramilbaum requested changes

2020-09-10 07:33 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +@app.get("/healthcheck", tags=["service"])
This change is unrelated to this PR

2020-09-10 07:33 UTC, lioramilbaum commented on tests/test_gateway.py
> +def test_whoami():
I am not sure if this test covers all options: 
a request without any payload
a request with incorrect payload
a request with correct payload

2020-09-10 07:34 UTC, lioramilbaum commented
Is there an issue this PR can be linked to?

2020-09-10 15:52 UTC, nathanegillett commented on exodus_gw/gateway.py
> +@app.get("/healthcheck", tags=["service"])
Tags could be added in an additional commit, at least.

2020-09-10 15:56 UTC, nathanegillett commented on tests/test_gateway.py
> +def test_whoami():
If I understand `whoami` correctly, there's only one possible response; it just returns whatever context it's given.

2020-09-14 10:28 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +@app.get("/healthcheck", tags=["service"])
The value of the change is unquestionable. Mixing this effort with another effort is the issue here. The value of keeping PRs small and related to the PR subject+linked issue is for future trouble shooting/debugging.

2020-09-14 15:37 UTC, nathanegillett commented on exodus_gw/gateway.py
> +@app.get("/healthcheck", tags=["service"])
> Now in this change I'm adding one more endpoint which seems to belong in the same group, so I've put the same tag on the old endpoint and my new endpoint to group them.

Makes sense to me.

2020-09-14 15:40 UTC, nathanegillett approved these changes

2020-09-14 15:40 UTC, nathanegillett commented
It seems CI is still acting strange.

2020-09-14 22:40 UTC, rohanpm commented on exodus_gw/gateway.py
> +@app.get("/healthcheck", tags=["service"])
> The value of keeping PRs small and related to the PR subject+linked issue is for future trouble shooting/debugging.

I agree with the principle of keeping PRs small and focused, but I don't think we agree on how to apply that principle.  I explained (already in the commit message) how I think this change *is* related to the purpose of the PR.

2020-09-14 22:41 UTC, merged