Implement environment support in upload API [RHELDST-2188]
release-engineering/exodus-gw pull request #37
Opened 2020-09-16 19:57 UTC by nathanegillett

This commit removes the 'bucket' parameter from the s3 upload API,
replacing it with 'env'. The bucket name is now generated to match the
corresponding environment.

The endpoints for the upload API were also updated to conform to the
'/<env>/<task>/...' convention used by the gateway API.

2020-09-17 00:36 UTC, rohanpm requested changes
Basically fine, can we please tweak either the implementation or the docs to keep https://release-engineering.github.io/exodus-gw/api-guide.html#using-boto3-with-the-upload-api working?

2020-09-17 00:36 UTC, rohanpm commented on exodus_gw/s3/api.py
> +    "/{env}/upload/{key}",
Does this break the compatibility with boto library?  If not, I guess at least the docs need updating for the new way of using it.

Here's the example currently of how you can use boto with exodus-gw: https://release-engineering.github.io/exodus-gw/api-guide.html#using-boto3-with-the-upload-api

The thing is that the S3 API always expects a bucket in the URL, so I was kinda expecting we would still have some bucket component in the URL, maybe just the literal value "bucket", and then our docs would say something like "if using exodus-gw via boto, always provide a bucket name of of "bucket" - the true bucket name will be determined via exodus-gw configuration and cannot be influenced by the caller".

As far as I can tell, this change might still be compatible with boto but you might need to do something like:

```
# e.g. if env is "qa"
s3 = boto3.resource('s3',
                    endpoint_url='https://exodus-gw.example.com/qa',
                    # If SSL needs to be configured:
                    verify='/path/to/bundle.pem',
                    config=Config(client_cert=('client.crt', 'client.key')))

# bucket name is always "upload" (to confirm with URL: <endpoint_url>/<bucket_name>/<key>)
bucket = s3.Bucket('upload')
```

It feels a bit weird.  Is one of these two options perhaps better:

- Make the URL /{env}/upload/bucket/{key}.  Then the endpoint_url is /{env}/upload, and the name given to s3.Bucket is always "bucket".
- Or make the URL /upload/{env}/{key}.  Then the endpoint_url is /upload, and the name given to s3.Bucket is the environment you want to use.  Which seems kinda nice, but then we need to consider if we would make other exodus-gw APIs consistent with that, e.g. /publish/{env}/... rather than /{env}/publish/...

2020-09-17 00:36 UTC, rohanpm commented on exodus_gw/s3/util.py
> +def bucket_name(env: str):
Was this intended as the permanent mechanism?  I think it would ideally be something controllable from a config file rather than being locked into this convention.  Of course it would be possible to implement that later.

2020-09-17 00:41 UTC, rohanpm commented on exodus_gw/s3/util.py
> +def bucket_name(env: str):
Thinking about it a bit more, I don't think it should remain like this permanently as there could be differences between the buckets beyond their name.  e.g. the region or credentials.

2020-09-17 07:34 UTC, lioramilbaum commented on exodus_gw/s3/util.py
> +def bucket_name(env: str):
+1. Bucket names should not be hard coded but pulled from the ConfigMap.

2020-09-17 07:44 UTC, lioramilbaum commented on exodus_gw/s3/api.py
> +    "/{env}/upload/{key}",
I am not following. What is the value of keeping consistency with s3 API? exodus-gw should provide a layer on top of the storage we use. Today it is S3, tomorrow it might be something else.

2020-09-17 14:07 UTC, nathanegillett commented on exodus_gw/s3/util.py
> +def bucket_name(env: str):
> Thinking about it a bit more, I don't think it should remain like this permanently as there could be differences between the buckets beyond their name. e.g. the region or credentials.

This is specifically for the name but, sure, it doesn't need to be permanent.

> Bucket names should not be hard coded but pulled from the ConfigMap.

Bucket names aren't currently in the ConfigMap.

> I think it would ideally be something controllable from a config file rather than being locked into this convention.

It doesn't seem we currently use any configuration outside of ConfigMap.
Do we want to add more info there? Environment name, s3 bucket name, DynamoDB table name?

2020-09-17 14:22 UTC, nathanegillett commented on exodus_gw/s3/api.py
> +    "/{env}/upload/{key}",
So, if I understand correctly, the boto3 approach is an alternative to the upload API. However, we would need AWS account credentials to upload directly to the bucket using boto3, which almost no one will have, so we need the upload API to proxy for authentication.
Is that right, @rohanpm?

Of the three options suggested, I think the last is probably the best. While it doesn't seem necessary to change the publish endpoint path, I think consistency would be nice.
Wdyt, @lioramilbaum?

2020-09-17 22:58 UTC, rohanpm commented on exodus_gw/s3/api.py
> +    "/{env}/upload/{key}",
About the upload API being consistent with S3, there are two main points:

1. If we invent our own upload API, we must implement all the client logic ourselves.  If we instead follow an API which already exists, we gain access to a selection of existing client libraries.  But this is only an argument for following *some* existing API and not S3 specifically.
2. Upload is one of the more performance-sensitive parts, and if the exodus-gw API doesn't align with the API of the underlying storage, there's a risk of introducing major bottlenecks  Having the upload API follow the S3 API ensures this isn't a problem - if a certain task would need N requests when dealing with S3 directly, then it also requires only N requests when dealing with exodus-gw.  Also the request bodies can be streamed to S3 immediately without any buffering (e.g. if uploading a 10MB part, exodus-gw starts streaming the first bytes of that to S3 without waiting for the client to finish the entire part.).  It also works without having to store any state within exodus-gw during the upload (which is why the upload API is already fully functional without having a DB).

The storage backend indeed could change in the future, that's a valid concern which I considered while working on it, but if you look at the details of how the API works you'll see that the API being S3-compatible does not imply that the implementation is locked in to S3.  This is also evidenced by other projects like localstack.  Still, I think if the storage backend were to change, we nevertheless might also have to change the upload API due to performance reasons as described in point (2).  It's very challenging to make an API which wraps another API and is both abstracting the implementation perfectly, and also not introducing some performance overhead.

2020-09-17 23:05 UTC, rohanpm commented on exodus_gw/s3/util.py
> +def bucket_name(env: str):
ConfigMap is just how the config is stored within Openshift, it doesn't tell us how the config should be loaded by exodus-gw which I think is more relevant here.

Config which we will need and don't currently have includes:

- the set of environments
- per-environment, the configuration for the boto library when doing uploads to S3; this includes everything which can be configured in boto (e.g. bucket name, credentials)

The ways that exodus-gw could retrieve this config include:

- environment variables, via Settings class
- a settings file
- loaded from DB

In my opinion, introducing a settings file seems to be the right choice here, an ini-style file which supports any of the config items used by boto library, plus a bit more.

If we choose environment variables or a settings file, ConfigMap can be used to store them.

2020-09-18 17:00 UTC, nathanegillett commented on exodus_gw/s3/api.py
> +    "/{env}/upload/{key}",
I've updated the endpoints to /upload/{env}/{key} and reflected the change in the api-guide doc.

2020-09-18 17:02 UTC, nathanegillett commented on exodus_gw/s3/util.py
> +def bucket_name(env: str):
I've added a config file under root, a function to parse it in settings.py, and updated bucket_name function in s3/util.py to draw the name from there.

2020-09-21 00:36 UTC, rohanpm requested changes

2020-09-21 00:36 UTC, rohanpm commented on exodus_gw/s3/util.py
> +    raise ValueError("Environment '%s' not supported" % env)
I think this is just going to result in a 500 error if the caller requests a nonexistent env.

Could we please give a more appropriate status?  404 seems to be the correct value.  We can do that by `raise HTTPException(...)`.

2020-09-21 00:36 UTC, rohanpm commented on exodus_gw/settings.py
> +def exodus_gw_config(file_name: str = "exodus-gw-config.ini"):
A few separate issues here:

1. Can we please name it just "exodus-gw.ini"?  I think the fact that it's a configuration file is already implied by ".ini".

2. This is loading the file from the current working directory only, that's probably not the best idea as we don't strongly control that.  e.g. can you tell without looking what the CWD is when the container is running in openshift?  In my experience, a convenient way to do it which is friendly both to devs and sysadmins is having multiple paths defined, one being relative to the code and one being hardcoded, and using the first existing.  e.g. if we look for `["<dirname(__file__)>/../exodus-gw.ini", "/opt/app/config/exodus-gw.ini"]` and document in our deployment guide that config will be loaded from /opt/app/config/exodus-gw.ini then we have a good way to handle it in both development and production.  By the way, /opt/app/config is fairly arbitrary but is consistent with platform-sidecar.

3. Now the biggest issue is that this doesn't fit with existing get_settings in any way:

- why does this one have exodus_gw in the name while get_settings doesn't?
- why does this one not have get_ prefix while get_settings does?
- why is get_settings cached via lru_cache while this one loads config again at every call?
- what is the difference between "config" and "settings" anyway - if I'm writing code to use one of these, how would I know which one to call?

I think these should probably be integrated into the same object.  From the point of view of code using the settings - there is no reason why settings should be arbitrarily split between a ConfigParser object and a Settings object.  That should ideally be an implementation detail which is wholly encapsulated within settings.py.

How about defining a model for these Environment settings, adding an `environments: List[Environment] = []` onto Settings, and adding a bit of code into `get_settings` to populate that list from the config file?

2020-09-21 00:36 UTC, rohanpm commented on docs/api-guide.rst
We should probably mention this:

```suggestion

    # Bucket name must match one of the environments defined in exodus-gw.ini.
```

2020-09-21 00:36 UTC, rohanpm commented on tests/s3/test_manage_mpu.py
> +        "Bucket": "exodus-cdn-dev",
I don't think it's a good idea for all these tests to depend on the top-level exodus-gw.ini which would also be used by developers if running the service locally.

At least it seems a little dangerous & inconvenient if a dev wants to both run the service with real config locally (e.g. against exodus-cdn-dev) while also working with the test suite.  If you need to tweak settings for your dev server to manually test something, you can break the automated tests.  Also if the tests are exposed to the real details and credentials of target environments, there is increased risk that they might actually modify data in the target environment unexpectedly (as it's only the mocking setup which prevents this, which can be broken).

Could the test suite perhaps use a separate exodus-gw.ini?  The values could be consistent with the current behavior of tests to remove the need for (some of) these updates.

2020-09-21 09:47 UTC, lioramilbaum requested changes

2020-09-21 09:47 UTC, lioramilbaum commented on tests/s3/test_upload.py
> +async def test_upload_invalid_env(mock_s3_client, mock_request_reader):
You might want to consider using fixtures for modularity. It doesn't have to implemented in this PR.
https://docs.pytest.org/en/stable/fixture.html

2020-09-21 09:47 UTC, lioramilbaum commented on tests/s3/test_upload.py
> +    """Uploading to an invalid environment does not delegate to s3."""
Another suggestion which is not a must but might make the code robust and scale-able: Parameterize test functions.
https://docs.pytest.org/en/stable/parametrize.html

2020-09-21 09:47 UTC, lioramilbaum commented on tests/s3/test_manage_mpu.py
> +        "Bucket": "exodus-cdn-dev",
We have a ConfigMap object as a key/value store.  The `exodus-gw-config.ini` file is yet another key/value store. Consolidation of key/value stores into one might be a simpler solution.

2020-09-21 09:47 UTC, lioramilbaum commented on exodus_gw/s3/util.py
> +def bucket_name(env: str):
I am not sure I am following the whole discussion here. But, I do think that all key/value pairs should be tracked in one place.

2020-09-21 15:45 UTC, nathanegillett commented on exodus-gw-config.ini
> +# Configuration for the exodus-gw application
So, this ini file is temporary? I thought you suggested this as the permanent solution.
> Having production-like config promotes misunderstanding how the config is managed.

How will the actual config for these values be handled? Without that this issue is incomplete, as the app won't be pointed to any real buckets.

2020-09-21 15:49 UTC, nathanegillett commented on exodus_gw/s3/api.py
> -# - should support configuration of the target S3 environment rather than using
> When deploying exodus-gw, it's the responsibility of the service owners to deploy ~/.aws/credentials with all profiles they want to use.

What do you mean by "deploy ~/.aws/credentials"? Where would they be deployed? I thought the plan was to store AWS auth in the playbook's secrets.

2020-09-21 17:17 UTC, nathanegillett commented on docs/api-guide.rst
exodus-gw.ini won't have valid environments, though?
> Maybe it can just have some obviously phony environments like "test1", "test2" [...]

2020-09-21 17:19 UTC, nathanegillett commented on tests/s3/test_upload.py
> +        Bucket="exodus-cdn-dev",
This is an assertion by the test so it should be hard-coded as the expected value.

2020-09-21 17:19 UTC, nathanegillett commented on tests/s3/test_upload.py
> +async def test_upload_invalid_env(mock_s3_client, mock_request_reader):
I'm just using the existing infrastructure. If we want to improve that, it should be done in another PR.

2020-09-21 18:21 UTC, nathanegillett commented on tests/s3/test_upload.py
> +    """Uploading to an invalid environment does not delegate to s3."""
I normally would but this test requires a whole new set of assertions.

2020-09-21 19:34 UTC, nathanegillett commented on tests/s3/test_manage_mpu.py
> +        "Bucket": "exodus-cdn-dev",
We can have a separate ini file for tests but that introduces a bit more complexity; it'll probably require a lot of mocking to get tests pointed at the test config.

2020-09-21 22:47 UTC, rohanpm commented on exodus-gw-config.ini
> +# Configuration for the exodus-gw application
No, using an ini file wouldn't be temporary.  It's just that the exodus-gw repo isn't the definitive source for the specific config to be used in the production environment (and stage, qa etc environments).  The config file in this repo could be used for local development and/or for documentation purposes.

> How should the actual config for these values be handled?

The production (and stage, qa etc...) configuration should be deployed by ansible-roles/exodus-gw similar as was done for platform-sidecar.yml.

2020-09-21 22:50 UTC, rohanpm commented on exodus_gw/s3/api.py
> -# - should support configuration of the target S3 environment rather than using
Yes they would be stored in the playbook's secrets and somehow deployed by ansible-roles/exodus-gw.

With respect to that "somehow", the main option which comes to mind is to put a file using the format of ~/.aws/credentials into a Secret and then mount that as a volume.  Other options could include using a Secret to provide environment variables, but I'm not sure if boto supports using environment variables to define multiple profiles.

2020-09-21 22:51 UTC, rohanpm commented on docs/api-guide.rst
The one in this repo, yes.  The "exodus-gw.ini" here doesn't mean the one checked into this repo, it means the one you deploy with the service.

2020-09-21 23:10 UTC, rohanpm commented on tests/s3/test_manage_mpu.py
> +        "Bucket": "exodus-cdn-dev",
> We have a ConfigMap object as a key/value store. The exodus-gw-config.ini file is yet another key/value store. Consolidation of key/value stores into one might be a simpler solution.

I don't think it would be.

With this config file, the entire file is likely to be deployed as one (key=exodus-gw.ini, value=<content of file>) within a ConfigMap.

It would certainly be possible to instead flatten all content of the file into e.g. (key=qa.table, value=exodus-cdn-qa), (key=stage.table, value=exodus-cdn-stage), ...

Then, to make the config usable to exodus-gw, we would either attach the ConfigMap pairs as environment variables (e.g. QA_TABLE=exodus-cdn-qa, STAGE_TABLE=exodus-cdn-stage, ...) or mount them as files (e.g. /config/qa.table contains "exodus-cdn-qa", /config/stage.table contains "exodus-cdn-stage", ...) as in example https://kubernetes.io/docs/concepts/configuration/configmap/ .

To me it's not simpler, it's about the same level of complexity except that some complexity is moved from exodus-gw code into openshift resources, where it's harder to test.  I think deploying the file in a configmap is fine, it seems to be a typical use-case as shown in above example.

2020-09-22 01:05 UTC, rohanpm commented on exodus-gw-config.ini
> +[qa]
I've just realized that these sections ought to have some kind of prefix, e.g. "env.qa" rather than just "qa".

The reason is that we may want to introduce sections not tied to a specific environment later.  `[logging]` would be a realistic example.  In such case, we wouldn't want exodus-gw to behave as though there is an environment named "logging".  Right now, it'd give you an error since "bucket" wouldn't be defined under logging, but ideally it would not even attempt to parse that section as an environment.

2020-09-22 08:45 UTC, lioramilbaum commented on exodus-gw-config.ini
> +# Configuration for the exodus-gw application
This can be enforced if we have a downstream repo which syncs from upstream repo (this one). The downstream repo can track additional changes which are specific to our production deployment.

2020-09-22 08:52 UTC, lioramilbaum commented on exodus_gw/s3/api.py
> -# - should support configuration of the target S3 environment rather than using
What is the need which enforce support of multiple AWS profiles?

2020-09-22 12:07 UTC, lioramilbaum commented on tests/s3/test_manage_mpu.py
> +        "Bucket": "exodus-cdn-dev",
I was thinking of have a one key per ConfigMap, e.g. key=table value=exodus-cdn-qa for a qa environment. The playbook is supposed to populate the right value according to the environment deployed.  The code should be amended to consume the value from the ConfigMap. Using a config file in parallel sounds like an hybrid solution between the Openshift way and what as before Openshift.
I don't know how to answer the statement that the suggested approach is harder to test.  It will become easier as soon as we gain more knowledge/experience with Openshift.

2020-09-22 12:44 UTC, lioramilbaum commented on tests/s3/test_upload.py
> +async def test_upload_invalid_env(mock_s3_client, mock_request_reader):
+1

2020-09-22 12:47 UTC, lioramilbaum commented on tests/s3/test_upload.py
> +    """Uploading to an invalid environment does not delegate to s3."""
+1

2020-09-22 13:35 UTC, nathanegillett commented on exodus-gw-config.ini
> +# Configuration for the exodus-gw application
> The config file in this repo could be used for local development and/or for documentation purposes.
[...]
The production (and stage, qa etc...) configuration should be deployed by ansible-roles/exodus-gw similar as was done for platform-sidecar.yml.

That makes a lot more sense. Thank you.

2020-09-22 15:22 UTC, nathanegillett commented on exodus_gw/s3/api.py
> -# - should support configuration of the target S3 environment rather than using
> in the exodus-gw ini file, under each env, we define an 'aws_profile = xxx'. Then when constructing the client within exodus-gw, we request usage of that profile.

The best we can do here seems to be setting the `AWS_PROFILE` in the s3_client function. There's no profile parameter for `boto3.client` or even `botocore.config.Config`. I considered using the `Config` model instead but it doesn't seem to support key_id, key, and tokens. https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html

2020-09-22 15:52 UTC, nathanegillett commented on exodus-gw-config.ini
> +[qa]
Yeah, that makes sense. I would prefer to use nested sections but that isn't supported by configparser, unfortunately.

2020-09-23 01:05 UTC, rohanpm requested changes

2020-09-23 01:05 UTC, rohanpm commented on exodus_gw/settings.py
> +    environments: List[Environment] = []
Have you checked how this shows up in the generated docs? (Deployment guide documents this Settings class.)

I think we would want it to not appear there if possible, since it doesn't work the same way as the other attribute.

2020-09-23 01:43 UTC, rohanpm commented on tests/s3/test_manage_mpu.py
> +        "Bucket": "exodus-cdn-dev",
> I was thinking of having one key per ConfigMap, e.g. key=table value=exodus-cdn-qa for a qa environment. The playbook is supposed to populate the right value according to the environment deployed.

I don't think that would work, remember one exodus-gw deployment supports multiple target environments, so there's more than one "table".

> I don't know how to answer the statement that the suggested approach is harder to test. It will become easier as soon as we gain more knowledge/experience with Openshift.

I don't see my opinion as related much to the level of experience.  Let me explain my thinking here:

For any settings we deal with, we ultimately want to be able to maintain them and make changes to them in a git repo, as is the convention for configuration management.  Those settings need to be made available to the bits of code in exodus-gw which depend on them.

So, how to get those settings maintained in a git repo connected with the exodus-gw code at runtime?  Well, the options which have been discussed here include:

- store them all directly as keys/values in a ConfigMap.  Our ansible needs changes relating to ConfigMap resource, and changes to ensure the right keys/values are attached to the pod which needs them, at the right place (most likely as env vars).  We need to make similar changes whenever we introduce a new key/value.  Within exodus-gw, the code for loading the settings would be near-trivial, as everything is loaded in the same way, e.g. by looking at os.environ.  So this is more complex and requires more work long-term on the ansible/openshift side, and less complex on the Python side.
- put them in a config file, and deploy that config file in a single key/value in a ConfigMap.  Our ansible needs a change to add one item to our ConfigMap, and connect it to our pod in one place, and there will not be any further changes needed to that structure as new config is added.  Within exodus-gw, the code for loading the config is more complex as the responsibility for somehow translating that flat file into the values needed by the code lives in Python maintained by us.  So this is less complex on the ansible/openshift side and more complex on the Python.

OK, so there is a choice of adding a bit of complexity either to our openshift resources managed by ansible, or in our Python code here.  Which is better?

Well let's compare the development experience between the two.  If you're working on a Python change then you've got:

- ability to write whatever unit tests you need to verify that the config file is parsed in the way you expect
- ability to run the entire test suite for the project in seconds as you iterate on your changes
- a code coverage report
- mature linter/formatter/IDE support, etc.

While if you're working on ansible/openshift changes you've got:

- virtually no ability to write unit tests at all
- no clear answer how to verify correctness of changes.  Note if there is an answer to this which involves running the ansible to deploy somewhere - that's probably going to be 100 times slower or more compared to running pytest.
- generally, less mature tools overall

If you've got to introduce a new setting for exodus-gw, which codebase would you rather work on between those two?  For me it would certainly be Python.

It's clear to me that we have much more effective means to manage complexity in the Python domain than we do in the ansible & openshift domain.  Therefore if there's a choice between increasing the complexity in Python or increasing the complexity in ansible/openshift, it makes more sense to favor the Python approach.

2020-09-23 07:27 UTC, lioramilbaum commented on tests/s3/test_manage_mpu.py
> +        "Bucket": "exodus-cdn-dev",
I appreciate the detailed feedback. You have raised few points which we might want to review.  The current media (GitHub) is ineffective (for me) to handle such a discussion. Will start an email thread for further discussion.

2020-09-23 08:21 UTC, lioramilbaum commented on exodus_gw/s3/api.py
> +        endpoint_url=os.environ.get("EXODUS_GW_S3_ENDPOINT_URL", None),
We can consider storing this key/value in the ConfigMap. This is something to consider in a different PR.

2020-09-23 19:07 UTC, nathanegillett commented on exodus_gw/s3/api.py
> +        os.environ["AWS_PROFILE"] = profile
I'm surprised I failed to look at Session models given my work on chexus
https://github.com/nathanegillett/chexus/blob/eaa0eae66e02af0a2eb9a6b5e1a8c2903c36fd08/chexus/_impl/client/client.py#L62

I can't find docs for aioboto* but for boto3.Session it's `profile_name`.

2020-09-23 21:30 UTC, nathanegillett commented on exodus_gw/settings.py
> +    environments: List[Environment] = []
The only way to ensure this attribute isn't documented is to specify the Settings members we _do_ want documented.
```
.. autoclass:: exodus_gw.settings.Settings()
    :members: call_context_header
```
The autodoc docs suggest flagging the attribute as private will hide it but that proved ineffective.
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html

2020-09-23 21:38 UTC, nathanegillett commented on tests/s3/test_upload.py
> -        yield s3_client
This was duplicated from conftest.py

2020-09-23 21:39 UTC, nathanegillett commented on docs/deployment.rst
> +    :members: call_context_header
This ensures that call_context_header is the only member of Settings documented

2020-09-23 21:53 UTC, rohanpm approved these changes

2020-09-23 21:53 UTC, rohanpm commented on exodus-gw.ini
> +[env.test]
Seems like there is still nothing about exodus-gw.ini in docs, do you intend to add something?  Having it in a later PR would also be fine.

2020-09-23 21:53 UTC, rohanpm commented on exodus_gw/s3/api.py
> +        endpoint_url=os.environ.get("EXODUS_GW_S3_ENDPOINT_URL") or None,
I was curious just now whether this os.environ.get could also be dropped, as maybe this is something which can already be controlled by the "profile".

Unfortunately it looks like maybe not, at least I don't see it in the list of values at https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html .

2020-09-24 14:14 UTC, nathanegillett commented on tests/s3/test_manage_mpu.py
> +        "Bucket": "exodus-cdn-dev",
I'm going to go ahead and resolve this, as the discussion (at least in part) has moved to email.

2020-09-24 14:24 UTC, nathanegillett commented on exodus-gw.ini
> +[env.test]
I did add the following line to the api-guide;
`# Bucket name must match one of the environments defined in exodus-gw.ini`
but I can add some additional info on the ini file under deployment, settings.

2020-09-24 15:07 UTC, nathanegillett commented on exodus_gw/s3/api.py
> +        endpoint_url=os.environ.get("EXODUS_GW_S3_ENDPOINT_URL") or None,
That's okay. It's only intended for testing/development cases anyway, right?

2020-09-28 03:36 UTC, rohanpm approved these changes

2020-09-28 03:36 UTC, rohanpm commented on docs/deployment.rst
> +those resources. Each environment must appear in it's own section with the prefix "env.".
```suggestion
those resources. Each environment must appear in its own section with the prefix "env.".
```

"it's" always means "it is" or "it has" rather than indicating ownership.

2020-09-28 03:36 UTC, rohanpm commented on exodus_gw/s3/api.py
> +        endpoint_url=os.environ.get("EXODUS_GW_S3_ENDPOINT_URL") or None,
Yes, it was originally added so Tom could point this at localstack.  It just would have been nice if the profile could control it instead of having a special case for this thing.

It probably should have been migrated to `Settings` class at some point, but I don't think it should be in scope of this PR.

2020-09-28 13:37 UTC, nathanegillett commented
@crungehottman @lioramilbaum @dichen16, please have a look when you can.

2020-09-28 13:59 UTC, crungehottman approved these changes

2020-09-28 14:06 UTC, merged