Resolve origin aliases before publishing [RHELDST-8582]
release-engineering/exodus-gw pull request #380
Opened 2021-11-11 18:19 UTC by nathanegillett

Because exodus-lambda maps uri aliases before looking them up on the
Exodus CDN, we must do the same when publishing to it. This commit
implements code which do just that while constructing DynamoDB write
requests.

Previously, exodus-gw would publish an item with a web_uri like
"/content/origin/rpms/some/file.iso". If exodus-lambda then receives a
request for "/content/origin/rpms/some/file.iso", it will resolve the
origin alias and futilely look for an item with a web_uri of
"/origin/rpms/some/file.iso".

2021-11-11 18:20 UTC, nathanegillett commented on exodus_gw/aws/util.py
> +def uri_alias(uri, aliases):
This was copy/pasted from exodus-lambda :)

2021-11-11 18:22 UTC, nathanegillett commented on tests/async_utils.py
> +    thread = threading.current_thread()
This sig change was raised as a deprecation warning. Unrelated to the RP but thought I'd sneak it in anyway.

2021-11-11 22:53 UTC, rohanpm requested changes

2021-11-11 22:53 UTC, rohanpm commented on exodus_gw/aws/dynamodb.py
> +        request = create_request(env_obj, list(batch), from_date, delete)
Seems like this is going to query definitions from the DB once per batch.

Should we pull that up instead so it only happens once per publish?  Reasons being:

- reduce the number of queries for performance/cost
- what if the definitions are changed in the middle of a publish?  I think it's preferable to execute the entire publish using one set of definitions, rather than potentially applying different definitions onto different items in the same publish.

2021-11-11 22:53 UTC, rohanpm commented on exodus_gw/aws/dynamodb.py
> +    definitions = query_definitions(env_obj, from_date)
This doesn't seem right; what type do you expect "definitions" to be?

Later code implies it should be a dict.  But query_definitions returns whatever ddb.query returns, and I would expect that to be a list.  I know the query is run with Limit=1, but I would not expect that to change it into returning a dict, I would expect it to return a list with either 0 or 1 elements, so to get a dict you'd have to extract the first element.

Can you please check it?  And if I'm right that this is currently wrong, it would be nice to figure out why tests pass and address that as well.  For example, perhaps MagicMock is being overused, so that definitions.get will work in the tests (since MagicMock would create a 'get' method on demand) even though it would always crash in reality.

We do use mypy, so I wonder if declaring the return type of query_definitions would have helped here.

2021-11-11 22:53 UTC, rohanpm commented on exodus_gw/aws/util.py
> +    return uri
May I suggest adding a DEBUG log if the output is not equal to the input?  It seems difficult otherwise to judge whether aliases are having the intended effect.

2021-11-12 14:37 UTC, nathanegillett commented on exodus_gw/aws/dynamodb.py
> +        request = create_request(env_obj, list(batch), from_date, delete)
Ah, yep, good catch.

2021-11-12 15:19 UTC, nathanegillett commented on exodus_gw/aws/dynamodb.py
> +    definitions = query_definitions(env_obj, from_date)
Right, yeah, it works out to `mock_s3_client.query` returning a mock which just passes.
I'll make it return a realistic structure (with no items) by default that can then be replaced in individual tests as needed.

2021-11-12 16:00 UTC, nathanegillett commented on exodus_gw/aws/dynamodb.py
> +    definitions = query_definitions(env_obj, from_date)
Correcting this revealed quite a bit wrong with the handling of the query result, so thanks for raising this.

2021-11-12 19:29 UTC, crungehottman approved these changes

2021-11-15 04:02 UTC, rohanpm approved these changes

2021-11-15 04:02 UTC, rohanpm commented on tests/conftest.py
> +        client.query.return_value = BASE_QUERY_RESPONSE
Good idea to put this in the autouse fixture so you get a realistic response by default.

2021-11-15 11:22 UTC, merged