Add API for deploying exodus config [RHELDST-7902]
release-engineering/exodus-gw pull request #383
Opened 2021-11-18 22:59 UTC by nathanegillett

The deploy_config API creates a worker task that puts the given config
dictionary to the config_table specified in exodus-gw.ini.

There is no validation performed on the config, though only dictionaries
with str-type keys are accepted. The content of the config is determined
by exodus-config, exodus-gw is only responsible for putting the data into
the config DynamoDB table.

At this time, config is expected to look something like the following;
{
    "listing": {
        "/content/dist/rhel/server": {
            "values": ["8"],
            "var": "releasever",
        },
        "/content/dist/rhel/server/8": {
            "values": ["x86_64"],
            "var": "basearch",
        },
    },
    "origin_alias": [
        {"src": "/content/origin", "dest": "/origin"},
        {"src": "/origin/rpm", "dest": "/origin/rpms"},
    ],
    "releasever_alias": [
        {
            "dest": "/content/dist/rhel8/8.5",
            "src": "/content/dist/rhel8/8",
        },
    ],
    "rhui_alias": [
        {"dest": "/content/dist/rhel8", "src": "/content/dist/rhel8/rhui"},
    ],
    "config_cache_ttl": 0.1,
}

The "config_cache_ttl" key, if present, will trigger a sleep for the
set duration (corresponding value) prior to submitting the put request.
This ensures that any existing caches within tools consuming the config
have expired and we're not updating the config more than is necessary.

2021-11-18 23:46 UTC, rohanpm requested changes

2021-11-18 23:46 UTC, rohanpm commented on exodus_gw/routers/service.py
> +@router.get(
As it's a write operation, it should not be GET.  A POST would be appropriate.

2021-11-18 23:46 UTC, rohanpm commented on exodus_gw/routers/service.py
> +    dependencies=[needs_role("publisher")],
Could we please introduce a new role for this?  I don't think it's right that anyone with rights to publish content will also have rights to change the config.  "config-deployer" would be my first stab at the new role name...

2021-11-18 23:46 UTC, rohanpm commented on exodus_gw/routers/service.py
> +def deploy_config(
Minor - in my opinion 'service.py' isn't really an appropriate module to add this.  That's intended for endpoints relating to exodus-gw service itself, like the healthchecks.  Deploying config seems not to fit.

A new module like 'config.py' might make more sense.

2021-11-18 23:46 UTC, rohanpm commented on exodus_gw/routers/service.py
> +            "rhel_open_dist": [8],
This is not accurate with the latest exodus-config changes.

2021-11-18 23:46 UTC, rohanpm commented on exodus_gw/routers/service.py
> +            "version": "0.0.0",
Not accurate.

2021-11-18 23:46 UTC, rohanpm commented on exodus_gw/routers/service.py
> +
We're going to need a strict validation of 'config' somewhere here before we invoke the actor.

If an invalid config is uploaded here, it can badly break the CDN.  exodus-gw is the last line of defence against that.  I think we have got to be validating this object against a fairly strict schema, e.g. using jsonschema.

2021-11-18 23:46 UTC, rohanpm commented on exodus_gw/worker/deploy_config.py
> +            sleep(ttl)
Two problems with this:

1. The sleep should be *after* we update the config, not before.  The point is that, by the time the task is set to COMPLETE, we want to be sure that the config has taken effect everywhere.  This can be done by updating the config and then waiting for the cache ttl to pass.  Sleeping *before* updating config doesn't seem to achieve anything... the config could be put back into the cache at any point during the sleep.

2. I don't think this should be literally a time.sleep because it ties up the worker, preventing it from doing anything else while this is ongoing.  It needs to be effectively a sleep from the point of view of an exodus-gw caller, but in a way which doesn't block the worker.

Will a dramatiq send_with_options(delay=...) work to do the "sleep"?  Like this:

- deploy method does the DynamoDB update, but leaves task IN_PROGRESS.
- It calls a new actor like this: `set_task_complete.send_with_options(kwargs={'task_id': task.id}, delay=ttl*1000)`
- After 'delay' milliseconds has passed, set_task_complete runs and sets the task to COMPLETE.

2021-11-18 23:46 UTC, rohanpm commented on tests/worker/test_actors.py
> +def test_deploy_invlaid_ttl(mock_batch_write, mock_get_message, db, caplog):
```suggestion
def test_deploy_invalid_ttl(mock_batch_write, mock_get_message, db, caplog):
```

2021-11-18 23:52 UTC, rohanpm commented on exodus_gw/routers/service.py
> +
I see that the PR message points out there's no validation.

If the intent was to add it in a later PR, that's OK.  If the idea was that it's just not the responsibility of this service and that exodus-config library has to get it right, I don't think that's a good idea, as we need to defend against:

- bugs in exodus-config library
- incorrect manually-generated inputs. People may manually prepare the data for these requests sometimes e.g. while trying to resolve a ticket, as happens on occasion for most services, and they'll need a safety net.

It's extremely important that we don't deploy any invalid config here.

2021-11-19 15:26 UTC, nathanegillett commented on exodus_gw/worker/deploy_config.py
> +            sleep(ttl)
That makes far more sense than what I initially thought you were asking for. My fault for not asking.
Thanks for clarifying.

From dramatiq API reference, delay should work exactly as you posit. Will go with that approach.

2021-11-22 23:27 UTC, rohanpm requested changes

2021-11-22 23:27 UTC, rohanpm commented on exodus_gw/routers/deploy.py
> +                            "items": {"type": "string"},
Could we please add minLength: 1 here so we at least reject empty strings?

2021-11-22 23:27 UTC, rohanpm commented on exodus_gw/worker/deploy.py
> +        batch_write(env_obj, request)
Could we please add an INFO log just before this write, and ensure it contains the from_date and task ID?  This will enable us to reliably search for the exodus-gw event which deployed any particular version of exodus-config later.

2021-11-22 23:27 UTC, rohanpm commented on exodus_gw/routers/deploy.py
> +    LOG.info("Enqueued configuration deployment: %s", msg.message_id)
from_date would probably be good here as well.  e.g. if there's mysterious config in the table, it's identified by from_date, so what we'd want to do is search for all exodus-gw logs including that date.

2021-11-22 23:27 UTC, rohanpm commented on exodus_gw/worker/deploy.py
> +        if not isinstance(ttl, (int, float)):
I find this chunk a bit confusing as config_cache_ttl should have already been verified as a number before we get here.  In fact, if it's not a number then we may have just broken CDN as exodus-lambda presumably expects a number, so we shouldn't have deployed it.  Do you have any particular case in mind for this block of code to kick in?

2021-11-22 23:27 UTC, rohanpm commented on exodus_gw/worker/deploy.py
> +    ttl = config.get("config_cache_ttl", 0)
In the associated JIRA we were discussing about the idea of embedding config_cache_ttl in the deployed config, which you've done here, but we were saying it might not work so well on the lambda side.  Did you look into that yet and commit to a specific approach?  It's just that this code in exodus-gw only makes sense if we also change the lambda to start taking this value from exodus-config rather than lambda_config.json, so if you aren't going to do that we should just scrap this and use a Setting instead.

2021-11-22 23:27 UTC, rohanpm commented on tests/routers/test_deploy.py
> +    """Ensure commit_publish delegates to worker correctly and creates task."""
```suggestion
    """Ensure deploy_config delegates to worker correctly and creates task."""
```

2021-11-23 15:46 UTC, nathanegillett commented on exodus_gw/routers/deploy.py
> +PATH_PATTERN = r"^(/[\w-]*([\d]([\.][\d]{1,2})?)?)*$"
Hmm. Yeah, your first example fits the pattern but the second, "/content/dist/rhel/server/7/7Server/$basearch/rhosj/2.0.0/files" doesn't due to `$` and the additional `.0`.

Do we really expect releasever/basearch variables in alias or listing paths? That's something I haven't seen.

Since we're not trusting the incoming config and enforcing a schema here, I thought it important to at least protect against non-absolute paths, i.e., "/some/../../path".

We do need _some_ pattern to support listing's subschema, so we may as well apply it for all paths, but we can loosen the pattern to just take any number of expected characters (i.e., alphanumeric, forward slash, hyphen, underscore, dollar, and period).

Could do something like `r"^((?!/\.+/)(/[\w\$\.\-]+))*$"` which excludes segments like "/../" or multi-slashes, "//", but otherwise permits segments composed of alphanumeric, `-`, `_`, `$`, `.`, characters, such as "/content/dist/rhel/server/7/7Server/$basearch/rhosj/2.0.0/files".

2021-11-23 15:57 UTC, nathanegillett commented on exodus_gw/routers/deploy.py
> +openapi_tag = {"name": "service", "description": __doc__}
Ahh, thanks.

2021-11-23 23:20 UTC, rohanpm requested changes

2021-11-23 23:20 UTC, rohanpm commented on exodus_gw/routers/deploy.py
> +                            # we can't establish a subschema for them.
Slightly confusing because the "items" is already a subschema.  Do you mean to point out that we don't require any "pattern"?

2021-11-23 23:20 UTC, rohanpm commented on requirements.in
> +importlib-metadata
I'm pretty sure that what's going on here is just different python versions in different envs.  importlib-* are backports of standard python features introduced in the last few versions, so you need to install these separately only if you're using an old enough version of python.  Probably you don't need them if you're using python 3.10 but CI may still need them.

We should probably (separately from this PR) introduce a 'pip-compile' env into tox.ini which specifies exactly which python version is intended to be used during pip-compile, similarly as done in other repos.

2021-11-23 23:20 UTC, rohanpm commented on exodus_gw/worker/deploy.py
> +    task.state = schemas.TaskStates.complete
What happened with the send_with_options and delay approach to set the task complete only after the cache has expired?  Was that removed for a reason?  We still need something like that somewhere.

In case that was removed based on https://github.com/release-engineering/exodus-gw/pull/383#discussion_r754704980 - that wasn't what I was getting at there.  We still need to have some delay to ensure that newly deployed config has taken effect.  That comment was only about where you get the "how long do I need to delay" info from, i.e. can you extract it out of the config object which is being deployed, or do you need to get it from a Setting (which we'll have to keep synchronized with exodus-lambda).  Either way we still need to have a delay.

2021-11-23 23:20 UTC, rohanpm commented on exodus_gw/routers/deploy.py
> +PATH_PATTERN = r"^((?!/\.+/)(/[\w\$\.\-]+))*$"
Thanks, I feel much better about this revised pattern.

2021-11-24 14:29 UTC, nathanegillett commented on exodus_gw/routers/deploy.py
> +                            # we can't establish a subschema for them.
I suppose I meant sub-subschema, then. We can specify a pattern for the string depending on the var used. E.g., if `"var": "releasever"` we know that the value array should contain strings like `"8.1"`.
I gave up on this because often releasever arrays contain basearch or other strings so it didn't seem to achieve anything meaningful.

2021-11-24 14:45 UTC, nathanegillett commented on exodus_gw/routers/deploy.py
> +PATH_PATTERN = r"^((?!/\.+/)(/[\w\$\.\-]+))*$"
Yeah, I like this more as well now.

2021-11-24 14:47 UTC, nathanegillett commented on requirements.in
> +importlib-metadata
That makes a lot of sense and I agree. I'll submit a follow up PR for that which removes these CI deps.

2021-11-24 15:51 UTC, nathanegillett commented on exodus_gw/worker/deploy.py
> +    task.state = schemas.TaskStates.complete
Ah, okay. I'll move the ttl to settings, defaulting to same as exodus-lambda (2 min), and bring back the delayed completion.

2021-11-24 15:51 UTC, nathanegillett commented on exodus_gw/routers/deploy.py
> +                            # we can't establish a subschema for them.
Removed the comment.

2021-11-25 00:28 UTC, rohanpm requested changes

2021-11-25 00:28 UTC, rohanpm commented on exodus_gw/settings.py
> +    Determines the delay (in milliseconds) for deployment task completion to allow for
Above it says minutes, here it says milliseconds.  I think the milliseconds reference should be removed... not sure if this was a mistake or if you wrote this because, internally, we derive a milliseconds-based value using this.  If it's the latter, that would seem to be an irrelevant implementation detail for the person adjusting the settings.

As a side note I dislike the fact that we've got mixed milliseconds, seconds, minutes, hours here in the settings, but if we do something about that we should do it separately and try to fix them all at once...

2021-11-25 00:28 UTC, rohanpm commented on exodus_gw/worker/deploy.py
> +    complete_deploy_config_task.send_with_options(task_id=task.id, delay=ttl)
Does this return a message ID or something that we can log here?  That'd be nice so there's a trail we can follow between this and the delayed actor.

Also, don't you need to db.commit() after this since actors are participating in transactions?

2021-11-25 00:40 UTC, rohanpm commented on exodus_gw/worker/deploy.py
> +    complete_deploy_config_task.send_with_options(task_id=task.id, delay=ttl)
Another question: does this actually work?  I think the way you've called send_with_options is incorrect, doesn't it need to be like this:

`send_with_options(kwargs=dict(task_id=task.id), delay=ttl)`

The way you're calling it now, I believe task_id is going to fall into the `**options` argument which is not going to work.  If I'm right, this also means the tests are too weak as they're passing despite the code being unusable.

2021-11-25 04:18 UTC, rohanpm commented on exodus_gw/worker/deploy.py
> +    complete_deploy_config_task.send_with_options(task_id=task.id, delay=ttl)
After looking into this a bit further I believe the situation is:

- no, you don't need db.commit() because the broker will do that for you, when used outside of an HTTP request.
- task_id has to be put into kwargs as in above example.
- also, task.id can't be sent directly because that's a UUID and sqlalchemy doesn't know how to store that into a JSONB column (to store in DramatiqMessage.body). It's inconsistent with the complete_deploy_config_task implementation too, which is declared as taking a str and not UUID.

Can we please reduce usage of mocks here so these problems are more likely to be caught by tests? I gave it a try in https://github.com/rohanpm/exodus-gw/commit/0b9b18b782663e9946c00f0bca0e9e1bf639629a and at least that last problem can be detected by not using a mock here.

2021-11-29 15:17 UTC, nathanegillett commented on exodus_gw/settings.py
> +    Determines the delay (in milliseconds) for deployment task completion to allow for
Removed the milliseconds reference

2021-11-29 16:00 UTC, nathanegillett commented on exodus_gw/worker/deploy.py
> +    complete_deploy_config_task.send_with_options(task_id=task.id, delay=ttl)
Added a debug message for tracing the task completion actor.

2021-11-30 21:48 UTC, rohanpm requested changes

2021-12-01 17:20 UTC, nathanegillett commented on exodus_gw/routers/deploy.py
> +@router.post(
I've rewritten deploy-config tests to use TestClient, which exposes theses issues, and implemented the necessary fixes.

The dev env doesn't reliably work (never fully completes setup) for me so I'm unable to test without first deploying.

2021-12-02 04:54 UTC, rohanpm commented on exodus_gw/routers/deploy.py
> +@router.post(
If you share some details on the dev env issues I could probably help.

2021-12-02 04:56 UTC, rohanpm approved these changes

2021-12-02 11:32 UTC, merged