Add support for setting item content type [RHELDST-8907]
release-engineering/exodus-gw pull request #400
Opened 2022-01-26 22:03 UTC by negillett

When adding items to a publish, content_type may now be specified.
Content type value must adhere to MIME type structure:
TYPE/SUBTYPE[+SUFFIX][;PARAMETER=VALUE]

2022-01-27 00:04 UTC, rohanpm requested changes

2022-01-27 00:04 UTC, rohanpm commented on exodus_gw/schemas.py
> +        if content_type:
Could you please clarify the relationship between content_type and link_to?

What's supposed to happen in the following case:

- an item has web_uri = /link-src,  link_to = /link-dest, content_type = A
- the item with web_uri /link-dest has content_type = B

If the user requests /link-src, do they get a Content-Type of A or B?

I suspect the correct answer is that it should be B.  In that case we can say that including both content_type and link_to together doesn't make sense, as the content type always comes from the link destination.

If that sounds right then can we please make the validation here reject any mixing of content_type and link_to ?

2022-01-27 00:04 UTC, rohanpm commented on tests/routers/test_publish.py
> +def test_update_publish_items_invalid_content_type(db, auth_header):
I can't find any test which uses a *valid* non-empty content-type.  Can we please have one?

2022-01-27 00:44 UTC, negillett commented on exodus_gw/migrations/versions/48cfe99f5c21_.py
> +    # clean all publishes first to avoid crashing on null state
Yeah, I initially left it out and it passed locally. However, it failed the ci workflow. There should be records of the failed runs.

2022-01-27 00:54 UTC, dichn requested changes
Could you upgrade the example in func `update_publish_items` in `exodus_gw/routers/publish.py` for setting content type support?
```
        example=[
            {
                "web_uri": "/my/awesome/file.iso",
                "object_key": "aec070645fe53ee3b3763059376134f058cc337247c978add178b6ccdfb0019f",
            },
            {
                "web_uri": "/my/slightly-less-awesome/other-file.iso",
                "object_key": "c06545d4e1a1c8e221d47e7d568c035fb32c6b6124881fd0bc17983bd9088ae0",
            },
            {
                "web_uri": "/another/route/to/my/awsome/file.iso",
                "link_to": "/my/awesome/file.iso",
            },

```

2022-01-27 15:34 UTC, negillett commented on exodus_gw/migrations/versions/48cfe99f5c21_.py
> +    # clean all publishes first to avoid crashing on null state
Looks like the downgrade failed. I'll try reverting the upgrade portion.

2022-01-27 15:36 UTC, negillett commented on exodus_gw/schemas.py
> +        if content_type:
Hmm. Yeah, that makes sense to me.

2022-01-28 12:59 UTC, dichn approved these changes

2022-01-28 14:15 UTC, crungehottman approved these changes

2022-01-28 14:47 UTC, merged