Support publish of 'absent' items [RHELDST-9953]
release-engineering/exodus-gw pull request #403
Opened 2022-02-11 08:45 UTC by dichn

In order to support the explicit deletion/hiding of content on exodus
CDN, it should make exodus-gw allow setting the object_key to the string
"absent" on uploaded publish items.

2022-02-11 13:50 UTC, negillett commented on exodus_gw/schemas.py
> +            "(it indicates that content unable to be fetched from the CDN.)"
I think a little more detail would be good here. Something like...
```suggestion
            "piece of content (in lowercase hex-digest form) or the string 'absent'."
            "An 'absent' object_key allows publishing of items not uploaded."
```

2022-02-11 15:11 UTC, crungehottman commented on exodus_gw/schemas.py
> +            "(it indicates that content unable to be fetched from the CDN.)"
Maybe I've misread, but from the Jira tickets in the content deletion epic, it sounds like 'absent' doesn't suggest that the content doesn't exist in the s3 bucket, just that it shouldn't be accessed from some uri. (So, I don't think "allows publishing of items not uploaded" is correct.)

I'd suggest to either remove the explanation for what 'absent' means in the context of exodus-lambda,

```suggestion
            "piece of content (in lowercase hex-digest form) or the string 'absent'."
```
or to maybe fix up the sentence like so:
```suggestion
            "piece of content (in lowercase hex-digest form) or the string 'absent'"
            "(indicates that content shouldn't be fetched from the web_uri)."
```

2022-02-13 22:35 UTC, rohanpm requested changes

2022-02-13 22:35 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +                "web_uri": "/another/route/to/my/awesome/deletion.iso",
The chosen URI here doesn't make sense, it should be confusing to anyone paying attention to the values.

The previous item had a uri of "/another/route/to/..." because it was a link_to file.iso, i.e. file.iso could be accessed by /my/awesome/file.iso or by /another/route/to/... , two ways to get to the same content.

For this item it's not the case, this is not "another route to" anything, because there's no link and a key of "absent" means nothing can be accessed.  I guess this was just copy-pasted from the item above.  Can you please give it a URI which makes more sense for someone reading the docs?

2022-02-13 22:35 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +                "content_type": "application/octet-stream",
I don't think content_type should be provided when object_key is absent.

2022-02-13 22:35 UTC, rohanpm commented on exodus_gw/schemas.py
> +                pass
Could we please add a validation somewhere (could be here) that content_type is not provided if object_key is "absent" ?

2022-02-13 22:35 UTC, rohanpm commented on exodus_gw/schemas.py
> +            "(it indicates that content unable to be fetched from the CDN.)"
I'll pile on with my own suggestion:

> Key of blob to be exposed; should be the SHA256 checksum of a previously uploaded
> piece of content, in lowercase hex-digest form.
> Alternatively, the string 'absent' to indicate that no content shall be exposed at the given URI.
> Publishing an item with key 'absent' can be used to effectively delete formerly published
> content from the point of view of a CDN consumer.

The main points being:

- don't try to cram too much in a single sentence
- I do think the docs should explain *somewhere* why someone might want to do this.  Hence the last sentence.  I'm borderline whether 'schemas' is really the right place for that though.  The prime alternative would be in the doc string of the update_publish_items function, e.g. right after "Publish items primarily are ...", another sentence mentioning something like "Publish items can also hide previously published items by ..."

2022-02-14 00:10 UTC, dichn commented on exodus_gw/schemas.py
> +                pass
Gotcha, plan to update content_type validation like this:
```
        elif object_key:
            pattern = re.compile(r"[0-9a-f]{64}")
            if object_key == "absent":
                if content_type:
                    raise ValueError(
                        "content_type should not be provided if object_key is 'absent'"
                    )
```

2022-02-14 02:37 UTC, dichn commented
(1) object_key description updated
(2) example modified `"web_uri": "/my/awesome/deletion.iso"`
(3) add validation/unittest for absent items with content_type

2022-02-14 04:02 UTC, rohanpm requested changes

2022-02-14 04:34 UTC, dichn commented
(1) `<br>` change to `\n\n`
(2) error message updated

2022-02-14 04:40 UTC, rohanpm approved these changes

2022-02-14 14:55 UTC, crungehottman approved these changes

2022-02-15 00:29 UTC, merged