dev env: create & enforce 'test' aws profile during localstack setup
release-engineering/exodus-gw pull request #410
Opened 2022-02-25 03:16 UTC by rohanpm

It seems that the aws commands used in the localstack-* init scripts
were using the environment's default profile (or the profile set by the
user in AWS_PROFILE).

In a clean environment, that's a problem since no profile will exist;
and even though our docs suggested creating a "test" profile, these
scripts didn't attempt to use that profile, so it wouldn't help unless
the caller explicitly set AWS_PROFILE=test.

Let's make it a bit more robust:

- localstack-init will check for a 'test' aws profile and create it if
  missing.
- localstack-init always attempts to use the 'test' aws profile.

2022-02-25 14:20 UTC, crungehottman approved these changes

2022-02-25 14:29 UTC, negillett requested changes

2022-02-25 14:29 UTC, negillett commented on scripts/localstack-init
> +  fi
We also need to set default output format to "json" here. Otherwise, only "Unknown output type: None" will be returned from `aws` commands.

2022-03-04 16:09 UTC, negillett commented on scripts/localstack-init
> +  fi
I do have output set in my AWS config:
```
$ env | grep AWS
$ 
$ for file in ~/.aws/*; do echo "==== $file"; cat $file; done
==== /home/ngillett/.aws/config
[profile test]
region = us-east-1
output = json
==== /home/ngillett/.aws/credentials
[test]
aws_access_key_id = x
aws_secret_access_key = x
(py3) [ngillett@ngillett exodus-cdn-playbooks]$ aws --version
aws-cli/1.22.61 Python/3.10.2 Linux/5.16.11-200.fc35.x86_64 botocore/1.24.6
```
I can delete the dir, though, and, when reconfiguring, it prompts for an output format which defaults to None.
```
$ rm -rf ~/.aws
$ aws configure --profile test
AWS Access Key ID [None]: x
AWS Secret Access Key [None]: x
Default region name [None]: us-east-1
Default output format [None]: 
```
I see that this is a documented behavior: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-profiles
Though nothing explicitly states, using --profile seems to override the `[default]` profile.

2022-03-04 16:24 UTC, negillett commented on scripts/localstack-init
> +  fi
What interesting is that, when running `aws configure --profile saml` with an existing credentials for said profile, no config file is created (and therefore output format not overridden):
```
$ aws configure --profile saml
AWS Access Key ID [****************TVDQ]: 
AWS Secret Access Key [****************ZE2N]: 
Default region name [us-west-2]: 
Default output format [None]: 
$ aws s3 ls s3://exodus-cdn-prod
2021-12-17 11:26:48     196288 06316538b90d3aab20f4787132307f6d330da9a48bab11a13e0a616fcf622ce5
  [...]
$ for file in ~/.aws/*; do echo "==== $file"; cat $file; done
==== /home/ngillett/.aws/credentials
[test]
aws_access_key_id = x
aws_secret_access_key = x

[saml]
region = us-west-2
aws_access_key_id = REDACTED
aws_secret_access_key = REDACTED
aws_security_token = REDACTED
``` 
The same happens for `[test]`:
```
$ aws configure --profile test
AWS Access Key ID [****************x]: 
AWS Secret Access Key [****************x]: 
Default region name [None]: us-east-1
Default output format [None]:
$
$ for file in ~/.aws/*; do echo "==== $file"; cat $file; done
==== /home/ngillett/.aws/config
[profile test]
region = us-east-1
==== /home/ngillett/.aws/credentials
[...]
```

2022-03-04 16:30 UTC, negillett commented on scripts/localstack-init
> +  fi
And now, for some reason, the output isn't  being set to None by `aws configure`:
```
$ rm -rf ~/.aws
$ aws configure --profile test
AWS Access Key ID [None]: x
AWS Secret Access Key [None]: x
Default region name [None]: us-east-1
Default output format [None]: 
$ for file in ~/.aws/*; do echo "==== $file"; cat $file; done
==== /home/ngillett/.aws/config
[profile test]
region = us-east-1
==== /home/ngillett/.aws/credentials
[test]
aws_access_key_id = x
aws_secret_access_key = x
```
Same versions as before:
```
$ aws --version
aws-cli/1.22.61 Python/3.10.2 Linux/5.16.11-200.fc35.x86_64 botocore/1.24.6
```
So, I guess this _was_ something local, magically fixed by rerunning the command under different conditions... 
We can resolve this, then, and revisit if/when this crops up again.

2022-03-04 16:32 UTC, negillett approved these changes

2022-03-06 22:12 UTC, rohanpm commented on scripts/localstack-init
> +  fi
I see, I note the instruction to run `aws configure` in the guide here was removed though since the idea is that the updated logic here replaces it.

2022-03-06 22:12 UTC, merged