Improve Publish model's resolve_links [RHELDST-11634]
release-engineering/exodus-gw pull request #425
Opened 2022-05-16 19:33 UTC by negillett

Previously this method loaded every item on the publish, storing them in
memory for its duration. The number of these items can realistically
reach into many hundreds of thousands, approaching a million.

This commit refactors the method to use a querying approach to store
only the items that it needs to operate on -- those with non-empty
link_to fields -- and load only the URI and object key of the
corresponding items. These changes should significantly reduce the
impact this method has on system memory.

2022-05-16 22:58 UTC, rohanpm requested changes

2022-05-16 22:58 UTC, rohanpm commented on exodus_gw/models/publish.py
> +            if matches:
This change seems unnecessary.  'matches' can't be None, the worst it can be in the case of no match is an empty dict, but in that case the .get code which is already here should work just fine.  Could we please have this back the way it was?

2022-05-16 22:58 UTC, rohanpm commented on exodus_gw/models/publish.py
> +    def resolve_links(self, db: Session):
It doesn't feel right that the DB session needs to be passed in here.  The object must already be connected to a session, seeing as the other methods for modifying or querying it don't need to have a session passed in (including the older version of resolve_links). This also raises the question, what happens if you pass a session in here which is different from the one originally used to obtain the Publish object?

I went poking around in sqlalchemy and I think this is the right way to get the session already attached to an object, which could allow you to drop 'db' argument here:

```python
from sqlalchemy import inspect

  # ...

  def resolve_links(self):
    # this is the session the object is connected to
    db = inspect(self).session
```

2022-05-17 14:04 UTC, negillett commented on exodus_gw/models/publish.py
> +            if matches:
Agreed. This was an artifact of development, will remove.

2022-05-17 14:05 UTC, negillett commented on exodus_gw/models/publish.py
> +    def resolve_links(self, db: Session):
I had the same feeling but couldn't find a practical solution. I'll give your suggestion a try. Thank you!

2022-05-18 00:04 UTC, rohanpm approved these changes

2022-05-18 13:25 UTC, merged