Fix exodus-gw worker DB errors on startup [RHELDST-11593]
release-engineering/exodus-gw pull request #436
Opened 2022-05-30 09:06 UTC by dichn

Currently, we consider the two exodus components as "web" and "workder".

* the web component is responsible for running DB migrations during the
  initialization of the web app
* the worker component does not run DB migrations, it simply assumes the
  DB is up-to-date.

When booting up worker, the web component initialization can be
unfinished. This patch adds DB check when booting up a worker.

2022-05-30 09:09 UTC, dichn commented
After this patch, the log will be like this:
```
$ journalctl -u exodus-gw-worker.service --user -f
...
May 30 17:08:28 arpeggio sh[337833]: dev-worker run-test: commands[0] | dramatiq --watch exodus_gw exodus_gw.worker -p 1
May 30 17:08:31 arpeggio sh[338175]: [2022-05-30 17:08:31,880] [PID 338175] [MainThread] [dramatiq.MainProcess] [INFO] Dramatiq '1.13.0' is booting up.
May 30 17:08:31 arpeggio sh[338175]: [2022-05-30 17:08:29,951] [PID 338178] [MainThread] [exodus-gw] [INFO] Scheduled actor cleanup uses message f630bd10-14b0-5f04-bda1-5642b9933dae
May 30 17:08:31 arpeggio sh[338175]: [2022-05-30 17:08:29,985] [PID 338178] [MainThread] [backoff] [INFO] Backing off db_table_check(...) for 0.1s (False)
May 30 17:08:31 arpeggio sh[338175]: [2022-05-30 17:08:30,096] [PID 338178] [MainThread] [backoff] [INFO] Backing off db_table_check(...) for 1.7s (False)
May 30 17:08:31 arpeggio sh[338175]: [2022-05-30 17:08:31,877] [PID 338178] [MainThread] [dramatiq.WorkerProcess(0)] [INFO] Worker process is ready for action.
May 30 17:08:31 arpeggio sh[338175]: [2022-05-30 17:08:31,881] [PID 338252] [MainThread] [dramatiq.ForkProcess(0)] [INFO] Fork process 'dramatiq.middleware.prometheus:_run_exposition_server' is ready for action.
May 30 17:08:31 arpeggio sh[338175]: [2022-05-30 17:08:31,890] [PID 338178] [Thread-3] [exodus-gw] [INFO] default.DQ-6c067240-ff98-4a28-b469-182e0ce12128: consumer is running
```

2022-05-30 09:39 UTC, emanuelelevo requested changes

2022-05-30 09:39 UTC, emanuelelevo commented on exodus_gw/dramatiq/middleware/scheduler.py
> +import sqlalchemy
could we have "from sqlalchemy import inspect", rather then importing the entire module?

2022-05-30 09:52 UTC, dichn commented
@emanuelelevo 
re-pushed for using "from sqlalchemy import inspect", instead of importing the entire module.
Re-request review.

2022-05-30 10:04 UTC, emanuelelevo approved these changes

2022-05-30 23:53 UTC, rohanpm requested changes

2022-05-30 23:53 UTC, rohanpm commented on exodus_gw/dramatiq/middleware/scheduler.py
> +        # Check if DB table exists when booting up worker
Small issue: why is the function declared nested here?  It doesn't access 'self' or 'broker'.  Unnecessary nesting of functions/methods tends to lead to unmaintainable code.

Bigger issue: Can you please not add it here (in SchedulerMiddleware)?

A well-designed class should focus on one responsibility.  Now with this change, the concept of "SchedulerMiddleware" class has changed from "Middleware allowing for scheduled actors with cron-style rules", to "Middleware allowing for scheduled actors with cron-style rules, and also waits for DB to become available at startup".  It's not good design, and I think that you only chose to add the code here because you found that an after_process_boot implementation exists here.

Could you please do it without changing behavior of SchedulerMiddleware class?  You could add another middleware, like DatabaseReadyMiddleware, which is dedicated purely to ensuring the DB is ready.

2022-05-31 03:52 UTC, dichn commented
@rohanpm 
Re-pushed for
1) split function: db_table_check() out of after_process_boot(), rather than making it a nested function.
2) Introduce new middleware: DatabaseReadyMiddleware, purely to ensuring the DB is ready.

2022-05-31 03:58 UTC, rohanpm approved these changes

2022-05-31 04:03 UTC, merged