Support "deadlines" for queued tasks [RHELDST-5506]
release-engineering/exodus-gw pull request #450
Opened 2022-07-28 17:01 UTC by negillett

This commit implements support for task deadlines, with a default of 2
hours. Tasks queued for longer than the deadline are abandoned/failed
to avoid potentially overloading systems in the event of a worker
outage.

2022-07-28 22:08 UTC, rohanpm requested changes

2022-07-28 22:08 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +            deadline, "2022-07-25 15:47:47.156005+00:00"
I don't think this works, does it?  strptime expects to have a format string passed, not an example timestamp.

Also, could we please do this in such a way that if the user passes an invalid timestamp, they get a 400 (client error) response rather than a 500 (internal server error) response?

And can we please have at least one test using a TestClient to invoke this endpoint with a deadline set?  This bug ought to have been caught by such a test.

2022-07-28 22:08 UTC, rohanpm commented on exodus_gw/settings.py
> +    """Maximum amount of time (in hours) a task should remain viable."""
I think this should mention that it's a default, as the caller can provide a larger value than this.

2022-07-28 22:08 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +    deadline: str = None,
I'm not sure this is complete, does the new argument appear in the API docs at /redoc with a proper description?  It seems like you would have to add something to make sure it appears in the docs and specifies what the timestamp format is.

2022-07-29 14:30 UTC, negillett commented on exodus_gw/routers/publish.py
> +            deadline, "2022-07-25 15:47:47.156005+00:00"
Ah, yes, I forgot to create a test from that angle. Thanks!

2022-07-29 19:35 UTC, negillett commented on exodus_gw/routers/publish.py
> +    deadline: str = None,
The new argument would appear in the response schema documentation but not the endpoint doc. It took a while but I found fastapi.Query which allows setting an example.

2022-08-01 22:58 UTC, rohanpm requested changes

2022-08-01 22:58 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +        default=None, example="2022-07-25T15:47:47.156005"
Did the format come from anywhere in particular?  I would rather use the same format as pulp if we can, example: `2022-08-01T22:54:21Z`

Differences:
- Z suffix indicates the timezone is UTC (the current example is ambiguous)
- no fractional part of second

The timezone one is the most important.

2022-08-02 13:20 UTC, negillett commented on exodus_gw/routers/publish.py
> +        default=None, example="2022-07-25T15:47:47.156005"
Nope. I think it was just derived from the default datetime stamp. I did have to remove timezone due to Python translation conflicts but hard-coding a Z there is a trivial change. Thanks!

2022-08-02 22:28 UTC, rohanpm approved these changes

2022-08-02 22:47 UTC, merged