Add scripts/alembic-upgrade for DB migration [RHELDST-13374]
release-engineering/exodus-gw pull request #461
Opened 2022-09-06 06:01 UTC by dichn

Because a DB migration can take up to 15 minutes, we decide to decouple
it from the gunicorn initialization.

This commit adds a new script for calling alembic upgrade.

2022-09-06 06:08 UTC, dichn commented
Should I keep the logging module in script `alembic-upgrade`? I think the script will be called in a container, but the script will call the function `db_migrate` which contains many logging.

2022-09-06 06:38 UTC, rohanpm commented
@dichn , I think it would be better for this not to be in `scripts` directory.  We want this to be installed properly into the container image; pip isn't installing anything from the scripts dir.

I believe this should be done as a console_scripts entry point, with the code living somewhere inside of `exodus_gw` directory.  Then it would be installed normally and runnable normally like any pip-installed command. 
 For an example in a current project using pyproject.toml you can look at https://url.corp.redhat.com/436ee8f .

2022-09-06 06:40 UTC, rohanpm requested changes

2022-09-06 06:40 UTC, rohanpm commented on scripts/alembic-upgrade
> +    main(sys.argv[1:])
Have you seen this working?  I'd expect it to crash since you're passing arguments into `main()` but it doesn't accept any arguments.

2022-09-06 06:40 UTC, rohanpm commented on scripts/alembic-upgrade
> +    settings = Settings(
We should probably be using load_settings function, otherwise loggers don't get initialized from the config.  You can load_settings() first and then overwrite the two fields we want to force.

2022-09-08 03:19 UTC, rohanpm commented on setup.py
> +            "exodus_gw_alembic_upgrade = exodus_gw.alembic_upgrade:entry_point"
Generally command-line tools prefer '-' over '_' to separate words (examples: ansible-playbook, ssh-keygen, gpg-agent).    This should be the same, so:

```suggestion
            "exodus-gw-alembic-upgrade = exodus_gw.alembic_upgrade:entry_point"
```

2022-09-08 03:20 UTC, rohanpm commented on tests/test_alembic_upgrade.py
> +    entry_point()
Some kind of check that migrations actually happened would be good... as this test would pass even if the entry_point simply returned without doing anything.

2022-09-08 06:26 UTC, dichn commented on tests/test_alembic_upgrade.py
> +    entry_point()
Added a migration check similar to `test_db_migrate_typical`.

2022-09-08 06:28 UTC, dichn commented on setup.py
> +            "exodus_gw_alembic_upgrade = exodus_gw.alembic_upgrade:entry_point"
console script updated to `exodus-gw-alembic-upgrade`

2022-09-08 22:07 UTC, rohanpm approved these changes

2022-09-08 22:34 UTC, negillett requested changes

2022-09-08 22:34 UTC, negillett commented on tests/test_alembic_upgrade.py
> +def test_entry_point_alembic_upograde(mock_db_engine, unmigrated_db):
```suggestion
def test_entry_point_alembic_upgrade(mock_db_engine, unmigrated_db):
```

2022-09-09 00:35 UTC, dichn commented
Re-pushed for the typo fix.

2022-09-09 01:33 UTC, rohanpm approved these changes

2022-09-09 17:53 UTC, negillett approved these changes

2022-09-10 08:55 UTC, merged