Parallelize batch writes [RHELDST-13451]
release-engineering/exodus-gw pull request #463
Opened 2022-09-15 13:03 UTC by crungehottman

This commit ensures that DynamoDB clients are not unnecessarily created/destroyed repeatedly during the commit. It also ensures that DynamoDB batch writes happen concurrently. The number of threads is configurable in the server settings via "write_max_workers".

2022-09-15 23:09 UTC, rohanpm requested changes

2022-09-15 23:09 UTC, rohanpm commented on exodus_gw/aws/dynamodb.py
> +    with ThreadPoolExecutor(
I think you're not getting as much speedup here as you could be, because there are two levels of batching and you're only addressing one of them.

The other level I'm talking about is in write_publish_items.  In that method write_batches is called in a loop like:

```
        for partition in partitions:
```

...where partition will be of size 5000 by default.

So that means the behavior as of this patch, for a publish with 500,000 items, is that it's still going to do these steps 1,000 times each:

- create/destroy DDB client
- create/destroy thread pool

I think it would ideally be set up so that a single DDB client and thread pool is created and reused for the entire publish, not for each DB partition in the publish.  Put another way, the Commit class should probably own the DDB client and a thread pool.  I'm not sure but this might help meet the originally stated goal, which according to the JIRA is slightly missed right now.

2022-09-21 23:03 UTC, rohanpm submitted a review, later dismissed

2022-09-26 22:47 UTC, crungehottman commented on exodus_gw/worker/publish.py
> +                self.batch_write_wrapper(executor, items)
I have addressed the other two issues in my recent update to this PR, but still can't seem to load multiple partitions without hitting OOM issues. I will have to address this concern in a separate commit so that it is possible to run the `test_exodus_large_publish` test in the meantime (without timing out).

2022-09-26 23:55 UTC, rohanpm approved these changes

2022-09-27 12:46 UTC, merged