Improve use of batch write threads [RHELDST-13926]
release-engineering/exodus-gw pull request #470
Opened 2022-10-11 18:43 UTC by negillett

Previously, when writing items to DynamoDB, a single partition would be loaded and sumbitted to the thread pool executor, blocking until all items in the partition were completed.

This commit allows the number of partitions to be configured, meaning blocking only occurs once all item batches within n number of partitions are submitted to the executor.

Note that items are still only loaded per partition, so there should be no drastic memory usage increase. There is, however, correlation between number of partitions started and memory used due to the futures stored for each batch write but this should not normally be significant.

2022-10-11 18:49 UTC, negillett commented
@rohanpm @crungehottman @dichn @emanuelelevo

2022-10-11 22:51 UTC, rohanpm requested changes

2022-10-11 22:51 UTC, rohanpm commented on exodus_gw/worker/publish.py
> +                for future in as_completed(futures):
I don't think there's been much of an improvement here.   The core issue I complained about in the old code is that there was a part of the loop where we unnecessarily waited for *all* outstanding batches to complete before starting work on any more.  That's still here, it's just been changed from "it blocks at every partition" to "it blocks at every N'th partition" (every 3rd by default).  But I think almost the same effect could have been achieved by just multiplying the partition size by 3.

Another way of saying it - from my original quote in the JIRA referring to the old code:

> If there's 1000 partitions it means there will be 1000 little pauses

Now with this change, if there's 1000 partitions there will be 333 little pauses (at the cost of 3x as many items loaded into memory at once)... so that could be considered an improvement.  But you could achieve the same thing already by just increasing the partition size by 3, which with the existing code would have resulted in 333 partitions and 333 pauses...

The complaint is about the following scenario:

- we've got N threads working on writing batches
- now imagine one batch write operation is slow for whatever reason (maybe it has to retry)
- then at this loop with as_completed, (N-1) threads can complete, and the loop has to wait for the remaining one thread
- it doesn't make sense, why shouldn't we continue onto the next items as quickly as possible instead of leaving most of the threads idle?

The old code had that problem, the new code still has it as well.  It is probably going to need a larger refactoring to fix that.

2022-10-12 13:32 UTC, negillett commented on exodus_gw/worker/publish.py
> +                for future in as_completed(futures):
> at the cost of 3x as many items loaded into memory at once

Well, only the items for a single partition is loaded at one time. So, yeah, it's an improvement but I'll take another step back and see what I can do.

2022-10-12 13:46 UTC, closed without merging