Make exodus-gw resilient against postgres connection drops [RHELDST-13928]
release-engineering/exodus-gw pull request #477
Opened 2022-11-04 18:16 UTC by crungehottman

Exodus-gw now uses the sqlalchemy pool_pre_ping option to detect and recover from a broken DB connection at the beginning of the request. To accommodate for a broken DB connection within the request, exodus-gw wraps select endpoints in a "retry" decorator.

2022-11-04 20:14 UTC, negillett commented on exodus_gw/retry.py
> +            tries = 3
tries should probably be configurable

I'd suggest making it a parameter and providing a setting value in routers/publish.py

2022-11-06 23:14 UTC, rohanpm requested changes

2022-11-06 23:14 UTC, rohanpm commented on exodus_gw/database.py
> +    return create_engine(db_url(settings), pool_pre_ping=True)
It might be better to put this part in a separate pull request.  This should be uncontroversial and low risk, but per my comments on the retry decorator I think the other part of this change needs a lot more work and testing.

2022-11-10 16:03 UTC, negillett approved these changes

2022-11-10 23:07 UTC, rohanpm approved these changes

2022-11-10 23:07 UTC, rohanpm commented on exodus_gw/main.py
> +            response = await call_next(request)
I was thinking of this approach before as well. Just one thing makes me nervous about it: I can't find any info on whether or not it's OK for a middleware to do call_next more than once for a single request.

It's never mentioned anywhere in the Starlette middleware docs as far as I can tell, and no examples do it.  At the same time there are some examples of middleware which *modify* the request, and it seems like those could easily be written in such a way that calling them more than once will break (it would have to be safe to do the modification more than once). This makes me worried that having one middleware call the next more than once could lead to subtle bugs.

However it does seem like the raise-db-and-resolve test you added should be covering this, so it must be generally working.  I guess we should go ahead with this approach, but keep it in mind that if we see any strange behaviors or new bugs related to request handling, this middleware calling the next more than once might be a cause.

2022-11-11 14:52 UTC, merged