Support metadata on S3 uploads [RHELDST-14181]
release-engineering/exodus-gw pull request #483
Opened 2022-11-14 18:07 UTC by negillett

When migrating content in the future, we plan to store information on uploaded objects. This commit allows users to set metadata via headers for fields defined in settings and HEAD requests will now return metadata stored with the object.

2022-11-14 18:22 UTC, negillett commented on exodus_gw/routers/upload.py
> +- All `x-amz-*` headers, other than metadata, are omitted from responses.
Not sure this is true...or where we'd see x-amz-* headers in the context of the AWS Python SDK.

2022-11-14 23:53 UTC, rohanpm requested changes

2022-11-14 23:53 UTC, rohanpm commented on exodus_gw/aws/util.py
> +    valid_meta_fields = load_settings().upload_meta_fields
It doesn't seem like this function should have to load settings.  By the time this function is called, settings have already been loaded and ideally we don't reload them unnecessarily for every request.

Endpoints can obtain a loaded settings object by declaring a parameter like this:

```
settings: Settings = deps.settings
```

2022-11-14 23:53 UTC, rohanpm commented on exodus_gw/routers/upload.py
> +    exodus_migration_md5: Optional[str] = Header(
I don't think it should be done this way because it means you can't support new fields by just adding them into settings.  It seems to fail the point in the AC

> The specific set of metadata fields which can be set, and their valid values, are configurable by the exodus-gw service owners without requiring code changes

Can we please make the full set of supported headers based only on the settings, so that we can change it by changing the settings and not having to come back and revise this code?  Look at *all* headers on the request and extract all headers starting with "x-amz-meta-", then validate them.

2022-11-14 23:53 UTC, rohanpm commented on exodus_gw/routers/upload.py
> +    if "Metadata" in response:
It's not the right way to return it since it's not S3-compatible.

The AC said:

> if the object has any x-amz-meta-* headers returned from S3, those are returned to the client.

It needs to put the metadata into x-amz-meta-* headers in the response, because that's what S3 clients like boto are going to be looking for.  As well as the test you did in RHELDST-14181 comments using http command, you could try a script using boto library as a client of exodus-gw - it would probably show up that whatever you returned here did not make it into the "Metadata" returned by boto, because it's not looking for a header called "Metadata".

Logic here should be something along the lines of:

```
for key, value in response["Metadata"]:
  headers[f"x-amz-meta-{key}"] = value
```

2022-11-14 23:53 UTC, rohanpm commented on exodus_gw/settings.py
> +    upload_meta_fields: Dict[str, str] = {
Could we please make this an empty default?  I think this is a case where it makes more sense for these particular settings to live only in our specific deployment of the service (i.e. maintain them only in ansible).  exodus-gw is going to live "forever" while exodus migration is a one-time thing.  So far, exodus-gw has a general API which does not know anything about the migration process, and it'd be good to keep it that way.

I'm also worried that, if we don't force ourselves to use ansible to adjust these settings, then we won't figure out the correct way to do that and it'll be more complicated than expected if we ever have to adjust them.

2022-11-14 23:53 UTC, rohanpm commented on tests/routers/upload/test_head.py
> +    assert r.headers["Metadata"] == json.dumps(metadata)
This should instead be seeing headers like x-amz-meta-exodus-migration-md5.

2022-11-14 23:53 UTC, rohanpm commented on exodus_gw/routers/upload.py
> +- All `x-amz-*` headers, other than metadata, are omitted from responses.
The boto S3 client doesn't seem to give you direct access to headers.  x-amz-meta-* headers have presumably been parsed into the 'Metadata' field on response objects.

2022-11-15 15:44 UTC, negillett commented on exodus_gw/aws/util.py
> +    valid_meta_fields = load_settings().upload_meta_fields
Ah, yes, thanks.

2022-11-15 17:40 UTC, negillett commented on exodus_gw/routers/upload.py
> +    exodus_migration_md5: Optional[str] = Header(
Ah, okay. I wasn't sure they'd be included in the request object at this point. Thanks.

2022-11-15 22:44 UTC, rohanpm requested changes

2022-11-15 22:44 UTC, rohanpm commented on exodus_gw/routers/upload.py
> +        if not k.startswith("x-amz-meta"):
This check seems suspicious, as surely either (1) all of the metadata keys returned in the response Metadata will include the leading x-amz-meta portion taken from the header (i.e. boto doesn't strip it), or (2) none of them do.  

When I posted a code snippet in the earlier code review, I assumed the situation was (2) since that seems more intuitive to me, but I don't know.

If the situation is (1) then it doesn't seem like rewriting the keys is needed.  (If you've seen that Metadata usually contains x-amz-meta prefix but you're worried about the possibility of it maybe not guaranteed to work that way, it seems more appropriate to warn and filter out unexpected fields, rather than rewriting them.)

If the situation is (2) then this check introduces a really weird behavior: if you store a metadata field which itself starts with x-amz-meta, meaning you would have to send a header like "x-amz-meta-x-amz-meta-foo", it seems to store OK.  But then when you later fetch that object, one level of "x-amz-meta" is stripped from the beginning of the header, so the field name doesn't survive a round-trip.  This would be an unexpected difference between exodus-gw behavior and S3 behavior.

Can you confirm which case is it?  Do the keys here include x-amz-meta prefix or not?

2022-11-15 22:44 UTC, rohanpm commented on exodus_gw/aws/util.py
> +def extract_request_metadata(request: Request, settings: Settings):
Minor: somewhere in this file it would be nice to have a link to the AWS docs mentioning S3 metadata.  To make it clear this is not something we've made up ourselves.

2022-11-16 16:00 UTC, negillett commented on exodus_gw/routers/upload.py
> +        if not k.startswith("x-amz-meta"):
Our metadata headers will have the 'x-amz-meta-' prefix because they have to in order to be picked out as metadata, per util.extract_request_metadata, and I've no reason yet to think boto would strip a substring from those keys. So, the situation should always be (1). I'll replace the key rewrite with a warning about the unexpected  metadata.

2022-11-16 23:39 UTC, rohanpm requested changes

2022-11-16 23:39 UTC, rohanpm commented on exodus_gw/settings.py
> +    Must be prefixed with "x-amz-meta-".
Can we please drop the x-amz-meta- prefix in the doc and examples here?

The metadata *field names* don't contain "x-amz-meta-" prefix.  Only the HTTP headers used to serialize them contain this.  Seeing as clients usually won't have to deal with that detail, and it's redundant to require the same prefix on every key here anyway, it seems more sensible to leave it out.

2022-11-16 23:39 UTC, rohanpm commented on tests/routers/upload/test_head.py
> +                "x-amz-meta-exodus-migration-md5": "^[0-9a-f]{32}$",
Per my other comment on Settings, I don't think the x-amz-meta- prefix should be included here.

2022-11-16 23:39 UTC, rohanpm commented on tests/routers/upload/test_upload.py
I'm surprised it's currently missing in the test, but can we please add at least one assertion that mock_aws_client.put_object was called and that the Metadata argument is correct?

I believe that would have shown up the write-side bug with x-amz-meta-, as it would have shown that the Metadata dict contained e.g. x-amz-meta-exodus-migration-md5 when it should really have contained exodus-migration-md5.

2022-11-17 16:58 UTC, negillett commented on exodus_gw/aws/util.py
> +            metadata[k] = v
Oh, I see. We don't need to keep the prefix because, once uploaded, s3 will prepend it for us. And, when returned by headObject, this prefix is stripped. Perfect. Got it.
This behavior isn't mentioned anywhere in the documentation that I've seen.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html?highlight=put_object#S3.Client.put_object
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html?highlight=put_object#S3.Client.head_object

2022-11-17 21:23 UTC, negillett commented
```
$ http --cert /tmp/rhsm-pulp/cert.pem --cert-key /tmp/rhsm-pulp/key.pem PUT https://exodus-gw-c3i-ngillett-test.apps.ocp-c1.prod.psi.redhat.com/upload/test/5282fe9b67bbe58f639fd1b2446b280a136052f7fad60281dcd7dec5b02bc71e x-amz-meta-exodus-migration-md5:7957cc6e33d7b8277c7e5e324b95503b x-amz-meta-exodus-migration-src:original/source
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Expires: 0
Pragma: no-cache
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1 ; mode=block
content-length: 0
date: Thu, 17 Nov 2022 21:21:49 GMT
etag: "d41d8cd98f00b204e9800998ecf8427e"
server: uvicorn



$  http --cert /tmp/rhsm-pulp/cert.pem --cert-key /tmp/rhsm-pulp/key.pem HEAD https://exodus-gw-c3i-ngillett-test.apps.ocp-c1.prod.psi.redhat.com/upload/test/5282fe9b67bbe58f639fd1b2446b280a136052f7fad60281dcd7dec5b02bc71e
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Expires: 0
Pragma: no-cache
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1 ; mode=block
content-length: 0
date: Thu, 17 Nov 2022 21:21:53 GMT
etag: "d41d8cd98f00b204e9800998ecf8427e"
exodus-migration-md5: 7957cc6e33d7b8277c7e5e324b95503b
exodus-migration-src: original/source
server: uvicorn
```

2022-11-17 22:32 UTC, rohanpm requested changes

2022-11-17 22:32 UTC, rohanpm commented on exodus_gw/aws/util.py
> +            metadata[k.replace("x-amz-meta-", "")] = v
This is slightly incorrect since it will replace *all* instances of x-amz-meta-, not just the leading prefix.  Though it would be very weird to include an x-amz-meta- inside the metadata field name, it would be legal to do so and we shouldn't silently strip it out if so.

It can be fixed to strip just the leading prefix like this:

```suggestion
            metadata[k.replace("x-amz-meta-", "", 1)] = v
```

2022-11-17 22:32 UTC, rohanpm commented on exodus_gw/routers/upload.py
> +    return Response(headers={"ETag": response["ETag"], **response["Metadata"]})
This doesn't seem right:

- we're returning HTTP headers here, so metadata headers should have the `x-amz-meta-` prefix
- but `response["Metadata"]` isn't going to have that

So I guess if there is a metadata field "foo" this is going to wrongly return a header "foo" rather than "x-amz-meta-foo".

I think you need to explicitly add the x-amz-meta- prefix onto each element in response["Metadata"].

2022-11-17 22:32 UTC, rohanpm commented on tests/routers/upload/test_head.py
> +        "exodus-migration-md5": "94e19d5d30b26306167e9e7bae6b28fd",
The expected keys here aren't right, they should have x-amz-meta- prefix.  These are HTTP headers, so the header name is equal to the metadata field name with "x-amz-meta-" prepended.

2022-11-17 22:32 UTC, rohanpm commented on tests/routers/upload/test_upload.py
I wasn't asking to check the return value, I was asking to check whether the correct metadata ever makes it into S3.

In object_put  you added:

```
+        Metadata=metadata,
```

My point is, I believe this is entirely uncovered by the test.  If you deleted that line or if you passed incorrect metadata, I'm pretty sure this test would still pass right now, meaning we are not actually testing whether we ever passed the metadata into S3.

It should be possible to verify that correct Metadata was passed by either looking at 
`mock_aws_client.put_object.mock_calls` or using one of the `mock_aws_client.put_object.assert_called_*` methods.

2022-11-17 22:59 UTC, negillett commented on tests/routers/upload/test_head.py
> +        "exodus-migration-md5": "94e19d5d30b26306167e9e7bae6b28fd",
s3 strips that prefix for us on HEAD requests apparently; seen in my test commented above.
> When you retrieve the object using the SOAP API, the prefix is removed, regardless of which API you used to upload the object.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata

2022-11-17 23:03 UTC, negillett commented on exodus_gw/routers/upload.py
> +    return Response(headers={"ETag": response["ETag"], **response["Metadata"]})
Hmm. Okay. So we wan't the "x-amz-meta-" prefix. Is there a reason? I thought they were just used internally by S3 and by us to determine what should be stored as metadata with an object.

2022-11-17 23:19 UTC, negillett commented on tests/routers/upload/test_head.py
> +        "exodus-migration-md5": "94e19d5d30b26306167e9e7bae6b28fd",
Okay. We want to add the prefix back ourselves. Fixed.

2022-11-17 23:20 UTC, rohanpm commented on exodus_gw/routers/upload.py
> +    return Response(headers={"ETag": response["ETag"], **response["Metadata"]})
Yes, we want the x-amz-meta- prefix on HTTP headers, because:

- that's how the S3 API works
- that's what all S3 clients are going to be looking for (e.g. boto will not see the metadata if the headers are missing that prefix)
- if there's no prefix then there's issues with clashes.  What if a metadata field had the same name as a standard header like "ETag", "Content-Type" or similar?

2022-11-17 23:22 UTC, rohanpm commented on tests/routers/upload/test_head.py
> +        "exodus-migration-md5": "94e19d5d30b26306167e9e7bae6b28fd",
I don't think this is right.  Actually the above doc says:

> When you retrieve the object using the REST API, this prefix is returned.

We are using the REST API, not the SOAP API.

Also your above test comment showed a query to exodus-gw, not to S3 or localstack.  Your test only showed that exodus-gw behavior is buggy.

2022-11-17 23:49 UTC, rohanpm requested changes
Looks like a file named 'tee' has been incorrectly added to the commit, please remove that.  Didn't find any other issues.

2022-11-17 23:49 UTC, rohanpm commented on scripts/launch-devenv
> +            gnome-terminal -- journalctl --user "--unit=exodus-gw-*" -f > gw-dev-env.txt
Hmm, I personally don't use this script and it won't affect my review either way, but I'm wondering if it was intentional to include this?

If you did intend to add something like this, instead of `>` it's possible that something like `| tee -a gw-dev-env.txt` makes more sense so that the logs can still be seen on the terminal and so that previously generated logs don't get removed every time you launch.

2022-11-20 22:00 UTC, rohanpm approved these changes

2022-11-21 15:10 UTC, merged