Add GET publish endpoint [RHELDST-14412]
release-engineering/exodus-gw pull request #494
Opened 2022-12-15 21:39 UTC by negillett

This commit implements a new endpoint to retrieve a publish from the service database. No items are returned with the publish as there is currently no use case for them and implementation would be non-trival.

2022-12-16 02:44 UTC, rohanpm requested changes

2022-12-16 02:44 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +        422: {
Seems like this should be 404, not 422.

2022-12-16 02:44 UTC, rohanpm commented on tests/routers/test_publish.py
> +    assert r.status_code == 422
Should be 404 and not 422.

2022-12-16 15:22 UTC, negillett commented on exodus_gw/routers/publish.py
> +        422: {
@rohanpm, the Jira specified 422 but 404 makes sense too.

2022-12-18 22:47 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +        422: {
I see, I think the JIRA was wrong, will comment there.

2022-12-18 22:47 UTC, rohanpm approved these changes

2022-12-18 23:03 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +            models.Publish.env == env.name,
The other endpoints aren't using 'env' during lookup.  Noticing that made me realize that the other endpoints are buggy, and they should also all be using 'env' like this one is.  Filed a new issue RHELDST-15336.

2022-12-19 14:59 UTC, negillett commented on exodus_gw/routers/publish.py
> +            models.Publish.env == env.name,
👍🏻 Thanks

2022-12-19 14:59 UTC, merged