Add 'env' to publish queries [RHELDST-15336]
release-engineering/exodus-gw pull request #505
Opened 2023-01-31 21:16 UTC by negillett

Previously, when querying publishes from the service db, we only filtered by publish IDs. This commit adds env to the query filter to ensure we're only manipulating publishes belonging to the service environment used.

2023-01-31 22:47 UTC, rohanpm requested changes

2023-01-31 22:47 UTC, rohanpm commented on exodus_gw/routers/publish.py
> -        .with_for_update()
Why are the "with_for_update" being removed?

I don't think they should be.  The point of that is that the records are locked until the current transaction ends.  This is how we ensure it's safe in the case of concurrent requests.

For example: we load this publish, then we later check `if db_publish.state != "PENDING":`.  Given that some time has passed after we load the object from the DB and before we do that check, how do we know the state is up-to-date? (e.g. there could have been another request concurrently which has started to commit the publish.)

The answer is that `.with_for_update()` grabs a lock, so the query here and the similar query in commit_publish won't both be able to get the same object at the same time - one of them will be forced to wait.  If we remove it then concurrent requests seem like they'll lead to corruption.

2023-02-01 14:23 UTC, negillett commented on exodus_gw/routers/publish.py
> -        .with_for_update()
Ah, this was a mistake. Thanks, @rohanpm

2023-02-01 22:18 UTC, rohanpm approved these changes

2023-02-06 13:48 UTC, emanuelelevo approved these changes

2023-02-06 14:50 UTC, crungehottman approved these changes

2023-02-06 15:33 UTC, merged