Include AWS credentials in upload API documentation
release-engineering/exodus-gw pull request #526
Opened 2023-03-22 21:47 UTC by crungehottman

2023-03-22 22:30 UTC, rohanpm requested changes

2023-03-22 22:30 UTC, rohanpm commented on exodus_gw/routers/upload.py
> +                    # Provide AWS credentials to the boto client
I think these should be actual string values which can be just copy-pasted, not placeholders.  The values are not used for authentication here, we are simply forced to provide some values by boto (to prevent it looking in config files and complaining if they're missing).  So something like:

```
# In a typical setup using PKI auth, these values are not used during
# auth to exodus-gw, but boto client always insists on having *some* keys.
# Dummy values can be provided to prevent boto looking for credentials
# in config files.
aws_access_key_id="dummy",
aws_secret_access_key="dummy",
```

Explained a bit more on the gitlab comment for the related MR.

2023-03-23 13:55 UTC, crungehottman commented on exodus_gw/routers/upload.py
> +                    # Provide AWS credentials to the boto client
Thanks!

2023-03-23 13:59 UTC, negillett submitted a review, later dismissed

2023-03-23 14:07 UTC, emanuelelevo submitted a review, later dismissed

2023-03-27 04:01 UTC, rohanpm submitted a review, later dismissed

2023-03-27 04:02 UTC, rohanpm reviewed
Two scripts in `examples` directory configure a boto client, so it would be nice for those to be updated as well for consistency with the docs here.  (If it's not then those scripts probably have the same hidden requirement right now that you need to have `AWS_PROFILE` set and you need to have some credentials in config files.)

2023-03-27 23:04 UTC, rohanpm approved these changes

2023-03-28 12:55 UTC, merged