Return xml error responses for upload API [RHELDST-3354]
release-engineering/exodus-gw pull request #54
Opened 2020-10-12 20:06 UTC by nathanegillett

Adds a simple override of the HTTPException to return an XML response.

2020-10-12 21:08 UTC, rohanpm commented on exodus_gw/s3/api.py
> +@app.exception_handler(StarletteHTTPException)
It seems like this will be applied onto all of the API endpoints - I'm not seeing a reason this would be restricted to the S3 APIs.  It should be, as we don't want to use that XML error response anywhere else.

Could you look into that and make sure it applies onto these APIs only?

2020-10-13 09:12 UTC, lioramilbaum commented
Can you please provide the reasoning for this change and also fix the broken CI.

2020-10-13 17:44 UTC, nathanegillett commented
I've moved the handler to the gateway module since its scope is includes the whole app.
It's designed with the expectation that forthcoming methods may need XML responses, e.g., committing publishes to DynamoDB.

2020-10-13 21:49 UTC, rohanpm requested changes

2020-10-13 21:49 UTC, rohanpm commented on exodus_gw/gateway.py
> +    return JSONResponse(
If we get here, instead of returning JSONResponse explicitly, could we please fall back to the default fastapi exception handlers?  I think we should only deviate from them where we have a specific reason for it.

As in example: https://fastapi.tiangolo.com/tutorial/handling-errors/#re-use-fastapis-exception-handlers

I think instead of returning JSONResponse we'd be doing:

```
from fastapi.exception_handlers import http_exception_handler
...
return await http_exception_handler(request, exc)
```

2020-10-13 21:49 UTC, rohanpm commented on exodus_gw/gateway.py
> +        return xml_response(
Just curious have you checked how boto library behaves now when receiving these error responses?

The acceptance criteria for the issue doesn't require identical behavior as the real S3.  However I do see one difference here which might be significant: seems like this will result in the HTTP status code (number) appearing in Code, as in `<Code>500</Code>`.  While in the real API, it returns strings such as `<Code>NoSuchKey</Code>`.  So, I wonder if the boto library is going to behave reasonably in that case (which is the goal of the issue).

2020-10-13 21:49 UTC, rohanpm commented on exodus_gw/gateway.py
> +    return JSONResponse(
(...and then this custom method perhaps should not be named http_exception_handler.)

2020-10-14 13:40 UTC, nathanegillett commented on exodus_gw/gateway.py
> +        return xml_response(
I did notice this but didn't think it'd be of consequence. I'll run a test to make sure.

2020-10-14 13:48 UTC, nathanegillett commented on exodus_gw/gateway.py
> +    return JSONResponse(
Done!

2020-10-14 16:21 UTC, nathanegillett commented on exodus_gw/gateway.py
> +        return xml_response(
So, this does not affect botocore behavior. We _could_ replace the specific HTTP code with the name of the exception but that will only ever be "HTTPError", which isn't very informative.
I'd prefer to either leave it as-is or change it to a name-code combination.

2020-10-14 16:29 UTC, nathanegillett commented on exodus_gw/s3/util.py
> +        status_code=status_code,
This was necessary to raise the error, as it defaults to 200 otherwise.

2020-10-14 21:45 UTC, rohanpm approved these changes

2020-10-15 15:12 UTC, merged