Convert logging format to JSON [RHELDST-18175]
release-engineering/exodus-gw pull request #550
Opened 2023-06-06 18:58 UTC by negillett

In addition to formatting all logs as JSON, this commit makes timestamp
format configurable upon setting a "datefmt" key in log_config settings.

2023-06-06 21:46 UTC, rohanpm requested changes

2023-06-06 21:46 UTC, rohanpm commented on exodus_gw/logging.py
> +            "level": "levelname",
Could you please also include the logger name here?  Similarly as done in https://github.com/release-engineering/exodus-lambda/commit/d169e23e571a890c2d0ce30518f3f5147e49fb06 .

2023-06-07 14:11 UTC, negillett commented
Also note that I only provided success values where it seemed appropriate. Some log message don't mean any particular operation succeeded/failed.

2023-06-07 22:15 UTC, rohanpm approved these changes

2023-06-07 23:22 UTC, merged