Update test-requirements via pip-compile
release-engineering/exodus-gw pull request #570
Opened 2023-08-15 21:16 UTC by negillett

There is a conflict reported by bandit in the current chore: pip-compile PR, #558. Hopefully a manual update corrects this.

2023-08-16 17:32 UTC, negillett commented
@crungehottman @rohanpm @dichn

2023-08-16 18:43 UTC, crungehottman submitted a review, later dismissed

2023-08-16 22:25 UTC, rohanpm requested changes

2023-08-16 22:25 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +        examples=[
This change doesn't seem right. I've assumed the example => examples change is because the library changed from using a single example value, to supporting a list of example values, and that's why you wrapped all the other values in a list.

If you don't also wrap this value in a list, then isn't this changing the meaning of it?  Instead of one example request body, being a list, I think you've changed the meaning into 4 example request bodies, each being a dict.  

The API is designed to take a list, so each example needs to be a list (and it's acceptable to have just one example).

2023-08-17 16:27 UTC, crungehottman approved these changes

2023-08-20 23:23 UTC, rohanpm approved these changes

2023-08-21 01:19 UTC, dichn approved these changes

2023-08-21 13:20 UTC, merged