Add logging handler to write to healthcheck file [RHELDST-19614]
release-engineering/exodus-gw pull request #577
Opened 2023-08-31 16:37 UTC by negillett

To track the healthiness of workers in OCP, we'll probe for a specific
file, checking it's latest update time and restarting should a certain
time elapse since that update.

This commit implements the necessary mechanism for writing that file.
By using a custom logging handler, we implement an emit method to log
updates the healthcheck file. The location of the healthcheck file can
be configured via a new setting, "worker_health_filepath".

2023-09-03 22:50 UTC, rohanpm requested changes

2023-09-03 22:50 UTC, rohanpm commented on exodus_gw/logging.py
> +        handler = GWHandler(settings)
I don't think this should be under the `hasHandlers` condition.

I think the point of this block was to ensure: if there are no handlers at all, then ensure there's at least a basic stream handler set up.  But in practice I don't think we can necessarily predict whether this block is entered, given that:

- It's possible for the `dictConfig` above to have installed some handlers.
- It's possible for third-party code to have installed some handlers before we get here (and there's multiple relevant cases: running under uvicorn, gunicorn, dramatiq or pytest).

I don't think it would be right to not install the special handler in those cases.

I also don't think it was necessary to have GWHandler *extend* a StreamHandler.  It's possible that StreamHandler isn't even the desired type of handler, e.g. uvicorn/gunicorn/dramatiq all accept command-line arguments to log to a file which I believe causes them to install something other than a StreamHandler.

Loggers are designed to support any number of handlers, so we could have left GWHandler dedicated to just updating the healthcheck file while logging to a stream happens via StreamHandler as normal.  Wouldn't that be cleaner?

The final complicating factor is that I think this function can sometimes be called more than once in the process, at least in the "development server with hot reload enabled" case.

Taking that all together I think the logic here ought to be something more like this:

```
# if no handlers at all...
if not root_logger.hasHandlers():
    # then add at least a basic stream handler so logs can be seen
    root_logger.addHandler(logging.StreamHandler())

# if no GWHandler...
if not any([isinstance(h, GWHandler) for h in root_logger.handlers]):
    # then ensure there's one of those too
    root_logger.addHandler(GWHandler(settings))
```

2023-09-05 20:01 UTC, negillett commented on exodus_gw/logging.py
> +        handler = GWHandler(settings)
Hmm. Yeah, I didn't consider missing the StreamHandler block a realistic probability. And maybe it's simpler to keep the handlers separate.

I've simplified the GWHandler, extending logging.Handler instead, and added it to the logger as a separate handler.

2023-09-05 21:14 UTC, rohanpm approved these changes

2023-09-06 00:24 UTC, rohanpm commented
May as well get this deployed.

2023-09-06 00:24 UTC, merged