Add request/correlation IDs to log messages [RHELDST-18313]
release-engineering/exodus-gw pull request #583
Opened 2023-09-12 21:56 UTC by negillett

Previously, it was unclear which messages were logged for which request. Now, using the new 'request_id' field, one can match log messages that are associated with a particular request.

2023-09-12 22:26 UTC, rohanpm approved these changes

2023-09-12 22:26 UTC, rohanpm commented on tests/routers/test_common.py
> +            "request_id": r.headers["X-Request-ID"][:8],
I'm curious about the :8 , does the X-Request-ID end up with some kind of prefix which doesn't show up in the request_id in the log?

2023-09-12 22:26 UTC, rohanpm commented on exodus_gw/main.py
What's here looks good, but I would ask can we please also add an exception_handler here to process the 500 Internal Server Error case.

I'm looking at https://github.com/snok/asgi-correlation-id#exception-handling and it's mentioned that the X-Request-ID by default will not be added on 500 responses.  That seems like an important case & I'm a bit surprised that's the default.  Cases where our server is crashing might be where the request ID is most valuable.

There is a FastAPI example there and I *think* just copy-pasting that exactly as it is would work.  It should play nicely with the other `app.exception_handler` already defined here.

2023-09-13 13:31 UTC, negillett commented on tests/routers/test_common.py
> +            "request_id": r.headers["X-Request-ID"][:8],
The "X-Request-ID" header has a full 32 char ID but only the first 8 are logged as "request_id", per the filter settings. I felt the full ID would clutter the logs unnecessarily--8 chars is enough to match messages, I think.

2023-09-13 17:21 UTC, negillett commented on exodus_gw/main.py
Actually, from a new test, it looks like HTTP errors of code 500 include the correlation ID just fine so long as it originates from the app. The only cases in which X-Request-ID is null is when the app isn't really in use, such as logs coming from DB.

2023-09-13 22:22 UTC, rohanpm requested changes

2023-09-13 22:22 UTC, rohanpm commented on exodus_gw/main.py
> +            Headers=request.headers,
Same point here that I don't think it's right to copy the request headers into the response.

2023-09-13 22:22 UTC, rohanpm commented on exodus_gw/main.py
I had the same thought about the handlers, but I did investigate it a bit before making the suggestion and found there is special handling which should make handling of `Exception` work as desired.

It ultimately boils down to this code: https://github.com/encode/starlette/blob/93074e82ab15e860456d4a7074c0494eed78ea0c/starlette/applications.py#L84

You can see that an exception handler for `Exception` or for 500 status is picked out separately from all the rest, and then ends up installed at "the very outermost middleware" (as a comment in that file calls it).

So if we add an `Exception` handler exactly as the example, that should play nicely with all the other more specific handlers.  It does not override them, instead it's used as a last resort.

This is why I really do expect that copy-pasting the asgi-correlation-id README example ought to work and is the right thing to do rather than updating the exception handlers we've already added.  Those aren't designed to catch all types of exceptions anyway.

Not 100% sure but I'm guessing that "DB is offline" is probably a case where none of those existing exception handlers get invoked and X-Request-ID would currently be missing.

2023-09-13 22:22 UTC, rohanpm commented on tests/routers/test_common.py
> +            "request_id": r.headers["X-Request-ID"][:8],
I see.  I agree 32 chars is too much.

I'm wondering if the right way is to instead override `generator` when creating the CorrelationIdMiddleware.  Docs say it defaults to `generator=lambda: uuid.uuid4().hex`, I guess changing it to `generator=uuid.uuid4().hex[:8]` would make the value as 8 chars all the way through both the logging & request headers.

That is probably slightly nicer - I'm thinking, if someone does in fact report a failure and their failed response has a 32-char request ID, if anyone tries to copy-paste that directly into Splunk they're going to find nothing.  Are they really going to remember that they need to chop only 8 chars?  Will they remember whether that's at the beginning or the end?  Will they do it correctly or will they accidentally get the wrong number of chars and fail to find any matching messages?

2023-09-14 14:39 UTC, negillett commented on exodus_gw/main.py
Ah, okay. I totally missed the method name (for FastAPI) as well which hints at its uniqueness.
Thanks!

2023-09-14 14:45 UTC, negillett commented on tests/routers/test_common.py
> +            "request_id": r.headers["X-Request-ID"][:8],
This actually works really well. I wish they advertised this solution rather than suggesting truncating via filter, creating this inconsistency between the log and header. Or move truncation down to the middleware level, adding the uuid_length option to that class. But I digress. Thanks for the suggestion.

2023-09-14 16:11 UTC, negillett commented on exodus_gw/main.py
> +        headers=request.headers,
Yeah, you're right. Request headers probably aren't good here and, through more testing, the header is already included in JSONReponse. This is not the case for our custom xml_response, however.

2023-09-14 16:13 UTC, negillett commented on exodus_gw/main.py
> +            Headers=request.headers,
I've removed the request headers but included the X-Request-ID header, as it's not automatically applied like the others (presumably because it's our own function).

2023-09-14 16:24 UTC, negillett commented
@rohanpm @crungehottman @dichn, ready for another look

2023-09-14 18:13 UTC, crungehottman submitted a review, later dismissed

2023-09-14 21:54 UTC, rohanpm requested changes

2023-09-14 21:54 UTC, rohanpm commented on tests/routers/upload/test_manage_mpu.py
> +        b"<Headers>{'X-Request-ID':"
This doesn't seem correct, on two levels:

- rather than adding the X-Request-ID as an HTTP response header it's added it into a new `<Headers>` section of the response body.
- rather than representing the X-Request-ID as a key/value in the way you'd expect for either XML or JSON, this seems to be just the default python stringification of a dict.

Given that these responses are meant to be used on the APIs which aim to be S3-compatible, we have to be very careful about inserting new parts into the response which are not in real S3, because existing clients like boto might not expect those and might start crashing or doing something strange.

I think what you want to do is, instead of:

```python
return xml_response(..., Headers={'X-Request-ID': ...})
```

Update the response object after creating it:

```python
response = xml_response(...)
response.headers['X-Request-ID'] = ...
return response
```

... because the xml_response function is designed to put all of its kwargs into the XML document.  It doesn't have any way to adjust the headers.

I would suggest also double-checking if the custom_http_exception_handler really needed *any* changes at all, because what *ought* to be happening is that the installed CorrelationIdMiddleware already gets a chance to rewrite the value returned from that function anyway.  So it's unclear why the handler itself would also need to do anything.

2023-09-15 14:27 UTC, negillett commented on tests/routers/upload/test_manage_mpu.py
> +        b"<Headers>{'X-Request-ID':"
Looks like the middleware is adding the header to the xml_response as well.
Also, while the new unhandled_exception_handler is covered by a test (test_db_rollback_on_raise_db), removing it entirely doesn't cause any failures. So I guess this new handler is really just an insurance policy.

2023-09-17 23:01 UTC, rohanpm approved these changes

2023-09-18 13:43 UTC, merged