Add policy to redirect requests for reuse [RHELDST-18071]
release-engineering/exodus-gw pull request #606
Opened 2023-10-13 21:43 UTC by negillett

2023-10-15 21:37 UTC, rohanpm requested changes

2023-10-15 21:37 UTC, rohanpm commented on exodus_gw/routers/cdn.py
> +        "Policy=%s" % cf_b64(policy).decode("utf8"),
This doesn't seem like it's going to be useful.  The policy and signature here only enable access to the /_/cookie endpoint, so it can't be reused in a cookie for accessing any other paths.

You can think of it this way: we're shifting responsibility for generating the policy/signature which lives in the cookie from `/_/cookie` endpoint to here.  Therefore the policies/signatures generated here will have to include at least whatever `/_/cookie` was previously generating.

I'm pretty sure there will need to be three policies in total:
1. one for `/content/*`
2. one for `/origin/*`
3. one for `dest_url` (which starts with `/_/cookie/`)

The first two policies need to be somehow wrapped up for the request for `/_/cookie/`, e.g. encoded into query parameters.  But that should NOT be using the standard `Policy`, `Signature` since the point is to get the policy into our own exodus-cdn code, and not processed by CloudFront.

2023-10-16 16:16 UTC, negillett commented on exodus_gw/routers/cdn.py
> +        "Policy=%s" % cf_b64(policy).decode("utf8"),
Ah, I see. Thanks for clarifying!

2023-10-16 16:47 UTC, negillett commented
@rohanpm @crungehottman updated to forward origin and content signatures

2023-10-16 20:45 UTC, crungehottman approved these changes

2023-10-16 21:22 UTC, rohanpm requested changes

2023-10-16 21:22 UTC, rohanpm commented on exodus_gw/routers/cdn.py
> +    content_url = os.path.join(env.cdn_url, "/content/*")
I don't think these os.path.join make sense because they're just going to return whatever the second argument was, since it's an absolute path. e.g.

```
>>> os.path.join('https://abc.cloudfront.net/foo/bar', '/content/*')
'/content/*'
```

I believe this is a rare case where you might actually want to use urljoin:

```
# this is exactly what we want, the "/" brings us up to the root of the URL's domain and no further
>>> from urllib.parse import urljoin
>>> urljoin('https://abc.cloudfront.net/foo/bar', '/content/*')
'https://abc.cloudfront.net/content/*'
```

2023-10-16 21:22 UTC, rohanpm commented on exodus_gw/routers/cdn.py
> +        "Content-Signature=%s" % cf_b64(content_signature).decode("utf-8"),
While this approach should work, I would like to suggest that we wrap up all the info in a single parameter.

The reason is that, right now it looks like you'll have to update exodus-cdn to look explicitly at Content-* and Origin-* parameters, which means the detail of "we generate cookies for /content/ and /origin/" is spread across two places and they'll both have to change if we want different logic at some point.

I think it would be a good idea to instead design this as a list and have exodus-lambda apply whatever's in the list, that way if we ever want to change the setup we only have to change what we put in this list and everything will work out.

Concretely I mean something like this:

```python
# policies to be inserted into cookies.
cookie_policies = [
  # note: path should NOT have the trailing "*" here because this value
  # needs to go into "Path" attribute on the cookie which does not use wildcards.
  {"path": "/content/", "policy": content_policy, "signature": content_signature},
  {"path": "/origin/", "policy": origin_policy, "signature": origin_signature},
]

params = [
    ...,
    "CookiePolicies=%s" % cf_b64(json.dumps(cookie_policies)).decode("utf-8"),
]
```

And then exodus-lambda does the inverse (base64 decode, json load) to get the list back, and the hardcoded two calls to signer.cookies_for_policy in exodus-lambda are replaced with iterating over this list.

2023-10-17 13:30 UTC, negillett commented on exodus_gw/routers/cdn.py
> +    content_url = os.path.join(env.cdn_url, "/content/*")
Oh, interesting. Thanks!

2023-10-17 20:13 UTC, negillett commented
@rohanpm, @crungehottman, I decided to take this a step further and orient all the data as expected by set-cookie in exodus-lambda. Now each list item can be inserted directly into the set-cookie dict once decoded.

2023-10-17 20:15 UTC, negillett commented
Note that this brings the querystring length just over 2800 characters. We'll need to increase the accepted length limit in exodus-lambda to accommodate (3000?).

2023-10-17 21:16 UTC, rohanpm requested changes

2023-10-17 21:16 UTC, rohanpm commented on exodus_gw/routers/cdn.py
> +    cookies_bytes = bytes(str(cookies), "utf-8")
You used default python stringification here rather than e.g. a json dump.  How do you propose to parse it on the other end?

Did you check the value that this generates?  It seems wrong in a couple of ways.  Here's what the value produced by the test looks like (some whitespace added):

```
['CloudFront-Key-Pair-Id=XXXXXXXXXXXXXX; Secure; HttpOnly; SameSite=lax; Domain=http://localhost:8049/_/cookie; Path=/content/; Max-Age=1800',
'CloudFront-Policy=b\'{"Statement":[{"Resource":"http://localhost:8049/content/*","Condition":{"DateLessThan":{"AWS:EpochTime":1644971400}}}]}\'; Secure; HttpOnly; SameSite=lax;
Domain=http://localhost:8049/_/cookie; Path=/content/; Max-Age=1800',
'CloudFront-Signature=b"G\\xa9>\\x04k\\xcd...
```

Problems:

- it's not of any particular format, not even round-trippable python which could be passed to "eval".
- the CloudFront-Signature part seems like it contains a stringification of the raw bytes rather than having them encoded in the required way.

2023-10-17 21:16 UTC, rohanpm commented on tests/routers/test_cdn.py
> +        "Cookie-Policies=WydDbG91ZEZyb250LUtleS1QYWlyLUlkPVhYWFhYWFhYWFhYWFhYO"
In order to find that the encoded value of Cookie-Policies doesn't make sense, I copy-pasted this into a text file, cleaned it up and ran it through `base64 -d` to check it.

It's not reasonable to expect reviewers to do that, so can you please add a test which somehow covers the newly added code *before* the output value gets encoded?  For example, put that new code in a standalone function and add a new test which calls it.

2023-10-17 21:17 UTC, rohanpm commented
> Note that this brings the querystring length just over 2800 characters. We'll need to increase the accepted length limit in exodus-lambda to accommodate (2000->3000?).

I suggest making that change immediately so that all exodus-cdn environments will already be capable of accepting the longer query string before we submit this into exodus-gw.

2023-10-17 21:25 UTC, negillett commented on exodus_gw/routers/cdn.py
> +    cookies_bytes = bytes(str(cookies), "utf-8")
Ah, overlooked the policy when dropping json and forgot to bring over the b64 decodes. Thanks.

2023-10-18 21:11 UTC, rohanpm requested changes

2023-10-18 21:11 UTC, rohanpm commented on exodus-gw.ini
> +cdn_url = http://localhost:8049
Why was this changed?

2023-10-18 21:11 UTC, rohanpm commented on exodus_gw/routers/cdn.py
> +        append = f"; Secure; HttpOnly; SameSite=lax; Domain={env.cdn_url}; Path={path}; Max-Age={timeout}"
Maybe this is why the cdn_url setting was changed, so that `Domain={env.cdn_url}` would work?

I don't think that makes sense though, because we still need the redirect endpoint to redirect to `/_/cookie` specifically and not `/`, and it still preferably remains configurable as it is today.

I think you just need to extract the correct part out of `env.cdn_url` and not expect it to already be the needed value.

2023-10-18 23:15 UTC, negillett commented on exodus-gw.ini
> +cdn_url = http://localhost:8049
I mistook it for an error/something set for testing. From a quick check of real configs, it looks like this is the correct/expected path and it's the other envs that are incorrect.

2023-10-19 00:48 UTC, rohanpm approved these changes

2023-10-19 14:12 UTC, merged