exodus-gw: upgrade to python 3.11 [RHELDST-20628]
release-engineering/exodus-gw pull request #609
Opened 2023-10-18 13:29 UTC by dichn

2023-10-18 16:08 UTC, crungehottman submitted a review, later dismissed

2023-10-18 17:19 UTC, negillett approved these changes

2023-10-18 20:45 UTC, rohanpm requested changes

2023-10-18 20:45 UTC, rohanpm commented on requirements.in
> +# have its dep versions pinned with == (until anyio 4.0.0), it
"anyio does not have its dep versions pinned with ==" - this is expected, and should be true for all libraries.  So it's strange to mention this for anyio in particular.  The comment doesn't seem to make sense.

2023-10-18 20:45 UTC, rohanpm commented on requirements.in
> +exceptiongroup>=1.0.2
This doesn't seem right:

- firstly, the default behavior is already to use the latest version, so shouldn't a `>=` range be redundant?  If this is needed at all, wouldn't it be sufficient to just list `exceptiongroup`?
- secondly, why do we need this if we already have at least one dep which depends on `exceptiongroup`?  Why isn't it being found automatically?  The fact that `exceptiongroup` was already in requirements.txt prior to this change, seems to indicate that it *is* being found automatically.

Overall I'm not sure that the problem has been diagnosed properly.

Let me show you something from what you pasted in JIRA:

```
#7 27.29   Downloading zope.interface-6.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (246 kB)
#7 27.65 Collecting exceptiongroup
#7 27.65 ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
#7 27.65     exceptiongroup from https://files.pythonhosted.org/packages/ad/83/b71e58666f156a39fb29417e4c8ca4bc7400c0dd4ed9e8842ab54dc8c344/exceptiongroup-1.1.3-py3-none-any.whl#sha256=343280667a4585d195ca1cf9cef84a4e178c4b6cf2274caef9859782b567d5e3 (from anyio==3.7.1->-r requirements.txt (line 122))
#7 ERROR: process "/bin/sh -c microdnf -y install shadow-utils     && microdnf -y install python3 python3-devel gcc make     && microdnf -y install postgresql-devel     && microdnf -y update     && cd /usr/local/src/exodus-gw     && pip3 install --require-hashes -r requirements.txt     && pip3 install --no-deps .     && microdnf clean all && rm -rf /var/cache/yum && rm -rf /usr/local/src/exodus-gw" did not complete successfully: exit code: 1 
```

See that:

- the wheel filename contains `cp39` (cpython 3.9)
- the dnf command refers to "python3" and not "python3.11"

So isn't the actual problem that the build shown above was still trying to use python 3.9?

2023-10-19 00:26 UTC, rohanpm approved these changes

2023-10-19 00:54 UTC, merged