Create publish
release-engineering/exodus-gw pull request #68
Opened 2020-10-28 17:27 UTC by lioramilbaum

2020-11-01 21:44 UTC, rohanpm commented on exodus_gw/gateway.py
> +def publish(env: str, db: Session = Depends(get_db)):
Just linking this to another PR: https://github.com/release-engineering/exodus-gw/pull/69

To me, it seems like the approach here for getting a reference to the DB is appropriate and it allows us to remove the `db` global which was previously initialized at import time.  Therefore: I think *this* PR is the right way to solve the problem which seems to be addressed in a different way by https://github.com/release-engineering/exodus-gw/pull/69.

2020-11-05 17:58 UTC, lioramilbaum commented on exodus_gw/gateway.py
> +def publish(env: str, db: Session = Depends(get_db)):
Not accurate. There was another call in main.py (formally app.py) which triggered the tests failures: `models.Base.metadata.create_all(bind=engine)`.

2020-11-09 11:44 UTC, lioramilbaum commented
I am not still trying to figure out how to resolve the coveralls failure. Any ideas?

2020-11-09 11:48 UTC, lioramilbaum commented
@thrix Can you please take a look at the tests I've implemented? Not sure they cover everything.

2020-11-09 13:57 UTC, nathanegillett commented on tests/unit/test_gateway.py
> +    publish = gateway.publish(env=env, db=mock_db_session)
All of these `gateway.publish` calls fail because you aren't awaiting the coroutine.
```suggestion
    publish = await gateway.publish(env=env, db=mock_db_session)
```
^ should fix it.

2020-11-09 14:06 UTC, nathanegillett commented on tests/unit/test_gateway.py
> +from types import GeneratorType
I'm not sure creating a "unit" directory is the right way to go. We typically mimic the application structure within 'tests/'; test_gateway.py and test_api.py would be under 'tests/routers' while 'tests/s3' holds test files for modules under 'exodus_gw/s3'. Does that make sense?

That said, if 'tests/unit/' is meant to hold all unit tests, as the name implies, everything under 'tests/' should be moved there, right? All the tests we currently have are unit tests.

2020-11-09 14:16 UTC, nathanegillett commented
Could you update the commit subject line with the Jira issue ID, please?

2020-11-09 14:29 UTC, nathanegillett commented on exodus_gw/models.py
> +        default=uuid.uuid4,
Does this take care of https://projects.engineering.redhat.com/browse/RHELDST-2819, insert publish ID into the publish table?

2020-11-09 14:32 UTC, nathanegillett commented on exodus_gw/models.py
> +    )
Does this take care of https://projects.engineering.redhat.com/browse/RHELDST-2819, insert publish ID into the publish table?

2020-11-09 14:43 UTC, nathanegillett commented on exodus_gw/crud.py
> +from sqlalchemy.orm import Session
Not sure the name of this file is appropriate. There are C.R.U.D. operations elsewhere in this project so the name is potentially confusing. This module is specific to "publish" operations correct? Shouldn't it be named as such?

2020-11-09 22:51 UTC, rohanpm requested changes

2020-11-09 22:51 UTC, rohanpm commented on exodus_gw/routers/gateway.py
> +        return {"Error": "environment {0} not found".format(env)}
Why did "error" change to "Error" here?  It shouldn't be as it's not compatible with other error formats.

2020-11-09 22:51 UTC, rohanpm commented on exodus_gw/crud.py
> +    db.commit()
This can be something revisited later, but at some point - I doubt we'll be wanting to have the DB committed inside of functions like this.

Usually it's possible to arrange things so that:

- transaction begins when we start handling user's request
- transaction is committed if request succeeds, or rolled back if it fails

This is nice as the entire effect of the user's request is committed all at once and you won't risk bugs such as partially committed changes if a request fails part way through.

2020-11-09 22:51 UTC, rohanpm commented on test-requirements.in
> +pytest-docker-compose
Could we please not introduce this dependency for the test suite:

- docker is on the way out. Docker is no longer shipped for Fedora, which I believe most of the devs are using as their OS.  Tooling should be migrating to podman, but I don't think it has a good equivalent for docker-compose (and the recommended approach probably is rather to use systemd units for the containers rather than some docker-specific tooling which basically does the same thing but worse).
- The tests ideally shouldn't be depending on any external process.  Doing that usually is making the tests significantly slower, more flaky, and making your typical debugging & coverage measurement tools less effective.

I think the tests which are run by CI or when you just run "tox" locally just shouldn't connect to any real postgres server and that should be left to later testing.  The most common solution I've seen to this, which has worked well in all projects I've seen it used, is to use a different in-process DB such as sqlite during the test suite execution.

2020-11-09 22:51 UTC, rohanpm commented on tests/conftest.py
> +    service = session_scoped_container_getter.get("app").network_info[0]
Instead of running the service in a container and firing requests to it, can we please use the test client designed for this purpose instead: https://www.starlette.io/testclient/

2020-11-10 09:13 UTC, lioramilbaum commented on tests/unit/test_gateway.py
> +from types import GeneratorType
The current directory structure (under test folder) make sense while we are implementing unit tests only.
The current PR drove the need to implement functional tests as well.  I have seen in other python projects as this one that it is a good practice to separate the unit tests from the function tests. With this structure, one can invoke only unit tests or functional tests easier. Does that make sense?
If that is agreed, I'll submit a new PR which moves all current unit tests to the unit folder.

2020-11-10 09:19 UTC, lioramilbaum commented on exodus_gw/models.py
> +    )
Yes, but not those specific lines.

2020-11-10 09:21 UTC, lioramilbaum commented on exodus_gw/crud.py
> +from sqlalchemy.orm import Session
It doesn't have to be specific to publish. It can be used by all functions which change/read/update/delete db data with ORM.

2020-11-10 09:30 UTC, lioramilbaum commented on test-requirements.in
> +pytest-docker-compose
See in a previous comment. This PR drove the need to have functional tests as well.  Functional testing requires spinning of the app and db containers. Orchestrating the spinning with docker-compose for functional tests is the fastest way. Does that make sense?

2020-11-10 13:19 UTC, lioramilbaum commented on tests/conftest.py
> +    service = session_scoped_container_getter.get("app").network_info[0]
I have tried working with the test client with no avail. It requires spinning a PostgreSQL server locally. See my comment in previous conversation on why that didn't work.

2020-11-10 13:21 UTC, lioramilbaum commented
@rohanpm @nathanegillett This PR became too big for review. I would suggest I break it into few smaller PRs.

2020-11-10 16:50 UTC, nathanegillett commented on tox.ini
> +	-r test-requirements.txt
whitespace?

2020-11-10 16:50 UTC, nathanegillett commented on tox.ini
> +testpaths = tests/unit tests/auth tests/s3
this will conflict with the tests dir structure change PR

2020-11-10 16:50 UTC, nathanegillett commented on tests/unit/test_gateway.py
> +    assert isinstance(db, GeneratorType)
this test seems insufficient now, no? we should want to ensure that a _db_ is created/retrieved.

2020-11-11 04:24 UTC, rohanpm requested changes

2020-11-11 04:24 UTC, rohanpm commented on exodus_gw/routers/gateway.py
> +# https://stackoverflow.com/questions/62265626/why-not-getting-100-coverage-on-fastapi-with-pytest-cov-using-starlettes-testcl/64765411#64765411
Am I missing something?  This seems to be just a question with no answer.  I am skeptical that there is a valid reason to put the "pragma: no cover".

2020-11-11 04:24 UTC, rohanpm commented on test-requirements.in
> +pytest-docker-compose
> Functional testing requires spinning of the app and db containers.

I disagree with the premise here.  All code that you've written here should be testable without fragmenting the test suite as done in https://github.com/release-engineering/exodus-gw/pull/81 and without introducing tests which depend on some additional processes/containers.  I'm confident any issues you hit with sqlite or the starlette test client can be resolved.

2020-11-11 04:24 UTC, rohanpm commented on tests/conftest.py
> +    service = session_scoped_container_getter.get("app").network_info[0]
This doesn't make sense to me as these are two separate issues:

1. How do tests get requests into our app code?
2. How does our app code issue requests to DB during tests?

If you think the answer to (2) is "it needs to connect to a postgres server", that's one thing, but I don't see how it logically follows that the answer to (1) then needs to be "we need to run our app in a container and issue HTTP requests to it".

2020-11-12 18:53 UTC, lioramilbaum commented
The Travis CI is failing do to a python dependency conflict. I didn't find yet an elegant way to resolve it.

2020-11-12 19:13 UTC, lioramilbaum reviewed
> The Travis CI is failing do to a python dependency conflict. I didn't find yet an elegant way to resolve it.

I have raised this issue with some python experts. They suggested switching to poetry. WDYT?

2020-11-18 14:19 UTC, nathanegillett requested changes

2020-11-18 14:19 UTC, nathanegillett commented on tests/functional/conftest.py
> +from typing import Tuple
I'm not seeing the necessity of introducing functional tests with this PR. I'm certain it's possible to ensure the code changes are covered by unit tests so that we can get this PR merged.

2020-11-18 14:19 UTC, nathanegillett commented on tests/unit/test_gateway.py
> +from types import GeneratorType
The necessity of a "unit" directory hinges on the necessity of a "functional" directory. I don't believe the addition of either are required for this PR.

2020-11-18 15:23 UTC, lioramilbaum commented on tests/functional/conftest.py
> +from typing import Tuple
The code changes are covered by unit tests. This is an additional test which should not have an impact on the ability to get the PR merged.

2020-11-18 15:25 UTC, lioramilbaum commented on tests/unit/test_gateway.py
> +from types import GeneratorType
I am not sure I agree with this statement.

2020-12-01 04:00 UTC, rohanpm approved these changes

2020-12-01 16:26 UTC, nathanegillett approved these changes

2020-12-01 16:30 UTC, merged