Enforce /origin/files invariant [RHELDST-23443]
release-engineering/exodus-gw pull request #699
Opened 2024-04-19 22:03 UTC by crungehottman

In order to prevent conflicts, ensure that all clients follow the correct usage of the /origin/files/sha256 structure.

When clients publish underneath the /origin/files/sha256/ path, it is enforced that:

(1) The path always matches this format:
/origin/files/sha256/(first two letters of sha256sum)/(full sha256sum)/(basename)

(2) Every object_key is either absent, or is equal to the full sha256sum present in the path.

When either rule is broken, the request is denied with a 400 response.

2024-04-21 21:58 UTC, rohanpm requested changes

2024-04-21 21:58 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +            re.compile("^(/content)?/origin/files/sha256/.*$"), i.web_uri
This looks a bit weird: regular expressions don't usually need to be compiled.  They can be compiled to make the code more efficient if the pattern will be used many times.  However, this is going to compile the regex at every iteration of the loop over items, which could be 10,000 times.

If this is going to be compiled it should probably be at the same level as origin_regex, e.g. you could have `origin_base_regex`, `origin_regex`.

2024-04-21 21:58 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +                detail="Invalid path format for '%s' (unmatched regex)"
I think it would be nice if this message gave the user a hint that this is specifically about origin/files so they have something to search for.  Just "invalid path format ... unmatched regex" seems very difficult to find more information about, and in fact the user might assume it's an exodus-gw bug.  If it points towards origin/files, at least the caller can search for how other code deals with /origin/files and might realize that they are doing something which doesn't follow established conventions.

In fact in each of these branches I feel like the message you've got in the logs is a better user-facing message than the one you've put into the exceptions right now.

2024-04-21 21:59 UTC, rohanpm commented on exodus_gw/routers/publish.py
> +            re.compile("^(/content)?/origin/files/sha256/.*$"), i.web_uri
... or moving both of them up to global scope so they are compiled once at import time.

2024-04-22 22:01 UTC, rohanpm approved these changes

2024-04-23 15:41 UTC, negillett approved these changes

2024-04-23 22:34 UTC, merged