CI - lint with flake8 with GitHub Actions workflow
release-engineering/exodus-gw pull request #70
Opened 2020-10-31 08:29 UTC by lioramilbaum

2020-11-01 21:13 UTC, rohanpm commented on .github/workflows/linting.yml
> +          pip install flake8
Should this have a locked version of the tool, as we have implemented previously in test-requirements.txt?

Actually I'd suggest including flake8 in test-requirements.{in,txt} and just installing test-requirements.txt here, even though it'll waste a bit of time installing non-flake8 packages.  That will allow it to integrate with the existing dependabot setup.

2020-11-01 21:13 UTC, rohanpm commented on exodus_gw/__init__.py
> +from . import gateway, s3  # noqa
What error is suppressed by this noqa?

2020-11-01 21:13 UTC, rohanpm commented on docs/conf.py
> -    "description": "Publishing microservice for Red Hat's Content Delivery Network",
I see a lot of these changes were to get within the tool's configured line length.

I think it's misconfigured though.  We have typically used a line length of 100 rather than the default of ~80.  Would you mind updating the config instead so the tool is using 100?  That probably will remove the need for many of these changes.

2020-11-02 08:48 UTC, lioramilbaum commented on exodus_gw/__init__.py
> +from . import gateway, s3  # noqa
`(exodus) [lmilbaum@lmilbaum exodus-gw]$ flake8 .
./exodus_gw/__init__.py:2:1: F401 '.gateway' imported but unused
./exodus_gw/__init__.py:2:1: F401 '.s3' imported but unused`
This peace of code is about to be removed in a future PR.

2020-11-02 09:19 UTC, lioramilbaum commented on docs/conf.py
> -    "description": "Publishing microservice for Red Hat's Content Delivery Network",
Is there a specific reason to use a non default line length?
Take a look at the following [https://stackoverflow.com/questions/88942/why-does-pep-8-specify-a-maximum-line-length-of-79-characters/88948#88948](discussion)

2020-11-02 21:00 UTC, nathanegillett commented on tests/s3/test_extract_mpu_parts.py
> +        <CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> # noqa
What's this `#noqa` suppressing? It'd be nice if there was more accompanying info with these.

2020-11-02 21:00 UTC, nathanegillett commented on setup.py
> +        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",  # noqa
There's got to be a better way to suppress select lint errors rather than have these unexplained tags everywhere, right? Something like a .pylintrc file would be nice.

2020-11-02 21:00 UTC, nathanegillett commented on docs/conf.py
> -    "description": "Publishing microservice for Red Hat's Content Delivery Network",
I don't have a problem with limiting line length to 80 (79) but I don't think it's really necessary either. It's 2020, we all use an IDE and have 1080p+ displays. If we want to get technical, I believe PEP8 recommends length of 72 characters for docstrings. Should that be enforced as well?

BTW, where is line length even configured? I'm not seeing the metric anywhere.
Also, line 100 suggests 88 characters is expected. Should that and perhaps `page_width` be updated accordingly?

2020-11-02 21:19 UTC, rohanpm commented on docs/conf.py
> -    "description": "Publishing microservice for Red Hat's Content Delivery Network",
> Is there a specific reason to use a non default line length?

Originally, it comes from my opinion that 80 columns tends to result in code being wrapped too often, especially if you try to use meaningful variable and method names.  Making it slightly more generous at 100 seems to drastically cut down on cases where the code has to be formatted in an ugly manner to keep within the limit, especially if you are going to enforce this on items which aren't sanely able to be autoformatted like doc strings and string literals.

By now it's also about consistency between projects, as the teams working on this family of projects used 100 columns for a few years now, e.g. our standard CI setup in an (internal) Jenkins uses max-line-length=100 when running pylint over all projects; and this value was also used for projects with public CI for some years, e.g. see config in https://github.com/release-engineering/python-fastpurge/blob/master/tox.ini .  We want to use the same setting between projects so we're not reformatting code if we have to move or copy it from one project to another.

So, from my point of view, it was just a project setup bug / oversight that the line length wasn't set to 100 in this project already.  It's an unwanted difference from earlier projects maintained by the same people.

> Take a look at the following discussion

There's a ton of people arguing for every point of view there and no point of view seems particularly compelling.  This is an issue which can sustain bikeshedding indefinitely...

> BTW, where is line length even configured? I'm not seeing the metric anywhere.

There's numerous ways to configure it unfortunately... it can be read from tox.ini, pylintrc, pyproject.toml etc.  We've just got to configure it according to however our current tools use it.

> Also, line 100 suggests 88 characters is expected. Should that and perhaps page_width be updated accordingly?

Not sure (but not in this PR in any case).  I originally set that page_width to get the sources rendering inside of sphinx docs nicely on my browser and I guess it's been copied around uncritically since then.

2020-11-02 21:31 UTC, rohanpm requested changes
Could we please have any of the reformatting around line length taken out of this?

2020-11-02 21:31 UTC, rohanpm commented on setup.py
> +        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",  # noqa
I guess this noqa is for line length as the line happens to be 85 chars.

In my view this is a pretty good point in evidence that the default line length of 80 is just too short.  In my opinion, the above line (without noqa) is entirely reasonable.  It's not intended unnecessarily; it's not mixing too much on a single line.  I believe any method of reformatting this to fit within 80 chars would *decrease* readability rather than increase it.

So I think this line is a good example of why 100 columns is more reasonable.

2020-11-02 21:31 UTC, rohanpm commented on tests/s3/test_extract_mpu_parts.py
> +        <CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> # noqa
This would be line length again and I think is another point in favor of "80 chars is not enough", as this is completely readable to me and any reformatting is likely to make it only less readable.

2020-11-02 21:31 UTC, rohanpm commented on exodus_gw/__init__.py
> +from . import gateway, s3  # noqa
I see, I don't mind these hanging around for now but going forward we should perhaps use the `__all__` solution, like this:

```
__all__ = ["gateway", "s3"]
```

2020-11-02 21:31 UTC, rohanpm commented on docs/conf.py
> +    "description": "Publishing microservice for Red Hat's CDN",
Setting line length aside for a moment, I also don't like this change on its own merit.  Using an acronym without defining it first is bad form.

2020-11-03 06:37 UTC, lioramilbaum commented on docs/conf.py
> -    "description": "Publishing microservice for Red Hat's Content Delivery Network",
You might want to take a look at the PEP8 Style guide - https://www.python.org/dev/peps/pep-0008/#maximum-line-length.
The consistency issue is a good reason to continue working with the suggested line width. 
I will continue enforce the default PEP8 style guide in my code contributions. Let me know, when you find code to be unreadable due to this.

2020-11-03 06:45 UTC, lioramilbaum commented on tests/s3/test_extract_mpu_parts.py
> +        <CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> # noqa
I don't disagree with you and I don't want to get into bikeshedding.  Removing the `#noqa` stanza.

2020-11-03 06:53 UTC, lioramilbaum commented on setup.py
> +        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",  # noqa
Again, I see it differently than you do.

2020-11-03 15:10 UTC, nathanegillett requested changes

2020-11-03 15:10 UTC, nathanegillett commented on docs/conf.py
> +    # code
I agree that, if we're not limiting line length under the current 100 chars in this PR, the PR shouldn't include these length-type changes.

2020-11-03 15:58 UTC, lioramilbaum commented on docs/conf.py
> +    # code
I will remove those changes. Not a problem. 
Something for consider when providing a code review - 'Why does it bother if comment lines are wrapped?'

2020-11-03 16:23 UTC, nathanegillett commented on docs/conf.py
> +    # code
My reason for this request is that a PR or commit shouldn't include changes outside of its objective. If this change _was_ limiting line length, then it would make sense to implement that restriction throughout the project, but that's no longer the case so these changes are therefore unnecessary in implementing flake. Does that make sense?

Comment wrapping itself doesn't bother me at all. In fact, I tend to keep the length of my comments/docstring <=72 characters, per PEP8. That's a personal preference, though, and I don't currently have a strong desire to push that practice on anyone else.

2020-11-03 16:24 UTC, nathanegillett approved these changes

2020-11-03 16:40 UTC, lioramilbaum commented on docs/conf.py
> +    # code
I tend to agree that a PR or commit shouldn't include changes outside of its objective as a general rule. But, general rules are general.  Which means that we are using those rules when it is appropriate and band the rules when it is not. 
Our target is to produce a service which does what it needs to do in an effective way. 

As you said, comment wrapping is not a bad thing to do. It can be done in this PR or in another one.  Does it matter which PR?
Those changes are not pushing anyone to practice something which was not agreed.
Those changes are not making the code unreadable.

2020-11-03 17:52 UTC, nathanegillett commented on docs/conf.py
> +    # code
The point is that changes to wrap preexisting lines is unnecessary, as the enforced line length limit isn't changing, so said changes should not be made.

2020-11-03 19:40 UTC, crungehottman approved these changes

2020-11-03 21:29 UTC, rohanpm commented on docs/conf.py
> +    # code
I want to point out something in case it's overlooked:

Are you aware that this project already has an autoformatting tool (black) integrated with CI and a pre-commit hook (mentioned in README)?

One of the points of having an autoformatter is to cut down on exactly this kind of code style bikeshedding, because the rule is simply "your code is formatted as the autoformatter says - end of story".

I'm not sure if you just missed that we already use this tool, or made a conscious decision that it's not sufficient for whatever reason (which isn't explained anywhere).  Anyway I didn't reject this PR due to that, as I know that flake8 and black can be compatible if you configure the line length accordingly and I'd also like to get more experience with github actions.

So the PR as it stands is fine with me, but it's really galling that you would do:

- ignore the formatting tool already used by this project
- make a PR introducing a second slightly-incompatible tool & reformatting all code to fit that tool
- when reviewers complain about this mass reformatting, tell them that they shouldn't care about it

2020-11-04 08:55 UTC, lioramilbaum commented on docs/conf.py
> +    # code
Linting and formatting is not the [same](https://medium.com/@awesomecode/format-code-vs-and-lint-code-95613798dcb3#:~:text=Code%20linter%20works%20differently%20than,the%20whole%20codebase%2C%20and%20code). 
With that, I am not sure the assumptions you have listed are relevant/appropriate.

2020-11-04 08:56 UTC, merged

2020-11-04 13:46 UTC, nathanegillett commented on docs/conf.py
> +    # code
To change the layout of a file is the definition reformatting. In this case, preexisting lines in several files were wrapped. With the linter set to 100 character line length, those changes were no longer a result of the linting process.

If you're writing _new_ code or comments and want to format it a certain way (within reason), that's fine, but including changes to preexisting content for no particular reason will generally be met with resistance, as we've discussed.