Implement initial DynamoDB API [RHELDST-2161]
release-engineering/exodus-gw pull request #90
Opened 2020-11-19 00:55 UTC by nathanegillett

This commit introduces functions to write items to a DynamoDB table,
with retry, exponential backoff, and jitter, and roll back the write
operation in the event that not all items were successfully written.

2020-11-19 01:07 UTC, nathanegillett commented
For the record, I'm not appreciating container build in CI and flake enforcing import order.

2020-11-19 06:39 UTC, lioramilbaum commented
> For the record, I'm not appreciating container build in CI and flake enforcing import order.

You might want to challenge both decisions with submitting a PR or preparing a write-up.  This is the most effective way to get the buy-in of the other team members. Does that make sense?

2020-11-19 17:13 UTC, crungehottman commented on exodus_gw/routers/dynamodb.py
> +    AssertionError,
This scenario is probably extremely unlikely so feel free to ignore: if batch_write_item were to fail on an assertion error, the retry would commence. Did you consider using backoff.on_predicate here instead?

2020-11-19 17:13 UTC, crungehottman commented on exodus_gw/routers/dynamodb.py
> +)
I'm curious if you looked into adding jitter: https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/

2020-11-19 17:57 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +    max_time=0,
Good catch! I forgot to revert that after some testing.

2020-11-19 17:57 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +)
A "full jitter" is applied by default.

2020-11-19 18:06 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +    AssertionError,
It seems unlikely that boto3/botocore would raise an assertion error but, yes, it would trigger a retry. I'll look into it a bit more. Using `on_predicate` might be better.

2020-11-19 18:08 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +)
I think I misread the documentation, assumed full jitter was automatically applied, and removed the kwarg from the decorators. Looking at the code, that doesn't seem to be right. I'll put those jitter kwargs back. Thanks.

2020-11-19 18:19 UTC, nathanegillett commented
Comments on this PR point to a hole in test coverage. Will mark as ready when that's patched.

2020-11-19 18:22 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +)
Oh, I found it. `full_jitter` is applied by default.
https://github.com/litl/backoff/blob/128bba5377568b8e2c0230973e887e0b4f5da800/backoff/_decorator.py

2020-11-19 18:40 UTC, crungehottman commented on exodus_gw/routers/dynamodb.py
> +)
Whoops, I missed that. Sorry for the noise :)

2020-11-19 18:55 UTC, nathanegillett commented
Switched from exception-based retry to predicate and added `test_batch_write_retry` to ensure it works.

2020-11-19 21:13 UTC, crungehottman commented on exodus_gw/routers/dynamodb.py
> +    lambda response: response["UnprocessedItems"],
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html#API_BatchGetItem_ResponseSyntax 

```suggestion
    lambda response: response["UnprocessedKeys"],
```

2020-11-19 21:20 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +    lambda response: response["UnprocessedItems"],
The response this function returns (and therefore checks) is from `batch_write_item`. While the function does call `batch_get_item` to tell us which of the items are actually on the table, that response, seen filtered on line 48, is consumed by the `batch_write_item` call.

2020-11-19 21:25 UTC, crungehottman commented on exodus_gw/routers/dynamodb.py
> +    lambda response: response["UnprocessedItems"],
Hmm, nevermind the above suggestion. I now see that this was referring to the response of batch_write_item. But, it's still possible for this function to return a batch_get_item response, which would result in a KeyError.

2020-11-19 21:27 UTC, rohanpm requested changes

2020-11-19 21:27 UTC, rohanpm commented on exodus_gw/routers/dynamodb.py
> +            response = await ddb.batch_get_item(
I could be missing something here but I don't think we need to do both "get items" and then "delete items which exist" because I expect a DeleteRequest to work just fine even if the item doesn't already exist.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DeleteItem.html says:

> Unless you specify conditions, the DeleteItem is an idempotent operation; running it multiple times on the same item or attribute does not result in an error response.

I think we should just directly request deletion of the relevant keys without first trying to detect which of them actually exist.

In fact I think we pretty much have to do it that way, or make other changes, due to eventual consistency.  https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html says:

> When you read data from a DynamoDB table, the response might not reflect the results of a recently completed write operation.

...which means that this code may not even be able to reliably find whatever items it has recently written.

2020-11-19 21:27 UTC, rohanpm commented on exodus_gw/routers/dynamodb.py
> +        raise exc
The logging method here is not correct I believe, as the point of the `LOG.exception` method is that it already implicitly logs the current exception, i.e. you're meant to use it like:

```
LOG.exception("Error while doing foo")
```

...and then it'll result in a log message like:

```
Error while doing foo
<full exception details>
```

If you pass the exception to `LOG.exception` then I think you're going to just get the exception logged twice, e.g.

```
<str(exc)>
<full exception details>
```

You also don't have to explicitly catch the exception object because LOG.exception knows how to access it already.  So, in summary I think this code should be more like:

```suggestion
    except Exception:
        LOG.exception("Exception while rolling back %s items on %s", len(items), table)
        raise
```

2020-11-19 21:27 UTC, rohanpm commented on exodus_gw/routers/dynamodb.py
> +        LOG.exception(exc)
Same comment here about usage of LOG.exception.

2020-11-19 21:27 UTC, rohanpm commented on exodus_gw/routers/dynamodb.py
> +async def batch_write(env: str, items: List[dict]):
I think there is a bit missing in the overall logic, although maybe it's just planned for later:

Can you clarify how many "items" are expected to be passed here?  One publish might have something like 500,000 items.  Is the caller expected to divide that into chunks of 25 and call this function in a loop, and that's just not written yet?  Or was it expected that this can accept any number of items, and the backoff decorator will end up iterating through them in chunks according to the UnprocessedItems.  If the latter, I don't think that will work well.

I'm also not sure if rollback can be implemented correctly until that looping code exists.  The rollback behavior mustn't just roll back a single batch, e.g. if we're doing a publish with 500,000 items and we start getting errors around item 250,000, it should attempt to roll back all the items leading up to that and not just the latest batch of 25.

2020-11-19 21:27 UTC, rohanpm commented on exodus_gw/routers/dynamodb.py
> +    max_time=600,
I suggest these numbers should be customizable by env vars, so if we've picked the wrong values we can easily change them (or test changes to them).  Ideally the env vars are read via Settings class.

2020-11-19 21:27 UTC, rohanpm commented on exodus_gw/routers/dynamodb.py
> +    max_time=600,
This is probably too large for this operation.  If we get part way through and start to hit errors, and ultimately we can't recover from them, that can be customer-impacting (e.g. can cause yum to fail).  If we set this up so it spends max X minutes retrying this, that's like saying we'll accept customer-impacting broken data on the CDN for up to X minutes before giving up and trying to fix things, so X should not be too high.

To me it makes sense for the rollback operation to have a higher max time, but this one probably should be quite shorter, maybe around 60?

2020-11-19 21:27 UTC, rohanpm commented on tests/routers/test_dynamodb.py
> +        assert "[ERROR] Bad write" in captured.out
Per my earlier comments on usage of LOG.exception:

I think we'd want this message to rather give some context on what was being done when the exception happened, e.g. "[ERROR] Exception while writing 2 item(s) to 'test'\n<exception details>".

2020-11-19 21:34 UTC, rohanpm commented
A bit of a higher-level comment on this - I would recommend against spending too much time developing the rollback stuff before we have figured out the execution environment for background tasks, because I think these things need to be tied together.

If you've just set up rollback by decorators and such so it all happens in the current process as done here, that should work fine in the case of dynamodb errors.  But this isn't the only scenario, this is also an important scenario:

- exodus-gw worker is in the middle of writing 500,000 items
- the process/container where the worker is running is unexpectedly killed around item 250,000

The system MUST somehow detect this and recover, i.e. resume the interrupted work or roll it back; we can't leave the work partially completed if a process unexpectedly dies.  So this implies to me that the rollback stuff needs to be somehow designed in accordance with how the background workers are picking up tasks in the first place.

2020-11-20 17:07 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +    lambda response: response["UnprocessedItems"],
Ah, yeah, I suppose if the `items` list resulting from the query was empty it would return the query's `reponse`. We definitely don't want that.  Thanks.

2020-11-20 17:10 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +async def _batch_write_rollback(details: dict):
Yeah, that looks better to me as well. Thanks.

2020-11-20 17:43 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +            response = await ddb.batch_get_item(
Hmm. I was under the impression that an error would be raised if you tried to delete a non-existent key. Re-reading the documentation again, I'm not seeing anything stating or inferring that so maybe it's safe.

That's a good point about eventual consistency, though, that I hadn't considered either.

2020-11-20 17:44 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +    lambda response: response["UnprocessedItems"],
Solved this by removing the query altogether, as Rohan suggested.

2020-11-20 17:53 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +async def batch_write(env: str, items: List[dict]):
> [...] this can accept any number of items, and the backoff decorator will end up iterating through them in chunks according to the UnprocessedItems. If the latter, I don't think that will work well.

That's right. Could you expand a bit on what that might not work to our liking?

> [...] if we're doing a publish with 500,000 items and we start getting errors around item 250,000, it should attempt to roll back all the items leading up to that and not just the latest batch of 25.

Great point. I'll have to think on a solution for this.

2020-11-20 17:59 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +    max_time=600,
Yeah, I was on the fence with this before, but will do.

2020-11-22 23:31 UTC, rohanpm commented on exodus_gw/routers/dynamodb.py
> +async def batch_write(env: str, items: List[dict]):
>> [...] this can accept any number of items, and the backoff decorator will end up iterating through them in chunks according to the UnprocessedItems. If the latter, I don't think that will work well.
>
> That's right. Could you expand a bit on why that might not work to our liking?

Mainly because of the timing/performance.  One of the purposes of these backoff decorators is to "back off", i.e. wait a bit of time before trying again.  But it doesn't make sense to do that if everything is working normally, you'd rather want to go as fast as possible.

e.g. if you have 500,000 items you do not want this behavior:

- call batch write with 500,000
- write returns 499,975 items unprocessed
- backoff decorator sleeps a bit
- call batch write with 499,975 items
- write returns 499,950 items unprocessed
- backoff decorator sleeps a bit longer...

...etc.  Those sleeps exist for no reason and it would give completely unusable performance with default tuning of backoff decorator.

It seems like that's not possible anyway, https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html says that a batch write request with more than 25 items is simply rejected without even attempting the write.  So, as this is written right now, calling this method with more than 25 items is just not going to work at all, the logic for splitting up a large item list into chunks of 25 has to exist somewhere.

Probably a good idea to ensure tests are updated with some cases of >25 items.

Or alternatively, the scope of this PR could be limited to handling only <= 25 items and we implement the splitting into batches in later PRs.

2020-12-01 20:33 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +async def batch_write(env: str, items: List[dict]):
Oh, right, of course. Back offs must've slipped my mind at the time.

And, yeah, I guess I misread the doc. Thanks.
The scope for this will be limited to <= 25, then, and in a subsequent PR I'll implement something to split up all the items for writing.

I wonder if executors would be helpful in running multiple `batch_write`s, the results of which could inform the rollback decision. @rohanpm

2020-12-02 15:22 UTC, nathanegillett commented
I've finished tweaking finally. Sorry for any update spam.
Please review when able, @rohanpm @crungehottman @lioramilbaum @dichen16

2020-12-02 16:50 UTC, crungehottman approved these changes

2020-12-03 21:54 UTC, rohanpm reviewed
Only saw that one minor logging issue.

2020-12-03 21:54 UTC, rohanpm commented on exodus_gw/routers/dynamodb.py
> +        LOG.exception("Cannot process more than 25 items")
I don't think this is the right logger method, `exception` is meant for cases where there is a genuine Python exception.  https://docs.python.org/3/library/logging.html#logging.exception mentions "This function should only be called from an exception handler".  This should probably just be LOG.error.

2020-12-04 14:50 UTC, nathanegillett commented
It seems as though all the publish endpoints are landing in 'routers/gateway.py', so that's probably where I'll end up placing the commit endpoint (for which this PR exists). Therefore, the 'dynamodb.py' doesn't need to be in routers (since it won't contain any endpoints) and can probably live in 'gateway.py' or as a method of the dynamodb client class.
WDYT, @crungehottman, @rohanpm, @lioramilbaum?

2020-12-04 14:54 UTC, nathanegillett commented on exodus_gw/routers/dynamodb.py
> +)
I may just delete this from the PR, as dramatiq, which we'll use for multi-process, has retry and exponential back-off built into its "actors".

2020-12-04 19:10 UTC, nathanegillett commented
closing, -> #95

2020-12-04 19:10 UTC, closed without merging